#!/usr/bin/env scheme-script
;; Buffet integration; shared entry/table fixtures cover their generic mechanics.
(import (chezscheme))
(include "tests/roots.ss")
(test-roots! 'base)
(test-evaluate!
  '(begin
     (import (prefix (apps buffet) buffet:) (prefix (head head) head:) (prefix (service window) window:)
             (prefix (apps bindings) bindings:) (prefix (head binding-list) listing:)
             (prefix (head widget) widget:) (prefix (head window-control) window-control:)
             (prefix (head table) table:) (prefix (head entry) entry:)
             (prefix (head control) control:) (prefix (head range) range:)
             (prefix (head interaction) interaction:) (prefix (head routing) routing:)
             (prefix (head keymap) keymap:) (prefix (core kernel) kernel:)
             (prefix (head mouse) mouse:) (prefix (head mode) mode:)

             (prefix (state store) store:) (prefix (state collection) collection:)
             (prefix (state model) model:) (prefix (state view) view:)
             (prefix (state catalogue) catalogue:) (prefix (state connection) connection:)
             (prefix (foundation string) string:) (prefix (test) test:))
     (for-each kernel:load-module! '("window-control" "entry" "control" "table" "buffet" "bindings"))
     (define manager (window:create-manager! #f))
     (define window (window:current manager))
     (widget:mount! manager 'buffet-test)
     (define inspector #f)
     (define (help-show!)
       (unless inspector (set! inspector (bindings:create! #f '() manager)))
       (widget:mount! inspector 'buffet-inspector)
       (widget:prepare! inspector 240 20))
     (define (help-hide!) (widget:unmount! inspector))
     (define (get xs key) (cdr (assq key xs)))
     (define (help-record)
       (widget:pump!)
       (model:snapshot (view:source (interaction:snapshot inspector))))
     (define (help-rows) (apply append (map (lambda (p) (get (model:snapshot (cdr p)) 'value)) (get (get (help-record) 'value) 'parts))))
     (define (help-text)
       (string:join (map (lambda (r) (string-append (or (cadr r) "") " " (string:join (caddr r) " ") " " (cadddr r) " " (list-ref r 4))) (help-rows)) "\n"))
     (define (await-help! name predicate)
       (test:await name (lambda () (head:before-frame!) (predicate (help-text)))))
     (define (contains? text needle) (and (string:search text needle 0 (string-length text)) #t))
     (define (child id name) (cadr (assq name (view:children (interaction:snapshot id)))))
     (define (root) manager)
     (define (app) (window:document manager window))
     (define (table) (child (app) 'table))
     (define (entry) (child (child (table) 'filter) 'entry))
     (define (query) (view:source (interaction:snapshot (table))))
     (define (state) (view:state (interaction:snapshot (table))))
     (define (selection) (get (state) 'selection))
     (define (draw! id width height)
       (range:pump!) (widget:pump!)
       (let ([f (widget:prepare! id width (if (equal? id manager) (+ height 1) height))])
         (widget:present! (list (list f 0 0)))
         (if (equal? id manager) (widget:prepared (app)) f)))
     (define (settle!)
       (test:await 'buffet-ready
         (lambda ()
           (draw! (root) 120 15)
           (let* ([r (collection:summary (query))] [v (get r 'value)] [s (selection)])
             (and (eq? (get v 'status) 'ready) s (= (cadr s) (get v 'generation))
                  (equal? (get v 'input-filter)
                    (store:line (view:source (interaction:snapshot (entry))) 0))
                  (let ([r (range:read (query) (cadr s) 0 64 '(modified flags name lines mode file archived-at archive expires-at))]) (eq? (car r) 'ready)))))))
     (define (select! b)
       (let ([ref b])
         (table:select! (table) ref)
         ;; A ready prior generation can precede metadata or archive changes.
         ;; Wait for the facts that fence the selected row's next action.
         (test:await 'buffet-selected-current-facts
           (lambda ()
             (settle!)
             (let* ([s (selection)] [r (collection:lookup (query) (cadr s) ref '(name version))]
                    [m (and (eq? (car b) 'buffer) (cadar (cadr (store:metadata (list b)))))])
               (and (equal? (caddr s) ref) (eq? (car r) 'ready) (pair? (list-ref r 4))
                 (let ([cells (caddr (car (list-ref r 4)))])
                   (and (equal? (assq 'name cells) (list 'name 'ready (if m (get m 'name) (get (view:options (view:snapshot b)) 'name))))
                     (or (not m) (equal? (assq 'version cells) (list 'version 'ready (get m 'version))))))))))))
     (define (press! . keys)
       (for-each (lambda (key) (routing:input! manager (list 'key key (and (= (string-length key) 1) key)))) keys))
     (define a (store:create! head:ui-actor "buffet-a" '("")))
     (define b (store:create! head:ui-actor "buffet-b" '("")))
     (define path "/tmp/buffet-path/with-many-components/file.scm")
     (store:set-property! head:ui-actor a 'file path)
     (window-control:open-document! window a) (window-control:open-document! window b)
     (draw! manager 120 15)
     (let ([models (model:ids)])
       (test:check 'default-catalogue-neighbor-needs-no-query-or-presentation
         (list (catalogue:neighbor head:ui-actor #f a 'next)
           (equal? models (model:ids))) (list b #t)))
     (buffet:open! window) (settle!)
     (let* ([lines (widget:frame-lines (draw! (root) 120 15))] [heading (cadr lines)]
            [name (string:search heading "Buffer" 0 120)] [next (string:search heading "Lines" 0 120)])
       (test:check 'short-buffer-names-leave-room-for-the-full-file-path
         (list (<= (- next name 2) 12)
           (and (exists (lambda (line) (string:search line path 0 (string-length line))) (cddr lines)) #t)) '(#t #t)))
     (test:check 'default-previous-and-self-name
       (list (caddr (selection)) (get (view:options (view:snapshot (app))) 'name))
       (list a "<buffet>"))
     (press! "RET")
     (test:check 'enter-opens-the-previous-document (equal? (app) a) #t)
     (buffet:open! window) (settle!) (press! "ESC")
     (test:check 'escape-restores-origin (equal? (app) a) #t)
     (buffet:open! window) (settle!)
     (define host (root)) (define original-app (app)) (define original-table (table)) (define original-query (query))
     (define filter-id (view:source (interaction:snapshot (entry))))
     (test:check 'internal-filter-is-not-a-switchable-document
       (store:property filter-id 'internal #f) #t)
     (let ([focus (widget:focused (root))])
       (help-show!)
       (await-help! 'initial-binding-list (lambda (text) (contains? text "Composition")))
       (let ([text (help-text)])
         (test:check 'keys-lists-buffet-and-entry-bindings-without-changing-focus
           (list (for-all (lambda (needle) (and (string:search text needle 0 (string-length text)) #t))
                   '("buffet keys" "widget-entry keys" "C-x D" "C-u" "F6" "Widget commands" "table (table): '(model "
                     "activate" "trash" "delete" "buffet:choose!" "buffet:kill!" "buffet:delete!" "basis)"
                     "→ (widget:invoke!" "→ (widget:act!" "→ (buffet:kill!"))
             (not (string:search text "anonymous command" 0 (string-length text)))
             (not (string:search text "(widget:target)" 0 (string-length text)))
             (not (string:search text "Unavailable target." 0 (string-length text)))
             (equal? focus (widget:focused (root)))) '(#t #t #t #t #t)))
       (test:check 'table-command-keys-show-model-literals-and-explicit-command-names
         (map (lambda (keys)
                (keymap:action-text (keymap:binding-action (cdr (keymap:resolved-binding 'buffet keys)))
                  (list (cons widget:target (app))))) '(("RET") ("C-k") ("C-x" "D")))
         (map (lambda (command) (format "(table:invoke! (widget:descendant '~s 'table) '~a)" (app) command))
           '(activate trash delete)))
       (test:check 'archive-binding-exposes-every-forwarding-step
         (map cadr
           (keymap:action-trace (keymap:binding-action (cdr (keymap:resolved-binding 'buffet '("C-k"))))
             (list (cons widget:target (app)))))
         (list (format "(table:invoke! (widget:descendant '~s 'table) 'trash)" (app))
           (format "(table:invoke! '~s 'trash)" (table))
           (format "(widget:invoke! '~s 'trash selection basis)" (table))
           (format "(widget:act! '~s 'kill selection basis)" (app))
           (format "(buffet:kill! '~s selection basis)" (app))))
       (let ()
         (define (italic-text width)
           (apply string-append
             (map (lambda (r) (apply string-append (map (lambda (span) (substring (cadr r) (car span) (cdr span))) (caddr r))))
               (vector->list (listing:fit (help-rows) width)))))
         (let ([wide (italic-text 240)] [narrow (italic-text 50)])
           (test:check 'unresolved-arguments-stay-italic-through-wrapping-with-commands-and-literals-plain
             (list (string=? wide narrow)
               (for-all (lambda (s) (and (string:search wide s 0 (string-length wide)) #t)) '("selection" "basis" "computed"))
               (for-all (lambda (s) (not (string:search wide s 0 (string-length wide)))) '("table:invoke!" "widget:invoke!" "'activate"))) '(#t #t #t))))
       (select! a) (head:before-frame!)
       (let* ([id (cdr (assq 'listing (get (get (help-record) 'value) 'parts)))] [revision (model:revision id)])
         (select! b) (head:before-frame!)
         (test:check 'selection-does-not-rebuild-static-key-help (= revision (model:revision id)) #t))
       (table:move! (table) 'first) (settle!)
       (let* ([before (selection)]
              [action (keymap:binding-action (cdr (keymap:resolved-binding 'buffet '("DOWN"))))]
              [text (keymap:action-text action (list (cons widget:target (app))))])
         (parameterize ([widget:target #f]) (eval (read (open-input-string text))))
         (settle!)
         (test:check 'listed-buffet-call-works-in-eval-outside-key-dispatch
           (list (string:prefix? "(table:move! (widget:descendant '(model " text) (not (equal? (caddr before) (caddr (selection))))) '(#t #t)))
       (widget:focus! (root) (child (child (table) 'body) 'rows))
       (await-help! 'focused-binding-list (lambda (text) (not (contains? text "widget-entry keys"))))
       (let ([text (help-text)])
         (test:check 'keys-follows-widget-focus
           (and (string:search text "buffet keys" 0 (string-length text))
             (not (string:search text "widget-entry keys" 0 (string-length text)))) #t))
       (help-hide!) (widget:focus! (root) focus) (settle!))
     (let* ([id (table)] [options (view:options (interaction:snapshot id))]
            [activate (assq 'activate (cdr (assq 'commands options)))])
       (define (replace! action)
         (interaction:flush!)
         (interaction:arrange! head:ui-actor
           (list (list id (get (model:snapshot id) 'revision) (view:children (interaction:snapshot id))
                   (map (lambda (p)
                          (if (eq? (car p) 'commands)
                            (cons 'commands (map (lambda (c) (if (eq? (car c) 'activate)
                                                               (list 'activate (cadr c) action (cadddr c)) c)) (cdr p))) p)) options)))
           (list (list (root) (view:generation (interaction:snapshot (root))))))
         (head:before-frame!))
       (help-show!)
       (replace! 'unregistered-action)
       (await-help! 'rewired-binding-list (lambda (text) (contains? text "unregistered-action")))
       (test:check 'keys-shows-rewired-unavailable-command-template
         (let ([text (help-text)])
           (for-all (lambda (needle) (and (string:search text needle 0 (string-length text)) #t))
             '("Unavailable target." "widget:act!" "unregistered-action"))) #t)
       (replace! (caddr activate))
       (await-help! 'restored-binding-list (lambda (text) (not (contains? text "unregistered-action"))))
       (test:check 'keys-updates-restored-command
         (let ([text (help-text)])
           (not (string:search text "unregistered-action" 0 (string-length text)))) #t)
       (help-hide!) (settle!))
     (let ([focus (widget:focused (root))] [selected (selection)] [sort (get (get (collection:summary (query)) 'value) 'sort)])
       (head:set-mouse-position! '(2 . 2)) (help-show!) (settle!) (head:before-frame!)
       (await-help! 'heading-pointer-binding (lambda (text) (contains? text "table:toggle-sort!")))
       (let* ([lines (help-rows)]
              [header (cadr (assoc '(click primary ()) (mouse:bindings)))])
         (head:before-frame!)
         (test:check 'mouse-help-first-inspects-heading-without-changing-state
           (list (cadar lines) (equal? lines (help-rows))
             (keymap:call-action-procedure header) (cadr (keymap:call-action-arguments header))
             (caddr (selection)) (get (get (collection:summary (query)) 'value) 'sort) (widget:focused (root)))
           (list "Mouse bindings" #t table:toggle-sort! 'modified (caddr selected) sort focus))
         (head:set-mouse-position! '(2 . 3)) (head:before-frame!)
         (await-help! 'row-pointer-binding (lambda (text) (not (equal? lines (help-rows)))))
         (let* ([bindings (mouse:bindings)] [row (cadr (assoc '(click primary ()) bindings))])
           (test:check 'hover-changes-mouse-section-and-includes-wheel
             (list (not (equal? lines (help-rows))) (keymap:call-action-procedure row)
               (and (assoc '(wheel up ()) bindings) (assoc '(wheel down ()) bindings) #t)
               (widget:focused (root)))
             (list #t table:choose! #t focus)))
         (head:set-mouse-position! '(1000 . 1000)) (head:before-frame!)
         (await-help! 'empty-pointer-binding
           (lambda (text) (not (exists (lambda (r) (and (pair? (car r)) (eq? (caar r) 'mouse))) (help-rows)))))
         (test:check 'leaving-shown-target-clears-mouse-section
           (exists (lambda (r) (and (pair? (car r)) (eq? (caar r) 'mouse))) (help-rows)) #f))
       (head:set-mouse-position! #f) (help-hide!) (settle!))
     (let ([heading (cadr (widget:frame-lines (draw! (root) 120 15)))])
       (press! "b" "u" "f" "f" "e" "t" "-" "b") (settle!)
       (test:check 'typing-from-entry-filters-in-base-without-shifting-columns
         (list (get (get (collection:summary (query)) 'value) 'count) (caddr (selection))
           (equal? heading (cadr (widget:frame-lines (draw! (root) 120 15)))))
         (list 1 b #t)))
     (press! "C-u") (settle!)
     (define before (selection))
     (press! "UP") (settle!)
     (test:check 'arrows-from-filter-reach-table (not (equal? before (selection))) #t)
     (table:sort-by! (table) '((name descending))) (settle!)
     (window-control:open-document! window a)
     (buffet:previous! window)
     (test:check 'global-cycle-uses-compound-order (equal? (app) b) #t)
     (buffet:open! window) (settle!)
     (select! b)
     (define stale (selection)) (define stale-basis (get (state) 'basis))
     (store:rename! head:ui-actor b "buffet-b-renamed")
     (test:check 'stale-destructive-action-refuses
       (test:raises? (lambda () (buffet:kill! (app) stale stale-basis))) #t)
     (settle!) (select! b) (press! "C-k") (settle!)
     (test:check 'trash-retires-the-head-buffer
       (list (and (store:property b 'trashed #f) #t) (member b (window:documents manager window))) '(#t #f))
     (select! b)
     (let ([text (string:join (widget:frame-lines (draw! (root) 120 15)) "\n")])
       (test:check 'archive-age-and-retention-are-presented
         (and (string:search text " ago" 0 (string-length text)) (string:search text " left" 0 (string-length text)) #t) #t))
     (press! "RET")
     (test:check 'archive-restore-preserves-identity
       (list (app) (store:property b 'trashed #f))
       (list b #f))
     (buffet:open! window) (settle!)
     (select! b) (press! "C-k") (select! b)
     (press! "C-x" "D")
     (test:check 'permanent-archive-delete (store:exists? b) #f)
     (settle!)
     (let* ([picker (app)]
            [id (view:create! head:ui-actor #f 'row 1 '((name . "<buffet-local>") (catalogue . #t)) '() window)]
            [local id])
       (window-control:open-document! window picker) (head:before-frame!)
       (select! local)
       (let ([old (selection)] [basis (get (state) 'basis)])
         (let* ([source (get (get (model:snapshot (query)) 'value) 'source)]
                [before (model:revision source)])
           (view:set-state! head:ui-actor id #f '(retained interaction))
           ;; The neighbor request is a worker barrier, not a timing delay.
           (catalogue:neighbor head:ui-actor (query) local 'next)
           (test:check 'view-interaction-does-not-republish-catalogue-metadata
             (model:revision source) before))
         (view:arrange! head:ui-actor
           (list (list id (model:revision id) '()
                   (map (lambda (p) (if (eq? (car p) 'name) '(name . "<buffet-local-renamed>") p))
                     (view:options (view:snapshot id))))) '())
         (test:check 'view-metadata-fences-retirement-without-a-lease-change
           (test:raises? (lambda () (buffet:kill! (app) old basis))) #t))
       (select! local) (press! "C-k")
       (test:check 'table-activation-retires-view-and-placement
         (list (model:snapshot id) (member local (window:documents manager window))) '(#f #f))
       (settle!))
     ;; The generic window fixture covers inactive clicks and focus policy;
     ;; retain Buffet's independent metadata/width and hover/wheel invariants.
     (let* ([fork (view:fork! head:ui-actor original-app)]
            [fork-table (begin (widget:mount! fork 'buffet-peer) (child fork 'table))])
       (test:check 'forks-view-state-and-shares-query
         (list (equal? original-table fork-table)
           (equal? original-query (view:source (interaction:snapshot fork-table)))) '(#f #t))
       (draw! fork 27 8)
       (let ([wide (widget:frame-lines (draw! host 300 15))])
         (test:check 'split-width-does-not-truncate-peer-metadata
           (and (string:search (cadr wide) "Modified" 0 300)
             (string:search (cadr wide) "File" 0 300) (= (string-length (cadr wide)) 300)) #t))
       (settle!)
       (let* ([s (selection)] [rank (list-ref (collection:rank original-query (cadr s) a) 3)] [row (+ 2 rank)])
         (widget:pointer! '(pointer move none ()) 3 row)
         (let ([frame (draw! host 120 15)])
           (test:check 'hover-uses-shared-candidate-style
             (vector-ref (widget:frame-styles frame row (list-ref (widget:frame-lines frame) row)) 0) 'candidate-hover))
         (widget:pointer! '(scroll 0 3 cells) 3 row)
         (test:check 'wheel-never-changes-selection (selection) s))
       (widget:unmount! fork))
     ;; Two unmounted constructors are independent; explicit query reuse is
     ;; borrowing, so releasing the first view cannot disconnect its sibling.
     (define independent (buffet:create! #f '()))
     (let ([transient (catalogue:create-source! head:ui-actor "/home" 'transient)])
       (test:check 'transient-owner-cannot-orphan-a-persistent-filter
         (test:raises? (lambda () (catalogue:create-query! head:ui-actor transient))) #t)
       (model:retire! head:ui-actor transient (get (model:snapshot transient) 'revision)))
     (define borrowed (buffet:create! #f '() original-query))
     (widget:mount! borrowed 'embedded)
     (draw! borrowed 44 8)
     (test:check 'constructor-sharing-is-explicit
       (list (equal? original-query (view:source (view:snapshot (cadr (assq 'table (view:children (view:snapshot independent)))))))
         (equal? original-query (view:source (interaction:snapshot (child borrowed 'table))))) '(#f #t))
     (test:check 'unconnected-embedded-open-has-no-window-fallback
       (test:raises? (lambda () (buffet:choose! borrowed (selection) (get (state) 'basis)))) #t)
     (widget:unmount! host)
     (entry:insert! (child (child (child borrowed 'table) 'filter) 'entry) "buffet-a")
     (test:await 'borrowed-filter-still-connected
       (lambda () (= (get (get (collection:summary original-query) 'value) 'count) 1)))
     (test:check 'query-owns-filter-after-original-view-closes (store:exists? filter-id) #t)
     (widget:unmount! borrowed)
     (let ([r (model:snapshot original-query)]) (model:retire! head:ui-actor original-query (get r 'revision)))
     (test:await 'query-releases-owned-filter (lambda () (not (store:exists? filter-id))))
     (test:finish! 'buffet)))
