#!/usr/bin/env scheme-script
;; Buffet integration; shared entry/table fixtures cover their generic mechanics.
(import (chezscheme))
(include "tests/roots.ss")
(test-roots! 'base)
(eval
  '(begin
     (import (prefix (apps buffet) buffet:) (prefix (head head) head:)
             (prefix (apps keys) keys:)
             (prefix (head widget) widget:) (prefix (head window) window:)
             (prefix (head table) table:) (prefix (head entry) entry:)
             (prefix (head control) control:) (prefix (head range) range:)
             (prefix (head interaction) interaction:) (prefix (head dispatch) dispatch:)
             (prefix (head keymap) keymap:) (prefix (head edit) edit:) (head literal)
             (prefix (head mouse) mouse:)
             (prefix (head document) document:) (prefix (head paint) paint:)
             (prefix (state store) store:) (prefix (state collection) collection:)
             (prefix (state model) model:) (prefix (state view) view:)
             (prefix (state catalogue) catalogue:) (prefix (state connection) connection:)
             (prefix (foundation string) string:) (prefix (test) test:))
     (edit:init!) (interaction:init!) (widget:init!) (window:init!) (entry:init!) (control:init!) (table:init!) (buffet:init!) (keys:init!)
     (paint:window-layout)
     (define (get xs key) (cdr (assq key xs)))
     (define (child id name) (cadr (assq name (view:children (interaction:snapshot id)))))
     (define (root) (head:buffer-fact (head:current-buffer) 'widget-id #f))
     (define (app) (child (root) 'app))
     (define (table) (child (app) 'table))
     (define (entry) (child (child (table) 'filter) 'entry))
     (define (query) (view:source (interaction:snapshot (table))))
     (define (state) (view:state (interaction:snapshot (table))))
     (define (selection) (get (state) 'selection))
     (define (draw! id width height)
       (range:pump!) (widget:pump!)
       (let ([f (widget:prepare! id width height)]) (widget:present! (list (list f 0 0))) f))
     (define (settle!)
       (test:await 'buffet-ready
         (lambda ()
           (draw! (root) 120 15)
           (let* ([r (collection:summary (query))] [v (get r 'value)] [s (selection)])
             (and (eq? (get v 'status) 'ready) s (= (cadr s) (get v 'generation))
               (let ([r (range:read (query) (cadr s) 0 64 '(modified flags name lines mode file archived-at archive expires-at version))]) (eq? (car r) 'ready)))))))
     (define (select! b)
       (table:select! (table) (document:reference b)) (settle!))
     (define (press! . keys) (for-each dispatch:key! keys))
     (define (binding key id) (keymap:binding-action (cdr (keymap:resolved-binding 'buffet key)) id))
     (define a (head:new-buffer! "buffet-a"))
     (define b (head:new-buffer! "buffet-b"))
     (define path "/tmp/buffet-path/with-many-components/file.scm")
     (head:buffer-file-set! a path)
     (head:show-buffer! a) (head:show-buffer! b)
     (buffet:open!) (settle!)
     (let* ([lines (widget:frame-lines (draw! (root) 120 15))] [heading (cadr lines)]
            [name (string:search heading "Buffer" 0 120)] [next (string:search heading "Lines" 0 120)])
       (test:check 'short-buffer-names-leave-room-for-the-full-file-path
         (list (<= (- next name 2) 12)
           (and (exists (lambda (line) (string:search line path 0 (string-length line))) (cddr lines)) #t)) '(#t #t)))
     (test:check 'default-previous-and-self-name
       (list (caddr (selection)) (head:buffer-name (head:current-buffer)))
       (list (document:reference a) "<buffet>"))
     (press! "RET")
     (test:check 'enter-opens-the-previous-document (eq? (head:current-buffer) a) #t)
     (buffet:open!) (settle!) (press! "ESC")
     (test:check 'escape-restores-origin (eq? (head:current-buffer) a) #t)
     (buffet:open!) (settle!)
     (define host (root)) (define original-app (app)) (define original-table (table)) (define original-query (query))
     (define filter-id (cadr (view:source (interaction:snapshot (entry)))))
     (test:check 'internal-filter-is-not-a-switchable-document
       (exists (lambda (b) (equal? filter-id (head:buffer-store-id b))) (head:buffers)) #f)
     (let ([focus (widget:focused (root))])
       (select! a) (press! "C-x" "TAB")
       (let ([text (string:join (vector->list (head:buffer-lines (head:window-buffer (head:popup)))) "\n")])
         (test:check 'keys-lists-buffet-and-entry-bindings-without-changing-focus
           (list (filter (lambda (needle) (not (string:search text needle 0 (string-length text))))
                   '("buffet keys" "widget-entry keys" "C-x D" "C-u" "F6" "Global keys" "edit:kill-buffer!" "Kill a buffer" "Unavailable:"))
             (not (string:search text "anonymous command" 0 (string-length text)))
             (not (string:search text "(widget:target)" 0 (string-length text)))
             (equal? focus (widget:focused (root)))) '(() #t #t #t)))
       (table:move! (table) 'first) (settle!)
       (let* ([before (selection)]
              [action (keymap:binding-action (cdr (keymap:resolved-binding 'buffet '("DOWN"))))]
              [text (keymap:action-text action (list (cons widget:target (app))))])
         (parameterize ([widget:target #f]) (eval (read (open-input-string text))))
         (settle!)
         (test:check 'listed-buffet-call-works-in-eval-outside-key-dispatch
           (list (string:prefix? "(table:move! (widget:descendant '" text) (not (equal? (caddr before) (caddr (selection))))) '(#t #t)))
       (widget:focus! (root) (child (child (table) 'body) 'rows))
       (head:before-frame!)
       (let ([text (string:join (vector->list (head:buffer-lines (head:window-buffer (head:popup)))) "\n")])
         (test:check 'keys-follows-widget-focus
           (and (string:search text "buffet keys" 0 (string-length text))
             (not (string:search text "widget-entry keys" 0 (string-length text)))) #t))
       (keys:hide!) (widget:focus! (root) focus) (settle!))
     (select! a)
     (let ([generation (keymap:generation)])
       (keys:show!) (settle!) (head:before-frame!)
       (let* ([before (state)] [help (head:window-buffer (head:popup))] [old (head:buffer-lines help)]
              [call (binding '("C-k") (app))])
         (test:check 'concrete-kill-binding-is-educational-and-discovery-is-pure
           (list (eq? (keymap:action-procedure call) edit:kill-buffer!)
             (string:prefix? "(edit:kill-buffer! (buffer \"buffet-a\") " (keymap:action-text call))
             (equal? before (state)) (= generation (keymap:generation))) '(#t #t #t #t))
         (select! b) (head:before-frame!)
         (test:check 'keys-follows-selection-without-rebinding
           (list (not (eq? old (head:buffer-lines help))) (car (keymap:call-action-arguments (binding '("C-k") (app)))) )
           (list #t b)))
       (keys:hide!))
     (let ([focus (widget:focused (root))] [selected (selection)] [sort (get (get (collection:summary (query)) 'value) 'sort)])
       (head:set-mouse-position! '(2 . 2)) (keys:show!) (settle!) (head:before-frame!)
       (let* ([b (head:window-buffer (head:popup))] [lines (head:buffer-lines b)]
              [header (cadr (assoc '(click primary ()) (mouse:bindings)))])
         (head:before-frame!)
         (test:check 'mouse-help-first-inspects-heading-without-changing-state
           (list (vector-ref lines 0) (eq? lines (head:buffer-lines b))
             (keymap:call-action-procedure header) (cadr (keymap:call-action-arguments header))
             (caddr (selection)) (get (get (collection:summary (query)) 'value) 'sort) (widget:focused (root)))
           (list "Mouse bindings" #t table:toggle-sort! 'modified (caddr selected) sort focus))
         (head:set-mouse-position! '(2 . 3)) (head:before-frame!)
         (let* ([bindings (mouse:bindings)] [row (cadr (assoc '(click primary ()) bindings))])
           (test:check 'hover-changes-mouse-section-and-includes-wheel
             (list (not (eq? lines (head:buffer-lines b))) (keymap:call-action-procedure row)
               (and (assoc '(wheel up ()) bindings) (assoc '(wheel down ()) bindings) #t)
               (widget:focused (root)))
             (list #t table:choose! #t focus)))
         (head:set-mouse-position! '(1000 . 1000)) (head:before-frame!)
         (test:check 'leaving-shown-target-clears-mouse-section
           (string:prefix? "Mouse" (head:buffer-line b 0)) #f))
       (head:set-mouse-position! #f) (keys:hide!) (settle!))
     (let ([heading (cadr (widget:frame-lines (draw! (root) 120 15)))])
       (press! "b" "u" "f" "f" "e" "t" "-" "b") (settle!)
       (test:check 'typing-from-entry-filters-in-base-without-shifting-columns
         (list (get (get (collection:summary (query)) 'value) 'count) (caddr (selection))
           (equal? heading (cadr (widget:frame-lines (draw! (root) 120 15)))))
         (list 1 (document:reference b) #t)))
     (press! "C-u") (settle!)
     (define before (selection))
     (press! "UP") (settle!)
     (test:check 'arrows-from-filter-reach-table (not (equal? before (selection))) #t)
     (table:sort-by! (table) '((name descending))) (settle!)
     (head:show-buffer! a)
     (buffet:previous!)
     (test:check 'global-cycle-uses-compound-order (eq? (head:current-buffer) b) #t)
     (buffet:open!) (settle!)
     (select! b)
     (define stale (binding '("C-k") (app)))
     (head:buffer-name-set! b "buffet-b-renamed")
     (test:check 'stale-destructive-action-refuses
       (test:raises? (lambda () (keymap:run! stale))) #t)
     (settle!) (select! b) (press! "C-k") (settle!)
     (test:check 'trash-retires-the-head-buffer
       (list (and (store:property (head:buffer-store-id b) 'trashed #f) #t) (memq b (head:buffers))) '(#t #f))
     (let ([text (string:join (widget:frame-lines (draw! (root) 120 15)) "\n")])
       (test:check 'archive-age-and-retention-are-presented
         (and (string:search text " ago" 0 (string-length text)) (string:search text " left" 0 (string-length text)) #t) #t))
     (table:select! (table) (list 'buffer (head:buffer-store-id b))) (settle!)
     (test:check 'archive-kill-is-disabled (keymap:action-reason (binding '("C-k") (app))) "Choose a live buffer")
     (press! "RET")
     (test:check 'archive-restore-preserves-identity
       (list (head:buffer-store-id (head:current-buffer)) (store:property (head:buffer-store-id b) 'trashed #f))
       (list (head:buffer-store-id b) #f))
     (buffet:open!) (settle!)
     (select! (head:buffer-of-store-id (head:buffer-store-id b))) (press! "C-k") (settle!)
     (table:select! (table) (list 'buffer (head:buffer-store-id b))) (settle!)
     (let ([call (binding '("C-x" "D") (app))])
       (test:check 'archive-binding-is-the-canonical-delete (keymap:action-procedure call) edit:delete-trashed!)
       (eval (read (open-input-string (keymap:action-text call)))))
     (test:check 'permanent-archive-delete (store:exists? (head:buffer-store-id b)) #f)
     (settle!)
     (let ([local (head:register-view! "buffet-local" void)])
       (select! local)
       (let ([call (binding '("C-k") (app))])
         (head:buffer-name-set! local "<buffet-local-renamed>")
         (test:check 'local-version-fences-retirement (test:raises? (lambda () (keymap:run! call))) #t))
       (select! local) (press! "C-k")
       (test:check 'canonical-kill-retires-local-buffer (memq local (head:buffers)) #f)
       (settle!))
     (let* ([w (head:current-window)] [picker (head:current-buffer)]
            [other (window:split-right!)] [fork (head:buffer-fact (head:window-buffer other) 'widget-id #f)]
            [fork-table (child (child fork 'app) 'table)])
       (test:check 'split-forks-view-state-and-shares-query
         (list (equal? host fork) (equal? original-table fork-table)
           (equal? original-query (view:source (interaction:snapshot fork-table)))) '(#f #f #t))
       (draw! fork 27 8)
       (select! a)
       (test:await 'fork-selection
         (lambda ()
           (draw! fork 120 15)
           (and (table:target fork-table) #t)))
       (table:select! fork-table (document:reference picker))
       (test:await 'fork-binding
         (lambda () (draw! fork 120 15)
           (let ([action (binding '("C-k") (child fork 'app))])
             (and (not (keymap:action-reason action))
               (eq? (car (keymap:call-action-arguments action)) picker)))))
       (test:check 'split-bindings-use-their-own-selection
         (map (lambda (id) (car (keymap:call-action-arguments (binding '("C-k") id))))
           (list original-app (child fork 'app))) (list a picker))
       (let ([wide (widget:frame-lines (draw! host 300 15))])
         (test:check 'split-width-does-not-truncate-peer-metadata
           (and (string:search (cadr wide) "Modified" 0 300)
             (string:search (cadr wide) "Lines" 0 300)
             (string:search (cadr wide) "File" 0 300) (= (string-length (cadr wide)) 300)) #t))
       (window:focus! other) (head:show-buffer! a)
       (widget:set-active! host #f)
       (test:await 'inactive-table-ready
         (lambda ()
           (draw! host 120 15)
           (let* ([s (get (view:state (interaction:snapshot original-table)) 'selection)]
                  [r (and s (collection:rank original-query (cadr s) (document:reference a)))])
             (and r (eq? (car r) 'ready) (list-ref r 3)))))
       (let* ([frame (draw! host 120 15)] [s (get (view:state (interaction:snapshot original-table)) 'selection)]
              [generation (cadr s)]
              [rank (list-ref (collection:rank original-query generation (document:reference a)) 3)]
              [row (+ 2 rank)]
              [face (vector-ref (widget:frame-styles frame row (list-ref (widget:frame-lines frame) row)) 0)])
         (test:check 'inactive-pane-emphasizes-current-document face 'active)
         (widget:pointer! '(pointer move none ()) 3 row)
         (let* ([frame (draw! host 120 15)] [face (vector-ref (widget:frame-styles frame row (list-ref (widget:frame-lines frame) row)) 0)])
           (test:check 'hover-uses-shared-candidate-style face 'candidate-hover))
         (widget:pointer! '(scroll 0 3 cells) 3 row)
         (test:check 'wheel-never-changes-selection
           (get (view:state (interaction:snapshot original-table)) 'selection) s)
         (let ([result (parameterize ([head:app-event-focus other]) (widget:pointer! '(pointer press primary ()) 3 row))])
           (test:check 'inactive-click-opens-in-focused-window-and-keeps-focus
             (list (cadr result) (eq? other (head:current-window)) (eq? picker (head:window-buffer w)) (eq? a (head:window-buffer other))) '(#f #t #t #t))))
       (window:focus! w) (window:delete-others!) (widget:set-active! host #t) (settle!))
     ;; Two unmounted constructors are independent; explicit query reuse is
     ;; borrowing, so releasing the first view cannot disconnect its sibling.
     (define independent (buffet:create! '()))
     (let ([transient (document:create-source! 'transient)])
       (test:check 'transient-owner-cannot-orphan-a-persistent-filter
         (test:raises? (lambda () (catalogue:create-query! head:ui-actor transient))) #t)
       (model:retire! head:ui-actor transient (get (model:snapshot transient) 'revision)))
     (define borrowed (buffet:create! '() original-query))
     (widget:mount! borrowed 'embedded)
     (draw! borrowed 44 8)
     (test:check 'constructor-sharing-is-explicit
       (list (equal? original-query (view:source (view:snapshot (cadr (assq 'table (view:children (view:snapshot independent)))))))
         (equal? original-query (view:source (interaction:snapshot (child borrowed 'table))))) '(#f #t))
     (test:check 'unconnected-embedded-open-has-no-window-fallback
       (test:raises? (lambda () (buffet:choose! borrowed (selection) (get (state) 'basis)))) #t)
     (widget:unmount! host)
     (entry:insert! (child (child (child borrowed 'table) 'filter) 'entry) "buffet-a")
     (test:await 'borrowed-filter-still-connected
       (lambda () (= (get (get (collection:summary original-query) 'value) 'count) 1)))
     (test:check 'query-owns-filter-after-original-view-closes (store:exists? filter-id) #t)
     (widget:unmount! borrowed)
     (let ([r (model:snapshot original-query)]) (model:retire! head:ui-actor original-query (get r 'revision)))
     (test:await 'query-releases-owned-filter (lambda () (not (store:exists? filter-id))))
     (test:finish! 'buffet)))
