;; Catalogue ownership, capture gaps and archive witnesses share this runner.
(let ()
  (define actor '(head "catalogue"))
  (define other '(head "catalogue-other"))
  (define created '())
  (define demands '())
  (define (field r k) (cdr (assq k r)))
  (define (make name facts)
    (let ([id (store:create! actor name '("text") facts)]) (set! created (cons id created)) id))
  (define (metadata id) (cadar (cadr (store:metadata (list id)))))
  (define (version id) (field (metadata id) 'version))
  (define (act id v action) (let-values ([(status m) (store:archive! actor id v action)]) status))
  (define (packet query)
    (unless (assoc query demands)
      (set! demands (cons (cons query (model:subscribe! (list query) void)) demands)))
    (let* ([s (collection:summary query)] [v (field s 'value)])
      (and (eq? (field v 'status) 'ready)
        (let ([p (collection:range query (field v 'generation) 0 256 '(name flags lines file version))])
          (and (eq? (car p) 'ready) p)))))
  (define (keys query) (let ([p (packet query)]) (and p (map cadr (list-ref p 4)))))
  (define (expect query expected)
    (test:await 'catalogue-current (lambda () (equal? (keys query) expected))))
  (define (retire id) (let ([r (model:snapshot id)]) (when r (model:retire! actor id (field r 'revision)))))
  (define first (make "catalogue/Alpha" '((file . "/home/catalogue/Alpha") (read-only . #t))))
  (define second (make "catalogue/alpha" '()))
  (define trash (make "catalogue/trash" `((trashed 2 ,actor))))
  (define backup (make "catalogue/backup" `((trashed 1 ,actor) (backup "/old/catalogue/file" #f "hash"))))
  (define hidden (make "catalogue/hidden" `((audience ,other))))
  (define internal (make "catalogue/internal" '((internal . #t))))
  ;; Invalid requests do not enter the writer.
  (test:check 'catalogue-metadata-rejects-invalid-ids
    (test:raises? (lambda () (store:metadata '(-1)))) #t)
  (test:check 'catalogue-flags-use-one-portable-marker-order
    (list-sort property:flags<?
      (map property:flags '(((read-only . #t)) ((conflicts . 2)) () ((conflicts . 1) (read-only . #t)))))
    '(() (conflicted) (conflicted read-only) (read-only)))
  (let ([m (metadata first)])
    (test:check 'catalogue-metadata-is-small-and-typed
      (list (field m 'lines) (field m 'flags) (assq 'base m) (assq 'text m) (assq 'history m))
      '(1 (read-only) #f #f #f)))
  ;; Stop the catalogue after its first capture, then overflow its pending ID
  ;; queue. A bulk rescan must include late entries and remove deleted ones.
  (let* ([captured (test:gate)] [release (test:gate)]
         [watch (model:subscribe! #f
                  (lambda (notice)
                    (unless (captured)
                      (when (exists (lambda (id)
                                      (let ([r (model:snapshot id)])
                                        (and r (eq? (field r 'kind) 'buffer-catalogue) (> (field (field r 'value) 'epoch) 0))))
                              (or (cadr notice) '()))
                        (captured #t) (test:await 'release-catalogue release)))))]
         [source (catalogue:create-source! actor "/home" 'transient)])
    (test:await 'catalogue-initial-capture captured)
    (do ([i 0 (+ i 1)]) ((= i 257)) (make (format "unrelated-~a" i) '()))
    (store:rename! actor second "catalogue/Beta")
    (store:delete! actor internal)
    (release #t)
    (model:unsubscribe! watch)
    (let* ([query (collection:create! actor source "catalogue/" '((flags ascending)) 'transient)]
           [filtered (collection:create! actor source "~/catalogue/" '() 'transient)]
           [expected (list second first '(section backup) backup '(section trash) trash)])
      (expect query expected)
      (expect filtered (list first))
      (test:check 'catalogue-shared-inventory-filter-and-archive-sections
        (list (keys query) (keys filtered)
          (list-ref (collection:seek query (field (field (collection:summary query) 'value) 'generation) 2 'forward 0) 3))
        (list expected (list first) 3))
      (let ([v (version trash)])
        (store:rename! actor trash "catalogue/renamed")
        (test:check 'catalogue-rename-fences-restoration (act trash v 'restore) 'stale))
      (let ([v (version trash)])
        (store:rename! actor second "catalogue/unrelated")
        (test:check 'catalogue-unrelated-change-does-not-fence-restore (act trash v 'restore) 'applied)
        (test:check 'catalogue-restore-fences-delete (act trash v 'delete) 'stale))
      (test:check 'catalogue-delete-refuses-live (act trash (version trash) 'delete) 'refused)
      (act trash (version trash) 'trash)
      (let ([v (version trash)])
        (store:edit! actor trash (store:revision trash) (text:make-span 0 0 0 0) '("saved "))
        (test:check 'catalogue-edit-fences-delete (act trash v 'delete) 'stale))
      (test:check 'catalogue-delete-and-missing-id
        (let ([v (version trash)]) (list (act trash v 'delete) (act trash v 'restore))) '(applied unavailable))
      (test:check 'catalogue-audience-fences-archive (act hidden (version hidden) 'trash) 'refused)
      (let ([v (version first)])
        (act first v 'trash)
        (let ([same-name (make "catalogue/Alpha" '())])
          (act first (version first) 'restore)
          (test:check 'catalogue-restore-keeps-id-and-unique-name
            (list (not (equal? (store:buffer-name first) (store:buffer-name same-name)))
              (store:line first 0) (field (metadata first) 'flags)) '(#t "text" (read-only)))))
      (for-each retire (list query filtered source))))
  (for-each (lambda (id) (when (store:exists? id) (store:delete! actor id))) created)
  (for-each (lambda (p) (model:unsubscribe! (cdr p))) demands))
