;; Query only a selected span; never copy the document or its alternatives.
(let ()
  (import (prefix (service change-preview) preview:) (prefix (state model) model:)
          (prefix (state view) view:) (prefix (state connection) connection:))
  (define actor head:ui-actor)
  (define (get r k) (cdr (assq k r)))
  (define document (store:create! actor "change preview" '("base") '((base . "base") (trailing . #f))))
  (define root (view:create! actor #f 'change-preview 1 '() '((revision 1) #f)))
  (define count (length (store:buffer-list)))
  (define query (preview:create! actor document root))
  (define (value) (get (model:snapshot query) 'value))
  (define (ready selection)
    (test:await 'change-preview-ready
      (lambda () (let* ([v (value)] [basis (get v 'basis)] [a (get v 'annotations)])
                   (and basis (equal? (cadar basis) selection) (eq? (get v 'status) 'ready)
                     (pair? a) (= (cadr a) (store:revision document)))))))
  (store:edit! actor document 0 (text:make-span 0 0 0 4) '("mine"))
  (view:arrange! actor (list (list root 0 '() (list (list 'owned query)))) '())
  (connection:bind! actor query (list (list query 'selection #f (list root 'selection))))
  (let ([token (model:subscribe! (list query) void)])
    (ready '(revision 1))
    (check 'change-preview-is-a-bounded-mark-over-borrowed-text
      (list (get (value) 'annotations) (= count (length (store:buffer-list))))
      (list (list document 1 '(((0 0 0 4) match))) #t))
    (store:edit! bot document 1 (text:make-span 0 0 0 0) '("x"))
    (ready '(revision 1))
    (check 'change-preview-follows-source-edits
      (caddr (get (value) 'annotations)) '(((0 1 0 5) match)))
    (store:reload! bot document '("disk") '((base . "disk") (trailing . #f)))
    (let* ([conflict (car (store:conflicts document))] [selection (list 'conflict (car conflict))])
      (view:set-state! actor root #f (list selection #f))
      (ready selection)
      (check 'conflict-preview-uses-its-current-region
        (caddr (get (value) 'annotations)) (list (list (list-ref conflict 3) 'match)))
      (let ([revision (store:revision document)])
        (store:resolve! actor document (car conflict) 'disk 'any)
        (test:await 'settled-preview (lambda () (eq? (get (value) 'status) 'unavailable)))
        (check 'same-text-conflict-settlement-invalidates-preview
          (list (= revision (store:revision document)) (get (value) 'annotations)) '(#t ()))))
    (view:retire! actor root (model:revision root))
    (model:unsubscribe! token)
    (check 'preview-owner-retirement-keeps-only-the-borrowed-document
      (list (model:snapshot query) (store:exists? document)) '(#f #t)))
  (store:delete! actor document))
