(let ()
  (import (prefix (service conflict-review) review:) (prefix (state model) model:))
  (define (get r k) (cdr (assq k r)))
  (define actor head:ui-actor)
  (define (source name)
    (let ([id (store:create! actor name '("base" "tail") '((base . "base\ntail") (trailing . #f)))])
      (store:edit! actor id 0 (text:make-span 0 0 0 4) '("mine"))
      (store:reload! bot id '("disk" "tail") '((base . "disk\ntail") (trailing . #f))) id))
  (define x (source "review one"))
  (define y (source "review two"))
  (define a (review:create! actor (list x y)))
  (define b (review:create! actor (list x)))
  (define (revision id) (model:revision id))
  (define (entry id document)
    (find (lambda (e) (= document (get e 'document))) (get (get (model:snapshot id) 'value) 'records)))
  (define (mine id document) (get (entry id document) 'mine))
  (define (refresh id scope) (review:refresh! actor id (revision id) scope))
  (define (choose id document)
    (review:choose! actor id (revision id) (list (cons document (store:conflicts document))) 'mine))
  (choose a x)
  (check 'conflict-drafts-keep-independent-choices-without-writing
    (list (mine a x) (mine b x) (store:line x 0) (list-ref (review:preview a x) 3))
    '((1) () "disk" #("mine" "tail")))
  (check 'stale-draft-choices-refuse-before-changing-any-group
    (list (test:raises? (lambda () (review:choose! actor a 0 (list (cons y (store:conflicts y))) 'mine))) (mine a y))
    '(#t ()))
  (refresh a (list x))
  (let ([witness (get (entry a x) 'alternatives)])
    (store:edit! bot x (store:revision x) (text:make-span 0 0 0 0) '("prefix" ""))
    (check 'stale-click-and-unrefreshed-settlement-refuse-changed-coordinates
      (list (test:raises? (lambda () (review:choose! actor a (revision a) (list (cons x witness)) 'mine)))
        (cadr (assv x (review:settle! actor a (revision a) (list x)))) (mine a x)) '(#t refused (1))))
  (refresh a (list x))
  (check 'retained-evidence-rebases-mine-without-losing-unrelated-text
    (list (mine a x) (get (entry a x) 'invalidated) (list-ref (review:preview a x) 3))
    '((1) () #("prefix" "mine" "tail")))
  ;; Removed documents cannot settle; bringing one back verifies retained witnesses.
  (choose a x)
  (refresh a '())
  (check 'empty-scope-settles-nothing (review:settle! actor a (revision a) '()) '())
  (refresh a (list x y))
  (choose a y)
  (store:set-property! actor y 'read-only #t)
  (check 'multi-document-settlement-reports-partial-refusal-and-retains-choices
    (let ([results (review:settle! actor a (revision a) (list x y))])
      (list (map cadr results) (mine a x) (mine a y) (store:line x 1) (store:line y 0)))
    '((applied refused) () (1) "mine" "disk"))
  (store:undo! actor x)
  (check 'settlement-is-undoable-with-prior-history-intact
    (let-values ([(lines revision) (store:snapshot x)]) (vector->list lines)) '("prefix" "disk" "tail"))
  (store:set-property! actor y 'read-only #f)
  (store:edit! bot y (store:revision y) (text:make-span 0 0 0 4) '("changed"))
  (refresh a (list y))
  (check 'changed-disk-alternative-invalidates-only-its-mine-choice
    (list (mine a y) (get (entry a y) 'invalidated) (list-ref (review:preview a y) 3))
    '(() (1) #("changed" "tail")))
  (for-each (lambda (id) (review:close! actor id (revision id))) (list a b))
  (check 'closing-review-preserves-borrowed-sources
    (list (model:snapshot a) (model:snapshot b) (store:exists? x) (store:exists? y)) '(#f #f #t #t)))
