(let ()
  (import (prefix (service conflict-review) review:) (prefix (service conflict-source) conflict-source:)
          (prefix (service review-preview) review-preview:) (prefix (state view) view:)
          (prefix (state connection) connection:) (prefix (state collection) collection:) (prefix (state model) model:))
  (define (get r k) (cdr (assq k r)))
  (define actor head:ui-actor)
  (define (source name)
    (let ([id (store:create! actor name '("base" "tail") '((base . "base\ntail") (trailing . #f)))])
      (store:edit! actor id 0 (text:make-span 0 0 0 4) '("mine"))
      (store:reload! bot id '("disk" "tail") '((base . "disk\ntail") (trailing . #f))) id))
  (define x (source "review one"))
  (define y (source "review two"))
  (define a (review:create! actor (list x y)))
  (define b (review:create! actor (list x)))
  (define (revision id) (model:revision id))
  (define (entry id document)
    (find (lambda (e) (= document (get e 'document))) (get (get (model:snapshot id) 'value) 'records)))
  (define (mine id document) (get (entry id document) 'mine))
  (define (refresh id scope) (review:refresh! actor id (revision id) scope))
  (define (choose id document)
    (review:choose! actor id (revision id) (list (cons document (store:conflicts document))) 'mine))
  (choose a x)
  (check 'conflict-drafts-keep-independent-choices-without-writing
    (list (mine a x) (mine b x) (store:line x 0) (list-ref (review:preview a x) 3))
    '((1) () "disk" #("mine" "tail")))
  (check 'stale-draft-choices-refuse-before-changing-any-group
    (list (test:raises? (lambda () (review:choose! actor a 0 (list (cons y (store:conflicts y))) 'mine))) (mine a y))
    '(#t ()))
  (refresh a (list x))
  (let ([witness (get (entry a x) 'alternatives)])
    (store:edit! bot x (store:revision x) (text:make-span 0 0 0 0) '("prefix" ""))
    (check 'stale-click-and-unrefreshed-settlement-refuse-changed-coordinates
      (list (test:raises? (lambda () (review:choose! actor a (revision a) (list (cons x witness)) 'mine)))
        (cadr (assv x (review:settle! actor a (revision a) (list x)))) (mine a x)) '(#t refused (1))))
  (refresh a (list x))
  (check 'retained-evidence-rebases-mine-without-losing-unrelated-text
    (list (mine a x) (get (entry a x) 'invalidated) (list-ref (review:preview a x) 3))
    '((1) () #("prefix" "mine" "tail")))
  ;; Removed documents cannot settle; bringing one back verifies retained witnesses.
  (choose a x)
  (refresh a '())
  (check 'empty-scope-settles-nothing (review:settle! actor a (revision a) '()) '())
  (refresh a (list x y))
  (choose a y)
  (store:set-property! actor y 'read-only #t)
  (check 'multi-document-settlement-reports-partial-refusal-and-retains-choices
    (let ([results (review:settle! actor a (revision a) (list x y))])
      (list (map cadr results) (mine a x) (mine a y) (store:line x 1) (store:line y 0)))
    '((applied refused) () (1) "mine" "disk"))
  (store:undo! actor x)
  (check 'settlement-is-undoable-with-prior-history-intact
    (let-values ([(lines revision) (store:snapshot x)]) (vector->list lines)) '("prefix" "disk" "tail"))
  (store:set-property! actor y 'read-only #f)
  (store:edit! bot y (store:revision y) (text:make-span 0 0 0 4) '("changed"))
  (refresh a (list y))
  (check 'changed-disk-alternative-invalidates-only-its-mine-choice
    (list (mine a y) (get (entry a y) 'invalidated) (list-ref (review:preview a y) 3))
    '(() (1) #("changed" "tail")))
  ;; The same draft can supply bounded row pages; hidden queries do no work.
  (let* ([query (collection:create! actor a "" '() 'persistent)] [token #f])
    (define (page . after)
      (define reply #f)
      (test:await 'conflict-rows
        (lambda ()
          (let ([v (get (collection:summary query) 'value)])
            (when (eq? (get v 'status) 'unavailable) (error 'conflict-rows "unavailable" v))
            (and (eq? (get v 'status) 'ready) (or (null? after) (> (get v 'generation) (car after)))
              (let ([r (collection:range query (get v 'generation) 0 10 '(buffer mine disk choice))])
                (and (eq? (car r) 'ready) (begin (set! reply r) #t))))))) reply)
    (check 'conflict-row-query-is-lazy (get (get (collection:summary query) 'value) 'generation) 0)
    (set! token (model:subscribe! (list query) (lambda (notice) (void))))
    (let* ([first (page)] [selection (list query (cadr first) (cadar (list-ref first 4)))])
      (conflict-source:choose! actor selection (caddr first) 'mine)
      (let ([next (page)])
        (check 'conflict-row-choice-is-exact-and-stale-listings-refuse
          (list (mine a y) (> (cadr next) (cadr first))
            (test:raises? (lambda () (conflict-source:choose! actor selection (caddr first) 'disk)))) '((1) #t #t))
        (store:edit! bot y (store:revision y) (text:make-span 1 4 1 4) '("!"))
        (let ([updated (page (cadr next))])
          (check 'demanded-conflict-rows-follow-source-edits-and-retain-proven-picks (mine a y) '(1))
          (conflict-source:choose-all! actor query (cadr updated) (caddr updated) 'disk))
        (page)
        (model:unsubscribe! token)
        (let ([generation (get (get (collection:summary query) 'value) 'generation)])
          (store:edit! bot y (store:revision y) (text:make-span 1 4 1 4) '("!"))
          (check 'hidden-conflict-query-keeps-no-derived-work
            (get (get (collection:summary query) 'value) 'generation) generation))))
    (let* ([preview (review-preview:create! actor a)] [request (car preview)] [document (cadr preview)]
           [table (view:create! actor query 'table 1 '((columns mine disk)) '((selection . #f) (basis)))])
      (define (ready?) (eq? (get (get (model:snapshot request) 'value) 'status) 'ready))
      (connection:bind! actor request (list (list request 'selection #f (list table 'selection))))
      (let ([hold (model:subscribe! (list request) (lambda (notice) (void)))])
        (test:await 'preview-start ready?)
        (check 'preview-is-read-only-and-retains-connected-query-demand
          (list (store:property document 'read-only) (store:line document 0) (model:demanded? query)) '(#t "changed" #t))
        (let* ([p (page)] [selection (list query (cadr p) (cadar (list-ref p 4)))])
          (view:set-state! actor table #f (list (cons 'selection selection) (cons 'basis (caddr p))))
          (conflict-source:choose! actor selection (caddr p) 'mine)
          (let* ([p (page)] [selection (list query (cadr p) (cadar (list-ref p 4)))])
            (view:set-state! actor table #f (list (cons 'selection selection) (cons 'basis (caddr p)))))
          (test:await 'preview-choice (lambda () (and (ready?) (equal? (store:line document 0) "mine"))))
          (check 'connected-preview-publishes-revisioned-semantic-highlight
            (let ([annotations (get (get (model:snapshot request) 'value) 'annotations)])
              (list (car annotations) (cadr annotations) (caddr annotations)))
            (list document (store:revision document) '(((0 0 0 4) conflict-mine-current)))))
        (model:unsubscribe! hold)
        (check 'hidden-preview-releases-its-connected-query (model:demanded? query) #f))
      (review-preview:close! actor request)
      (check 'closing-preview-deletes-only-owned-output
        (list (store:exists? document) (and (model:snapshot a) #t) (store:exists? y)) '(#f #t #t))
      (view:retire! actor table (model:revision table)))
    (model:retire! actor query (model:revision query)))
  (for-each (lambda (id) (review:close! actor id (revision id))) (list a b))
  (check 'closing-review-preserves-borrowed-sources
    (list (model:snapshot a) (model:snapshot b) (store:exists? x) (store:exists? y)) '(#f #f #t #t)))
