(let ()
  (define (field r k) (cdr (assq k r)))
  (define source (document:create-source! 'transient))
  (define draft (head:new-local-buffer! "catalogue-host draft"))
  (define app (head:register-view! "catalogue-host app" void))
  (define root (view:create! head:ui-actor #f 'row 1 '((name . "catalogue-host widget")) '()))
  (define host (window:show-widget! (head:current-window) root))
  (define demands '())
  (define (query!)
    (let ([q (collection:create! head:ui-actor source "catalogue-host" '() 'transient)])
      (set! demands (cons (model:subscribe! (list q) void) demands)) q))
  (define (rows q)
    (let* ([s (collection:summary q)] [v (field s 'value)])
      (and (eq? (field v 'status) 'ready)
        (let ([p (collection:range q (field v 'generation) 0 20 '(name lines version))])
          (and (eq? (car p) 'ready) (list-ref p 4))))))
  (define (wait q) (test:await 'host-catalogue-ready (lambda () (let ([r (rows q)]) (and r (= (length r) 3))))))
  (define (cells q ref) (caddr (find (lambda (row) (equal? (cadr row) ref)) (rows q))))
  (define (retire id) (let ([r (model:snapshot id)]) (when r (model:retire! head:ui-actor id (field r 'revision)))))
  (head:add-buffer! draft)
  (let* ([q (query!)] [ref (document:reference draft)] [app-ref (document:reference app)])
    (wait q)
    (test:check 'host-catalogue-refers-to-base-view-and-omits-generated-line-counts
      (list (document:reference host) (assq 'lines (cells q app-ref)) (assq 'lines (cells q root))
        (eq? draft (document:resolve! ref)) (eq? host (document:resolve! root))
        (document:resolve! (list 'local '(head "foreign") (caddr ref) (cadddr ref))))
      (list root '(lines absent) '(lines absent) #t #t #f))
    (let ([revision (field (model:snapshot source) 'revision)])
      (head:view-replace! app '("generated" "layout" "lines"))
      (head:bump-buffer-revision! app)
      (interaction:set-state! head:ui-actor root #f '((selection . changed)))
      (interaction:flush!)
      ;; A newly prepared query is a worker barrier after these notifications.
      (let ([probe (query!)])
        (wait probe)
        (test:check 'host-catalogue-ignores-generated-text-and-widget-selection
          (field (model:snapshot source) 'revision) revision)
        (retire probe)))
    (head:buffer-lines-set! draft '#("one" "two"))
    (head:buffer-name-set! draft "catalogue-host renamed")
    (test:await 'host-catalogue-text-and-rename
      (lambda () (and (rows q) (member '(lines ready 2) (cells q ref))
                   (member '(name ready "<catalogue-host renamed>") (cells q ref)))))
    (test:check 'host-catalogue-rename-keeps-reference (document:reference draft) ref)
    (let ([version (caddr (assq 'version (cells q ref)))])
      (head:buffer-lines-set! draft '#("new" "two"))
      (test:await 'host-catalogue-fences-same-size-text-change
        (lambda () (and (rows q) (> (caddr (assq 'version (cells q ref))) version)))))
    (head:forget-buffer! draft)
    (test:check 'host-catalogue-retired-local-token-refuses (document:resolve! ref) #f)
    (test:await 'host-catalogue-removes-forgotten-buffer (lambda () (let ([r (rows q)]) (and r (= (length r) 2)))))
    (for-each retire (list q source)))
  (head:forget-buffer! app)
  (head:forget-buffer! host)
  (retire root)
  (for-each model:unsubscribe! demands))
