;; Two widths share text and the existing renderer, but never interaction.
(let* ([actor head:ui-actor] [ambient (head:current-buffer)]
       [source (store:create! actor "nested editor" '("abcdefghijklmno" "a界éz" "" "last") '((mode . "editor-test")))]
       [a (create-view! actor source '())] [b (create-view! actor source '())]
       [root (view:create! actor #f 'row 1 '() '())] [calls 0])
  (define (state id) (view:state (interaction:snapshot id)))
  (define (show! width)
    (let ([f (widget:prepare! root width 4)]) (widget:present! (list (list f 0 0))) f))
  (define (body f n) (list-ref (widget:frame-children f) n))
  (edit:init!)
  (mode:register! "editor-test" '() '() #f #f
    (lambda (source row line) (set! calls (+ calls 1)) (make-vector (string-length line) 'keyword)))
  (view:arrange! actor (list (list root 0 (list (list 'narrow a '(grow 1)) (list 'wide b '(grow 2))) '())) '())
  (widget:mount! root 'nested-editor)
  (let* ([frame (show! 27)] [narrow (body frame 0)] [wide (body frame 1)] [before calls])
    (check 'editor-nests-at-independent-widths
      (list (map glyph:cells (map car (map widget:frame-lines (list narrow wide))))
        (substring (cadr (widget:frame-lines narrow)) 0 6)
        (eq? ambient (head:current-buffer)) (not (head:buffer-of-store-id source)))
      '((10 17) "klmno " #t #t))
    (show! 27)
    (check 'editor-warm-frame-does-not-repeat-mode-analysis calls before))
  (select! a '(0 . 13) '(0 . 13))
  (move! a 'up) (move! a 'down)
  (check 'editor-display-motion-keeps-column-and-independent-selection
    (list (car (state a)) (car (state b))) '((0 . 13) (0 . 0)))
  (let ([before (state b)])
    (delete! b 'backward) (insert! b "")
    (check 'editor-empty-edit-and-boundary-delete-are-inert (state b) before))
  (let ([before (state a)])
    (show! 12)
    (check 'editor-resize-does-not-write-cell-geometry-to-view (state a) before))
  (show! 27)
  (select! a '(1 . 3) '(1 . 3))
  (move! a 'right)
  (check 'editor-grapheme-selection-and-movement (car (state a)) '(1 . 4))
  (delete! a 'backward)
  (check 'editor-deletes-whole-cluster (store:line source 1) "a界z")
  (undo! a)
  (select! a '(2 . 0) '(2 . 0))
  (insert! a "A") (insert! a "B")
  (undo! a)
  (check 'editor-typing-is-one-undo-action (store:line source 2) "")
  (redo! a)
  (check 'editor-redo-preserves-multiline-history (list (store:line source 1) (store:line source 2)) '("a界éz" "AB"))
  (select! a '(2 . 2) '(2 . 2)) (insert! a "C")
  (widget:focus! root b) (widget:focus! root a) (insert! a "D")
  (undo! a)
  (check 'editor-focus-round-trip-ends-the-typing-group (store:line source 2) "ABC")
  (undo! a)
  (insert! a "E") (widget:set-active! root #f) (widget:pump!) (widget:set-active! root #t) (insert! a "F")
  (undo! a)
  (check 'editor-inactive-host-ends-the-typing-group (store:line source 2) "ABE")
  (undo! a)
  (select! b '(3 . 4) '(3 . 0))
  (insert! b "new\nline\n")
  (check 'editor-multiline-paste-preserves-trailing-line
    (list (store:line source 3) (store:line source 4) (store:line source 5) (car (state b))) '("new" "line" "" (5 . 0)))
  (store:set-property! actor source 'read-only #t)
  (check 'editor-read-only-refuses-text-but-allows-navigation
    (list (refused? (lambda () (insert! a "lost"))) (begin (move! a 'start) (car (state a)))) '(#t (0 . 0)))
  (store:set-property! actor source 'read-only #f)
  (select! a '(0 . 5) '(0 . 2))
  (let-values ([(lines revision) (store:snapshot source)])
    (store:edit! '(agent "editor") source revision (text:make-span 0 3 0 4) '("foreign")))
  (text-source:open! actor source)
  (check 'editor-overlapping-selection-refuses-without-loss
    (list (refused? (lambda () (insert! a "lost"))) (store:line source 0)) '(#t "abcforeignefghijklmno"))
  (select! a '(0 . 0) '(0 . 0))
  (let ([once? #f] [token #f])
    (set! token (store:subscribe! source (lambda (event)
                                           (when (and (not once?) (eq? (car event) 'edit))
                                             (set! once? #t) (select! a '(1 . 0) '(1 . 0))))))
    (insert! a "!") (store:unsubscribe! token)
    (check 'editor-commit-preserves-a-newer-callback-selection (car (state a)) '(1 . 0)))
  (show! 27)
  (widget:pointer! '(pointer press primary ()) 1 1)
  (widget:pointer! '(pointer release primary ()) 1 1)
  (check 'editor-mouse-selects-source-through-shown-wrap (car (state a)) '(0 . 11))
  (show! 27)
  (let ([before (list-head (state a) 2)])
    (widget:set-active! root #f)
    (widget:pointer! '(scroll 0 3 lines) 1 1)
    (let ([f (show! 27)])
      (check 'editor-inactive-wheel-scrolls-without-moving-selection-or-focus
        (list (list-head (state a) 2) (widget:focused root) (caddr (state a))
          (substring (car (widget:frame-lines (body f 0))) 0 2))
        (list before #f '(1 . 0) "a界")))
    (widget:set-active! root #t)
    (move! a 'start) (set-mark! a #t) (move! a 'right)
    (check 'editor-mark-extends-and-cancel-collapses
      (list (list-head (state a) 2) (begin (set-mark! a #f) (state a)))
      '(((0 . 1) (0 . 0)) ((0 . 1) (0 . 1) (0 . 0) #f))))
  (store:reset! '(base test) source '("replacement"))
  (text-source:forget! source) (text-source:open! actor source)
  (check 'editor-unknown-selection-history-refuses-until-explicit-selection
    (list (widget:caret (show! 27)) (refused? (lambda () (insert! a "lost")))
      (begin (select! a '(0 . 3) '(0 . 3)) (insert! a "X") (store:line source 0)))
    '(#f #t "repXlacement"))
  (let ([fired? #f] [token #f])
    (set! token (store:subscribe! source (lambda (event)
                                           (when (and (not fired?) (eq? (car event) 'edit))
                                             (set! fired? #t) (store:reset! '(base test) source '("external reset"))))))
    (check 'editor-lost-postcommit-history-keeps-text-without-inventing-a-caret
      (list (refused? (lambda () (insert! a "accepted"))) (store:line source 0)) '(#f "external reset"))
    (store:unsubscribe! token))
  (widget:prepare! root 0 0)
  (store:delete! '(base test) source)
  (text-source:forget! source)
  (check 'editor-retired-source-leaves-a-serviceable-placeholder
    (begin (widget:pump!) (not (refused? (lambda () (show! 27))))) #t)
  (widget:unmount! root) (widget:invalidate!))
