#!/usr/bin/env scheme-script

;; Command intent, adopted text, and all head anchors share one revision,
;; including reentrant notifications and callbacks computing a proposal.

(import (chezscheme))
(include "tests/roots.ss")
(test-roots! 'base)

(test-evaluate!
  '(begin
     (import (prefix (test) test:) (prefix (head head) head:) (prefix (head widget) widget:)
       (prefix (apps search) search:) (prefix (service search-request) search-request:)
       (prefix (state model) model:) (prefix (state view) view:) (prefix (state store) store:)
       (prefix (foundation text) text:) (prefix (head mode) mode:) (prefix (core kernel) kernel:))
     (define bot '(agent position-test))
     (define check test:check)
     (include "tests/search-request.sps")
     (include "tests/editor-fixture.sps")
     (store:log-retention 256)
     (define (foreign! b span replacement)
       (let ([id b]) (store:edit! bot id (store:revision id) span replacement)))
     (define (bmark b) (cadr (state-of b)))
     (define (after-own! b thunk)
       (store:subscribe!
         b
         (lambda (event)
           (when (and (eq? (car event) 'edit) (equal? (list-ref event 3) head:ui-actor)) (thunk)))))
     (define b (fresh "position-before" '("abcdef" "tail")))
     (goto! '(0 . 2))
     (foreign! b (text:make-span 0 0 0 0) '("pre" "Q"))
     (edit:insert! editing "X")
     (check 'command-follows-its-rebased-insertion (point) '(1 . 4))
     (check 'both-texts-survive (text-of b) '("pre" "QabXcdef" "tail"))
     (refresh!)
     (check 'queued-events-do-not-shift-again (point) '(1 . 4))
     (define boundary (fresh "position-boundary" '("abcdef")))
     (goto! '(0 . 2))
     (foreign! boundary (text:make-span 0 2 0 4) '("R"))
     (edit:insert! editing "X")
     (check 'insertion-before-foreign-replacement (text-of boundary) '("abXRef"))
     (check 'point-stays-after-own-character (point) '(0 . 3))
     (refresh!)
     (check 'boundary-point-stays-stable (point) '(0 . 3))
     (define reentrant (fresh "position-reentrant" '("abcdef")))
     (goto! '(0 . 2))
     (define token
       (after-own! reentrant (lambda () (foreign! reentrant (text:make-span 0 0 0 0) '("G")) (refresh!))))
     (edit:insert! editing "X")
     (store:unsubscribe! token)
     (check 'reentrant-adoption-keeps-current-text (text-of reentrant) '("GabXcdef"))
     (check 'reentrant-adoption-places-once (point) '(0 . 4))
     (refresh!)
     (check 'reentrant-queued-events-do-not-repeat (point) '(0 . 4))
     (define retained (fresh "position-retention-boundary" '("abcdef")))
     (goto! '(0 . 2))
     (do ([i 0 (+ i 1)]) ((= i 256)) (foreign! retained (text:make-span 0 0 0 0) '("q")))
     (edit:insert! editing "X")
     (check 'acceptance-retains-the-whole-chain (point) '(0 . 259))
     (check
       'acceptance-at-retention-boundary-keeps-text
       (substring (car (text-of retained)) 256 263)
       "abXcdef")
     (refresh!)
     (check 'retention-boundary-events-do-not-shift-again (point) '(0 . 259))
     (define reset (fresh "position-reset-after-commit" '("abcdef")))
     (goto! '(0 . 2))
     (set! token (after-own! reset (lambda () (store:reset! bot reset '("other")))))
     (edit:insert! editing "X")
     (store:unsubscribe! token)
     (check 'post-commit-reset-keeps-latest-text (text-of reset) '("other"))
     (check 'post-commit-reset-carries-the-cursor-not-the-old-new-end (point) '(0 . 5))
     (define truncated (fresh "position-truncated-after-commit" '("abcdef")))
     (goto! '(0 . 2))
     (set! token
       (after-own!
         truncated
         (lambda () (do ([i 0 (+ i 1)]) ((= i 257)) (foreign! truncated (text:make-span 0 0 0 0) '("q"))))))
     (edit:insert! editing "X")
     (store:unsubscribe! token)
     (check 'post-commit-truncation-clamps-without-partial-replay (point) '(0 . 2))
     (check
       'post-commit-truncation-keeps-all-text
       (substring (car (text-of truncated)) 257 264)
       "abXcdef")
     (define structural (fresh "position-structural" '("abcdef")))
     (goto! '(0 . 2))
     (foreign! structural (text:make-span 0 0 0 0) '("Q"))
     (editor:insert-at! editing "\n" #t)
     (check 'open-line-keeps-before-inserted-break (point) '(0 . 3))
     (check 'open-line-splits-the-rebased-position (text-of structural) '("Qab" "cdef"))
     (goto! '(1 . 0))
     (foreign! structural (text:make-span 0 0 0 0) '("R"))
     (edit:delete! editing 'backward)
     (check 'backspace-follows-rebased-join (point) '(0 . 4))
     (check 'backspace-preserves-foreign-prefix (text-of structural) '("RQabcdef"))
     (foreign! structural (text:make-span 0 0 0 0) '("S"))
     (edit:replace-region-text! editing '(0 . 2) '(0 . 4) "x\ny")
     (check 'replacement-follows-rebased-end (point) '(1 . 1))
     (check 'explicit-range-addresses-current-mirrored-text (text-of structural) '("SRx" "ybcdef"))
     (mode:register! "position-format" '() '() (lambda (line) #f))
     (define formatted (fresh "position-format-source" '("abc" "tail")))
     (mode:choose! "position-format" formatted)
     (goto! '(0 . 2))
     (mode:register-formatter!
       "position-format"
       (lambda (b from to)
         (foreign! formatted (text:make-span 0 0 0 0) '("Q"))
         (refresh!)
         '("ABC" "tail")))
     (set! token
       (after-own! formatted (lambda () (foreign! formatted (text:make-span 0 0 0 0) '("R")) (refresh!))))
     (edit:format-buffer! editing)
     (store:unsubscribe! token)
     (check 'format-retains-both-foreign-edits (text-of formatted) '("RQABC" "tail"))
     (check 'format-projects-its-preserved-point (point) '(0 . 4))
     (edit:undo! editing)
     (check 'format-undo-keeps-both-foreign-edits (text-of formatted) '("RQabc" "tail"))
     (define conflict (fresh "position-format-conflict" '("abc")))
     (mode:choose! "position-format" conflict)
     (mode:register-formatter!
       "position-format"
       (lambda (b from to) (foreign! conflict (text:make-span 0 1 0 2) '("R")) (refresh!) '("ABC")))
     (check
       'format-refuses-even-after-head-adoption
       (refused? (lambda () (edit:format-buffer! editing)))
       #t)
     (check 'format-cannot-overwrite-adopted-foreign-text (text-of conflict) '("aRc"))
     (check
       'format-refusal-records-no-head-action
       (filter (lambda (group) (equal? (car group) head:ui-actor)) (store:undo-labels conflict))
       '())
     (define indented (fresh "position-indent-source" '("  abc" "tail")))
     (mode:choose! "position-format" indented)
     (goto! '(1 . 2))
     (edit:set-mark! editing #t)
     (goto! '(0 . 3))
     (mode:register-indenter!
       "position-format"
       (lambda (b from to) (foreign! indented (text:make-span 0 0 0 0) '("pre" "")) (refresh!) '(6 #f)))
     (edit:indent-buffer! editing)
     (check 'indent-keeps-source-row-identity (text-of indented) '("pre" "      abc" "tail"))
     (check 'indent-projects-content-point (point) '(1 . 7))
     (check 'indent-projects-selection-endpoint (bmark indented) '(2 . 2))
     (define replaced (fresh "position-replace" '("aba" "tail")))
     (goto! '(0 . 1))
     (foreign! replaced (text:make-span 0 0 0 0) '("Q"))
     (search:replace! editing "a" "ZZ")
     (check 'replace-preserves-unseen-prefix (text-of replaced) '("QZZbZZ" "tZZil"))
     (check 'replace-projects-preserved-point (point) '(0 . 3))
     (for-each
       (lambda (backwards?)
         (let* ([b (fresh "position-selection" '("abcdef"))] [id b])
           (goto! (if backwards? '(0 . 6) '(0 . 2)))
           (edit:set-mark! editing #t)
           (goto! (if backwards? '(0 . 2) '(0 . 6)))
           (foreign! b (text:make-span 0 0 0 0) '("Q"))
           (refresh!)
           (submit! b (text:make-span 0 0 0 0) '("X"))
           (refresh!)
           (check
             'selection-retains-orientation-after-both-authors
             (list (point) (mark))
             (if backwards? '((0 . 4) (0 . 8)) '((0 . 8) (0 . 4))))
           (let ([caret (point)] [anchor (mark)])
             (edit:copy-region! editing)
             (check 'selection-keeps-the-original-text (edit:copy-text) "cdef")
             (edit:select! editing caret anchor))
           (foreign! b (text:make-span 0 0 0 2) '(""))
           (refresh!)
           (check
             'selection-follows-prefix-deletion
             (list (point) (mark))
             (if backwards? '((0 . 2) (0 . 6)) '((0 . 6) (0 . 2))))
           (foreign! b (text:make-span 0 3 0 5) '(""))
           (refresh!)
           (edit:copy-region! editing)
           (check 'selection-keeps-the-surviving-text (edit:copy-text) "cf")))
       '(#f #t))
     (test:finish! 'edit-position)))
