#!/usr/bin/env scheme-script

;; Shared commands either commit their declared edit or stop without
;; overwriting other actors, forking a cache, or recording a phantom action.

(import (chezscheme))

(include "tests/roots.ss")
(test-roots! 'base)

(test-evaluate!
  '(begin
     (import (prefix (test) test:) (prefix (head head) head:) (prefix (head widget) widget:)
       (prefix (state store) store:) (prefix (foundation text) text:) (prefix (head mode) mode:)
       (prefix (core kernel) kernel:))
     (define bot '(agent conflict-test))
     (define check test:check)
     (include "tests/editor-fixture.sps")
     (store:log-retention 256)
     (define (store-text id) (let-values ([(lines revision) (store:snapshot id)]) (vector->list lines)))
     (define (foreign! b span replacement)
       (let ([id b]) (store:edit! bot id (store:revision id) span replacement)))
     (define (failed? thunk) (guard (ex [else #t]) (thunk) #f))
     (define disjoint (fresh "edit-disjoint" '("abcdef")))
     (define disjoint-id disjoint)
     (goto! '(0 . 2))
     (foreign! disjoint (text:make-span 0 6 0 6) '("Z"))
     (edit:insert! editing "X")
     (check 'same-line-disjoint-edits-compose (text-of disjoint) '("abXcdefZ"))
     (check
       'insertion-retains-its-exact-span
       (list-head (cddar (store:history disjoint-id 1)) 2)
       '((0 . 2) (0 . 2)))
     (edit:undo! editing)
     (check 'undo-preserves-the-same-line-foreign-edit (text-of disjoint) '("abcdefZ"))
     (define overlap (fresh "edit-overlap" '("abcdef" "tail")))
     (define overlap-id overlap)
     (goto! '(1 . 4))
     (edit:insert! editing "own")
     (edit:undo! editing)
     (goto! '(0 . 2))
     (edit:set-mark! editing #t)
     (edit:copy-text! "saved kill")
     (define (head-groups b)
       (filter (lambda (group) (equal? (car group) head:ui-actor)) (store:undo-labels b)))
     (define old-groups (head-groups overlap))
     (foreign! overlap (text:make-span 0 1 0 5) '("RIV"))
     (define foreign-revision (store:revision overlap-id))
     (check 'overlap-refuses-the-command (refused? (lambda () (edit:insert! editing "X"))) #t)
     (check 'refusal-preserves-foreign-text (store-text overlap-id) '("aRIVf" "tail"))
     (check 'refusal-makes-no-transaction (store:revision overlap-id) foreign-revision)
     (check 'refusal-refreshes-the-cache (text-of overlap) (store-text overlap-id))
     (check 'refusal-keeps-the-heads-undo-groups (equal? (head-groups overlap) old-groups) #t)
     (check 'refusal-keeps-selection-active (cadddr (state-of overlap)) #t)
     (check 'refusal-keeps-copy-buffer (edit:copy-text) "saved kill")
     (check 'refusal-rebases-point-only-through-the-foreign-edit (point) '(0 . 4))
     (edit:redo! editing)
     (check 'redo-still-works-after-refusal (text-of overlap) '("aRIVf" "tailown"))
     (define grouped (fresh "edit-refused-group" '("abcdef")))
     (goto! '(0 . 2))
     (foreign! grouped (text:make-span 0 1 0 5) '("R"))
     (edit:call-as-one-edit!
       "accepted part"
       (lambda ()
         (check 'group-can-catch-refusal (refused? (lambda () (edit:insert! editing "lost"))) #t)
         (goto! '(0 . 0))
         (edit:insert! editing "kept")))
     (check 'group-records-only-accepted-work (map cadr (head-groups grouped)) '("accepted part"))
     (edit:undo! editing)
     (check 'group-undo-keeps-foreign-result (text-of grouped) '("aRf"))
     (let ([b (fresh "edit-after-group-undo" '("base"))])
       (edit:call-as-one-edit!
         "group with undo"
         (lambda () (edit:insert! editing "A") (edit:undo! editing) (edit:insert! editing "B")))
       (edit:undo! editing)
       (check 'post-undo-group-retains-undo (text-of b) '("base"))
       (edit:redo! editing)
       (check 'post-undo-group-retains-new-redo (text-of b) '("Bbase")))
     (define reset (fresh "edit-reset" '("abcdef")))
     (define reset-id reset)
     (goto! '(0 . 2))
     (store:reset! bot reset-id '("remote baseline"))
     (check 'reset-refuses-old-intent (refused? (lambda () (edit:insert! editing "X"))) #t)
     (check 'reset-refusal-keeps-baseline (store-text reset-id) '("remote baseline"))
     (check 'reset-refusal-records-no-head-action (head-groups reset) '())
     (do ([i 0 (+ i 1)]) ((= i 257)) (foreign! reset (text:make-span 0 0 0 0) '("x")))
     (define truncated-revision (store:revision reset-id))
     (check 'truncation-refuses-old-intent (refused? (lambda () (edit:insert! editing "X"))) #t)
     (check 'truncation-refusal-keeps-revision (store:revision reset-id) truncated-revision)
     (define failed (fresh "edit-store-failure" '("abcdef")))
     (define failed-id failed)
     (define before-failure (lines-of failed))
     (define before-failure-revision (store:revision failed-id))
     (check
       'store-error-propagates
       (failed?
         (lambda ()
           (submit! failed (text:make-span 0 2 0 2) '("LOST") '(bad-context "invalid" (undo (42 . bad))))))
       #t)
     (check 'store-error-keeps-cache (eq? before-failure (lines-of failed)) #t)
     (check 'store-error-keeps-revision (store:revision failed-id) before-failure-revision)
     (foreign! failed (text:make-span 0 0 0 0) '("remote "))
     (refresh!)
     (check 'frame-cannot-reset-after-failure (store-text failed-id) '("remote abcdef"))
     (check 'cache-recovers-by-reading (text-of failed) '("remote abcdef"))
     (goto! '(0 . 0))
     (edit:insert! editing "ok ")
     (check 'next-valid-edit-uses-store (store-text failed-id) '("ok remote abcdef"))
     (define deleted (fresh "edit-deleted-during-delivery" '("before")))
     (define deleted-id deleted)
     (define deleted-mirror (text-source:lookup deleted))
     (define deleted-before (lines-of deleted))
     (define delete-token
       (store:subscribe!
         deleted-id
         (lambda (event) (when (eq? (car event) 'edit) (store:delete! bot deleted-id)))))
     (check 'post-commit-adoption-error-propagates (failed? (lambda () (edit:insert! editing "new"))) #t)
     (check
       'post-commit-error-does-not-install-a-local-proposal
       (eq? deleted-before (text-source:lines deleted-mirror))
       #t)
     (refresh!)
     (check 'deleted-buffer-is-not-resurrected (store:exists? deleted-id) #f)
     (store:unsubscribe! delete-token)
     (define structural (fresh "edit-structural" '("abc" "tail")))
     (define structural-id structural)
     (define observations '())
     (define structural-token
       (store:subscribe!
         structural-id
         (lambda (event)
           (when (eq? (car event) 'edit) (set! observations (cons (store-text structural-id) observations))))))
     (goto! '(0 . 1))
     (editor:insert-at! editing "\n" #f)
     (check 'newline-has-one-complete-observation observations '(("a" "bc" "tail")))
     (set! observations '())
     (edit:delete! editing 'backward)
     (check 'backspace-joins-in-one-transaction observations '(("abc" "tail")))
     (set! observations '())
     (goto! '(0 . 3))
     (edit:delete! editing 'forward)
     (check 'delete-newline-has-one-observation observations '(("abctail")))
     (set! observations '())
     (edit:replace-region-text! editing '(0 . 1) '(0 . 5) "Q\nR")
     (check 'replacement-has-one-complete-observation observations '(("aQ" "Ril")))
     (set! observations '())
     (edit:copy-text! "x\ny\n")
     (edit:yank! editing)
     (check 'multiline-yank-including-final-break-is-atomic observations '(("aQ" "Rx" "y" "il")))
     (store:unsubscribe! structural-token)
     (define killed (fresh "edit-kill-refusal" '("abcdef" "tail")))
     (goto! '(0 . 2))
     (edit:copy-text! "keep")
     (foreign! killed (text:make-span 0 1 0 5) '("R"))
     (check 'kill-overlap-refuses (refused? (lambda () (edit:kill-line! editing))) #t)
     (check 'refused-kill-keeps-copy-buffer (edit:copy-text) "keep")
     (check 'refused-kill-records-no-head-action (head-groups killed) '())
     (goto! '(0 . 3))
     (store:set-property! head:ui-actor killed 'read-only #t)
     (check
       'read-only-newline-kill-refuses
       (refused? (lambda () (edit:kill-line! editing)))
       #t)
     (check 'read-only-newline-kill-keeps-copy-buffer (edit:copy-text) "keep")
     (define indented (fresh "edit-indent-refusal" '("  abc")))
     (mode:register! "conflict-indent" '() '() (lambda (line) #f))
     (mode:choose! "conflict-indent" indented)
     (goto! '(0 . 2))
     (mode:register-indenter!
       "conflict-indent"
       (lambda (b from to) (foreign! indented (text:make-span 0 0 0 4) '("R")) '(6)))
     (check 'indent-overlap-refuses (refused? (lambda () (edit:indent-buffer! editing))) #t)
     (check 'refused-indent-keeps-foreign-text (text-of indented) '("Rc"))
     (check 'refused-indent-only-follows-foreign-delta (point) '(0 . 1))
     (check 'refused-indent-records-no-head-action (head-groups indented) '())
     (test:finish! 'edit-conflict)))
