;; Two widths share text and the existing renderer, but never interaction.
(let* ([actor head:ui-actor] [ambient (head:current-buffer)]
       [source (store:create! actor "nested editor" '("abcdefghijklmno" "a界éz" "" "last") '((mode . "editor-test")))]
       [a (create-view! actor source '())] [b (create-view! actor source '((wrap . #f)))]
       [root (view:create! actor #f 'row 1 '() '())] [calls 0])
  (define (state id) (view:state (interaction:snapshot id)))
  (define (show! width)
    (let ([f (widget:prepare! root width 4)]) (widget:present! (list (list f 0 0))) f))
  (define (body f n) (list-ref (widget:frame-children f) n))
  (define (face f x y) (vector-ref (widget:frame-styles f y (list-ref (widget:frame-lines f) y)) x))
  (define (text) (let-values ([(lines revision) (store:snapshot source)]) lines))
  (define (key token) (dispatch:input! root (list 'key token)))
  (edit:init!)
  (mode:register! "editor-test" '() '() #f #f
    (lambda (source row line) (set! calls (+ calls 1)) (make-vector (string-length line) 'keyword)))
  (view:arrange! actor (list (list root 0 (list (list 'narrow a '(grow 1)) (list 'wide b '(grow 2))) '())) '())
  (widget:mount! root 'nested-editor)
  (let* ([frame (show! 27)] [narrow (body frame 0)] [wide (body frame 1)] [before calls])
    (check 'editor-nests-at-independent-widths
      (list (map glyph:cells (map car (map widget:frame-lines (list narrow wide))))
        (substring (cadr (widget:frame-lines narrow)) 0 6)
        (eq? ambient (head:current-buffer)) (not (head:buffer-of-store-id source)))
      '((10 17) "klmno " #t #t))
    (show! 27)
    (check 'editor-warm-frame-does-not-repeat-mode-analysis calls before))
  (check 'editor-wrap-precedence-is-view-source-head
    (map (lambda (settings)
           (parameterize ([paint:wrap-lines (car settings)])
             (store:set-property! actor source 'wrap (cadr settings))
             (widget:pump!)
             (select! a '(0 . 0) '(0 . 0)) (select! b '(0 . 0) '(0 . 0))
             (move! a 'down) (move! b 'down)
             (list (car (state a)) (car (state b)))))
      '((#f default) (#f #t) (#t #f) (#t default)))
    '(((1 . 0) (1 . 0)) ((0 . 10) (1 . 0)) ((1 . 0) (1 . 0)) ((0 . 10) (1 . 0))))
  (check 'editor-reveal-uses-the-shared-scroll-margin
    (map (lambda (margin)
           (parameterize ([paint:scroll-margin margin])
             (widget:pump!) (select! a '(0 . 0) '(0 . 0)) (select! a '(2 . 0) '(2 . 0))
             (caddr (state a)))) '(0 1))
    '((0 . 0) (0 . 10)))
  (widget:pump!) (select! b '(0 . 0) '(0 . 0))
  (select! a '(0 . 13) '(0 . 13))
  (move! a 'up) (move! a 'down)
  (check 'editor-display-motion-keeps-column-and-independent-selection
    (list (car (state a)) (car (state b))) '((0 . 13) (0 . 0)))
  (let ([before (state b)])
    (delete! b 'backward) (insert! b "")
    (check 'editor-empty-edit-and-boundary-delete-are-inert (state b) before))
  (let ([before (state a)])
    (show! 12)
    (check 'editor-resize-does-not-write-cell-geometry-to-view (state a) before))
  (show! 27)
  (select! a '(1 . 3) '(1 . 3))
  (move! a 'right)
  (check 'editor-grapheme-selection-and-movement (car (state a)) '(1 . 4))
  (delete! a 'backward)
  (check 'editor-deletes-whole-cluster (store:line source 1) "a界z")
  (undo! a)
  (select! a '(2 . 0) '(2 . 0))
  (insert! a "A") (insert! a "B")
  (undo! a)
  (check 'editor-typing-is-one-undo-action (store:line source 2) "")
  (redo! a)
  (check 'editor-redo-preserves-multiline-history (list (store:line source 1) (store:line source 2)) '("a界éz" "AB"))
  (select! a '(2 . 2) '(2 . 2)) (insert! a "C")
  (widget:focus! root b) (widget:focus! root a) (insert! a "D")
  (undo! a)
  (check 'editor-focus-round-trip-ends-the-typing-group (store:line source 2) "ABC")
  (undo! a)
  (insert! a "E") (widget:set-active! root #f) (widget:pump!) (widget:set-active! root #t) (insert! a "F")
  (undo! a)
  (check 'editor-inactive-host-ends-the-typing-group (store:line source 2) "ABE")
  (undo! a)
  (select! b '(3 . 4) '(3 . 0))
  (insert! b "new\nline\n")
  (check 'editor-multiline-paste-preserves-trailing-line
    (list (store:line source 3) (store:line source 4) (store:line source 5) (car (state b))) '("new" "line" "" (5 . 0)))
  (store:set-property! actor source 'read-only #t)
  (check 'editor-read-only-refuses-text-but-allows-navigation
    (list (refused? (lambda () (insert! a "lost"))) (begin (move! a 'start) (car (state a)))) '(#t (0 . 0)))
  (store:set-property! actor source 'read-only #f)
  (select! a '(0 . 5) '(0 . 2))
  (let-values ([(lines revision) (store:snapshot source)])
    (store:edit! '(agent "editor") source revision (text:make-span 0 3 0 4) '("foreign")))
  (text-source:open! actor source)
  (check 'editor-overlapping-selection-refuses-without-loss
    (list (refused? (lambda () (insert! a "lost"))) (store:line source 0)) '(#t "abcforeignefghijklmno"))
  (select! a '(0 . 0) '(0 . 0))
  (let ([once? #f] [token #f])
    (set! token (store:subscribe! source (lambda (event)
                                           (when (and (not once?) (eq? (car event) 'edit))
                                             (set! once? #t) (select! a '(1 . 0) '(1 . 0))))))
    (insert! a "!") (store:unsubscribe! token)
    (check 'editor-commit-preserves-a-newer-callback-selection (car (state a)) '(1 . 0)))
  (select! a '(0 . 0) '(0 . 0))
  (show! 27)
  (widget:pointer! '(pointer press primary ()) 1 1)
  (widget:pointer! '(pointer release primary ()) 1 1)
  (check 'editor-mouse-selects-source-through-shown-wrap (car (state a)) '(0 . 11))
  (show! 27)
  (let ([before (list-head (state a) 2)])
    (widget:set-active! root #f)
    (widget:pointer! '(scroll 0 3 lines) 1 1)
    (let ([f (show! 27)])
      (check 'editor-inactive-wheel-scrolls-without-moving-selection-or-focus
        (list (list-head (state a) 2) (widget:focused root) (caddr (state a))
          (substring (car (widget:frame-lines (body f 0))) 0 2))
        (list before #f '(1 . 0) "a界")))
    (widget:set-active! root #t)
    (move! a 'start) (set-mark! a #t) (move! a 'right)
    (check 'editor-mark-extends-and-cancel-collapses
      (list (list-head (state a) 2) (begin (set-mark! a #f) (state a)))
      '(((0 . 1) (0 . 0)) ((0 . 1) (0 . 1) (0 . 0) #f))))
  ;; Paging uses the same displayed-row engine; only logical anchors survive.
  (store:reset! '(base test) source '("abcdefghijklmno" "abc" "def" "ghi" "jkl" "mno" "pqrs"))
  (text-source:open! actor source)
  (select! a '(0 . 3) '(0 . 3)) (select! b '(0 . 7) '(0 . 7)) (show! 27)
  (set-mark! a #t) (key "PAGEDOWN")
  (check 'editor-page-keeps-mark-column-and-other-view
    (list (state a) (car (state b))) '(((4 . 3) (0 . 3) (3 . 0) #t) (0 . 7)))
  (key "C-v")
  (check 'editor-page-at-bottom-selects-edge (car (state a)) '(6 . 3))
  (key "M-v")
  (check 'editor-page-back-lands-inside-wrapped-row (car (state a)) '(0 . 13))
  (widget:focus! root b) (key "PAGEDOWN")
  (check 'editor-page-unwrapped-keeps-its-column (car (state b)) '(4 . 3))
  (widget:focus! root a)
  (store:set-property! actor source 'read-only #t)
  (select! a '(1 . 0) '(2 . 3)) (key "M-w")
  (check 'editor-copy-read-only-reversed-region-without-retargeting
    (list (copy-text) (cadddr (state a)) (eq? ambient (head:current-buffer)) (store:line source 1)) '("abc\ndef" #f #t "abc"))
  (select! a '(1 . 0) '(2 . 3))
  (check 'editor-refused-cut-keeps-clipboard (list (refused? (lambda () (key "C-w"))) (copy-text)) '(#t "abc\ndef"))
  (store:set-property! actor source 'read-only #f)
  (key "C-w")
  (check 'editor-cut-uses-explicit-view-and-can-undo
    (list (store:line source 1) (car (state a)) (copy-text) (begin (undo! a) (store:line source 2))) '("" (1 . 0) "abc\ndef" "def"))
  (select! a '(1 . 0) '(1 . 0))
  (key "C-k") (key "C-k") (key "C-k")
  (check 'editor-kills-accumulate-text-and-newlines (copy-text) "abc\ndef")
  (select! b '(0 . 0) '(0 . 0)) (widget:focus! root b) (key "C-k")
  (check 'editor-kill-in-another-view-starts-a-new-copy (copy-text) "abcdefghijklmno")
  (widget:focus! root a) (select! a '(0 . 0) '(0 . 0))
  (let ([before (text)])
    (insert! a "T")
    (let ([typed (text)])
      (dispatch:input! root '(text "P\r\nQ\r" paste))
      (let ([pasted (text)])
        (insert! a "U")
        (check 'editor-paste-normalizes-newlines-and-isolates-undo
          (list (vector-ref pasted 0) (vector-ref pasted 1)
            (begin (undo! a) (equal? (text) pasted)) (begin (undo! a) (equal? (text) typed)) (begin (undo! a) (equal? (text) before)))
          '("TP" "Q" #t #t #t)))))
  (copy-text! "yank\n") (key "C-y")
  (check 'editor-yank-preserves-final-newline (list (store:line source 0) (car (state a))) '("yank" (1 . 0)))
  (undo! a)
  (select! a '(2 . 0) '(2 . 3)) (copy-text! "keep")
  (let-values ([(lines revision) (store:snapshot source)])
    (store:edit! '(agent "editor") source revision (text:make-span 2 1 2 2) '("X")))
  (text-source:open! actor source)
  (check 'editor-stale-copy-and-cut-refuse-without-losing-either-text
    (list (refused? (lambda () (copy-region! a))) (refused? (lambda () (kill-region! a))) (copy-text) (store:line source 2))
    '(#t #t "keep" "gXi"))
  (store:reset! '(base test) source '("(a b)" "(c d)"))
  (text-source:open! actor source) (select! a '(0 . 0) '(0 . 0))
  (key "C-M-d") (key "C-M-@") (key "C-M-@")
  (check 'editor-expression-mark-extends-without-moving-caret (list-head (state a) 2) '((0 . 1) (0 . 4)))
  (select! a '(0 . 3) '(0 . 3)) (key "C-M-t")
  (check 'editor-expression-transposition-is-one-undoable-edit
    (list (store:line source 0) (car (state a)) (begin (undo! a) (store:line source 0))) '("(b a)" (0 . 4) "(a b)"))
  (select! a '(0 . 1) '(0 . 1)) (key "C-M-k") (key "C-M-k")
  (check 'editor-expression-kills-accumulate-through-canonical-bindings (list (store:line source 0) (copy-text)) '("()" "a b"))
  (select! a '(1 . 5) '(1 . 5)) (key "C-M-BACKSPACE")
  (check 'editor-backward-expression-cut-keeps-other-rows (list (store:line source 0) (store:line source 1) (copy-text)) '("()" "" "(c d)"))
  (mode:register! "editor-transform" '() '() #f)
  (mode:register-indenter! "editor-transform" (lambda (input from to) (make-list (+ 1 (- to from)) '(2 4))))
  (mode:register-formatter! "editor-transform"
    (lambda (input from to) (map (lambda (row) (string-upcase (vector-ref (mode:source-lines input) (+ from row)))) (iota (+ 1 (- to from))))))
  (store:reset! '(base test) source '(" a" " b" "" "tail"))
  (store:set-property! actor source 'mode "editor-transform") (store:set-property! actor source 'trailing #f)
  (text-source:open! actor source) (select! a '(0 . 1) '(1 . 2))
  (indent-region! a)
  (check 'editor-indent-maps-both-logical-selection-endpoints
    (list (store:line source 0) (store:line source 1) (list-head (state a) 2)) '("  a" "  b" ((0 . 2) (1 . 3))))
  (undo! a) (select! a '(2 . 0) '(2 . 0))
  (key "TAB") (key "TAB") (key "TAB")
  (check 'editor-tab-cycles-stops-and-pads-blank-line (list (store:line source 2) (car (state a))) '("  " (2 . 2)))
  (format-buffer! a)
  (check 'editor-format-keeps-final-newline-in-same-undo-action
    (list (store:line source 3) (store:property source 'trailing #f)
      (begin (undo! a) (list (store:line source 3) (store:property source 'trailing #f)))) '("TAIL" #t ("tail" #f)))
  (mode:register-formatter! "editor-transform"
    (lambda (input from to)
      (select! a '(1 . 0) '(1 . 0))
      '("ONE" "TWO")))
  (format-buffer! a)
  (check 'editor-format-does-not-overwrite-a-newer-callback-selection (car (state a)) '(1 . 0))
  (select! a '(1 . 0) '(1 . 0))
  (mode:register-formatter! "editor-transform" (lambda args '()))
  (format-buffer! a)
  (check 'editor-formatter-can-empty-the-document (text) '#(""))
  (replace-region-text! a '(0 . 0) '(0 . 0) "new\ntext")
  (check 'editor-explicit-range-replacement (list (text) (car (state a))) '(#("new" "text") (1 . 4)))
  ;; Mode contexts belong to the explicit editor, including inherited keys.
  (unless (mode:find "scheme") (mode:register! "scheme" '() '() #f))
  (pretty-scheme:init!)
  (store:set-property! actor source 'mode "pretty-scheme-depth")
  (store:reset! '(base test) source '("[foo"))
  (text-source:open! actor source) (select! a '(0 . 4) '(0 . 4))
  (widget:pump!) (show! 27)
  (key ")")
  (check 'editor-mode-binding-uses-its-own-source
    (list (store:line source 0) (eq? ambient (head:current-buffer))
      (cadar (cadr (widget:key-scopes root "")))) '("[foo]" #t (pretty-scheme-depth scheme widget-editor)))
  (keymap:bind-default! 'scheme "C-c x" (keymap:call move! widget:target 'start))
  (key "C-c")
  (store:set-property! actor source 'mode "editor-test")
  (widget:pump!)
  (key "x")
  (check 'editor-mode-change-cancels-pending-chord (car (state a)) '(0 . 5))
  ;; One portable annotation producer decorates two widths of the same text.
  (store:set-property! actor source 'mode #f)
  (store:reset! '(base test) source '("abcdefghijklmno" "a界éz"))
  (text-source:open! actor source) (select! a '(0 . 0) '(0 . 0)) (select! b '(0 . 0) '(0 . 0))
  (model:register-kind! 'editor-annotations 1 list?)
  (port:register! '(model editor-annotations 1) '((output ranges list (value))))
  (let* ([producer (model:create! actor 'editor-annotations 1 'session 'transient (list (list 'buffer source))
                     (list source (text-source:revision (text-source:lookup source))
                       '(((0 8 0 13) match) ((1 1 1 2) conflict-disk))))])
    (interaction:bind! actor root (map (lambda (id) (list id 'annotations #f (list producer 'ranges))) (list a b)))
    (widget:pump!)
    (let ([f (show! 27)])
      (check 'editor-annotations-project-through-wrap-and-wide-characters
        (list (face (body f 0) 8 0) (face (body f 0) 2 1) (face (body f 1) 12 0)
          (face (body f 0) 1 2) (face (body f 0) 2 2)) '(match match match conflict-disk #f)))
    (insert! a "!")
    (let ([f (show! 27)])
      (check 'editor-annotations-rebase-without-a-producer-update
        (list (face (body f 0) 8 0) (face (body f 0) 9 0) (face (body f 0) 3 1)) '(#f match match)))
    (replace-region-text! a '(0 . 10) '(0 . 11) "X")
    (let ([f (show! 27)])
      (check 'editor-overlapping-edit-hides-only-invalidated-annotation
        (list (face (body f 0) 9 0) (face (body f 0) 1 2)) '(#f conflict-disk)))
    (text-source:forget! source) (text-source:open! actor source) (insert! a "Y")
    (check 'editor-annotations-without-history-are-withheld
      (face (body (show! 27) 0) 1 2) #f)
    (interaction:bind! actor root (map (lambda (id) (list id 'annotations (list producer 'ranges) #f)) (list a b))))
  (store:reset! '(base test) source '("aa bb cc"))
  (text-source:open! actor source) (select! a '(0 . 8) '(0 . 0))
  (let ([old (basis a)])
    (store:edit! '(agent "rewrite") source (caddr old) (text:make-span 0 3 0 5) '("BBB"))
    (text-source:open! actor source)
    (check 'editor-bulk-rewrite-skips-stale-ranges-and-groups-history
      (list (rewrite-regions! a old '(((0 . 0) (0 . 2) "AAA") ((0 . 3) (0 . 5) "discard") ((0 . 6) (0 . 8) "C")))
        (text) (car (state a)) (begin (undo! a) (text))) '(2 #("AAA BBB C") (0 . 9) #("aa BBB cc"))))
  (let ([old (basis a)])
    (check 'editor-bulk-rewrite-validates-all-ranges-before-editing
      (list (refused? (lambda () (rewrite-regions! a old '(((0 . 0) (0 . 2) "lost") ((0 . 1) (0 . 3) "bad")))))
        (text)) '(#t #("aa BBB cc"))))
  (store:reset! '(base test) source '("aa bb cc"))
  (text-source:open! actor source) (select! a '(0 . 8) '(0 . 8))
  (let ([old (basis a)] [once? #f] [token #f])
    (set! token (store:subscribe! source (lambda (event)
                                           (when (and (not once?) (eq? (car event) 'edit))
                                             (set! once? #t)
                                             (let-values ([(lines revision) (store:snapshot source)])
                                               (store:edit! '(agent "rewrite-race") source revision (text:make-span 0 3 0 5) '("FOREIGN")))
                                             (text-source:open! actor source) (select! a '(0 . 4) '(0 . 4))))))
    (check 'editor-bulk-rewrite-keeps-interleaved-text-and-new-selection
      (list (rewrite-regions! a old '(((0 . 0) (0 . 2) "A") ((0 . 3) (0 . 5) "lost") ((0 . 6) (0 . 8) "C")))
        (text) (car (state a))) '(2 #("A FOREIGN C") (0 . 3)))
    (store:unsubscribe! token))
  (paren:init!)
  (check 'context-highlights-use-explicit-text-and-reject-mismatched-brackets
    (map (lambda (line)
           (map (lambda (col) (not (null? (mode:highlights (mode:source (vector line) '()) #f (cons 0 col)))))
             (list 0 (string-length line))))
      '("([])" "(]" "([)]" "[x]")) '((#t #t) (#f #f) (#f #f) (#t #t)))
  (store:reset! '(base test) source '("[x]"))
  (text-source:open! actor source) (select! a '(0 . 0) '(0 . 0)) (select! b '(0 . 0) '(0 . 0))
  (let ([f (show! 27)])
    (check 'nested-bracket-highlighting-follows-local-focus
      (list (face (body f 0) 0 0) (face (body f 0) 2 0) (face (body f 1) 0 0)
        (begin (widget:focus! root b) (let ([f (show! 27)]) (list (face (body f 0) 0 0) (face (body f 1) 0 0)))))
      '(matching-paren matching-paren #f (#f matching-paren))))
  (widget:focus! root a)
  (store:reset! '(base test) source '("replacement"))
  (text-source:forget! source) (text-source:open! actor source)
  (check 'editor-unknown-selection-history-refuses-until-explicit-selection
    (list (widget:caret (show! 27)) (refused? (lambda () (insert! a "lost")))
      (begin (select! a '(0 . 3) '(0 . 3)) (insert! a "X") (store:line source 0)))
    '(#f #t "repXlacement"))
  (let ([fired? #f] [token #f])
    (select! a '(0 . 0) '(0 . 3))
    (set! token (store:subscribe! source (lambda (event)
                                           (when (and (not fired?) (eq? (car event) 'edit))
                                             (set! fired? #t) (store:reset! '(base test) source '("external reset"))))))
    (check 'editor-lost-postcommit-history-keeps-accepted-cut-and-new-text
      (list (refused? (lambda () (kill-region! a))) (copy-text) (store:line source 0)) '(#f "rep" "external reset"))
    (store:unsubscribe! token))
  (widget:prepare! root 0 0)
  (store:delete! '(base test) source)
  (text-source:forget! source)
  (check 'editor-retired-source-leaves-a-serviceable-placeholder
    (begin (widget:pump!) (not (refused? (lambda () (show! 27))))) #t)
  (widget:unmount! root) (widget:invalidate!))
