;; Small API fixture: each document has an explicit editor; no default host.
(import (prefix (head edit) edit:) (prefix (head editor) editor:) (prefix (head editor-state) editor-state:)
        (prefix (head interaction) interaction:) (prefix (head text-source) text-source:)
        (prefix (state view) view:))
(for-each kernel:load-module! '("widget" "edit"))
(define editing #f)
(define presentations '())
(define (document-editor id)
  (cond [(assoc id presentations) => cdr]
    [else (let ([editor (edit:create-view! head:ui-actor id '())])
            (set! presentations (cons (cons id editor) presentations)) editor)]))
(define (show! id)
  (when editing (widget:unmount! editing))
  (set! editing (document-editor id))
  (widget:mount! editing 'editing-fixture)
  (widget:present! (list (list (widget:prepare! editing 80 12) 0 0))) id)
(define (fresh name lines)
  (show! (store:create! head:ui-actor name lines '((trailing . #t)))))
(define (visit! path)
  (edit:visit-file! path
    (lambda (kind id)
      (unless (eq? kind 'buffer) (error 'visit! "expected a document" kind))
      (show! id))))
(define (state-of id)
  (let* ([d (interaction:snapshot (document-editor id))] [source (text-source:lookup id)])
    (append (or (editor-state:points source (text-source:revision source) d) (list-head (view:state d) 3))
      (list (cadddr (view:state d))))))
(define (point) (car (state-of (view:source (interaction:snapshot editing)))))
(define (mark) (cadr (state-of (view:source (interaction:snapshot editing)))))
(define (goto! p) (edit:move! editing p))
(define (lines-of id) (text-source:lines (text-source:lookup id)))
(define (text-of id) (vector->list (lines-of id)))
(define (refresh!) (widget:pump!) (widget:prepare! editing 80 12))
(define (submit! id span replacement . context)
  (let-values ([(lines revision) (store:snapshot id)])
    (text-source:edit! head:ui-actor (list lines id revision) span replacement
      (if (pair? context) (car context) #f) '())
    (text-source:open! head:ui-actor id)))
(define (refused? thunk)
  (guard (ex [(kernel:refusal? ex) #t] [else (raise ex)]) (thunk) #f))
