#!/usr/bin/env scheme-script
;; Finder composition and its base provider share one filesystem fixture.
(import (chezscheme))
(include "tests/roots.ss")
(test-roots! 'base)
(eval
  '(begin
     (import (prefix (apps finder) finder:) (prefix (head edit) edit:)
             (prefix (core kernel) kernel:) (prefix (head head) head:)
             (prefix (head widget) widget:) (prefix (head window) window:)
             (prefix (head entry) entry:) (prefix (head table) table:)
             (prefix (head control) control:) (prefix (head range) range:)
             (prefix (head interaction) interaction:) (prefix (head dispatch) dispatch:)
             (prefix (head paint) paint:) (prefix (head keymap) keymap:)
             (prefix (head catalogue-host) catalogue-host:)
             (prefix (foundation string) string:) (prefix (foundation text) text:)
             (prefix (foundation path-filter) path-filter:)
             (prefix (service log) log:) (prefix (service filesystem) filesystem:)
             (prefix (service document) document:) (prefix (service file) file:)
             (prefix (state collection) collection:) (prefix (state model) model:)
             (prefix (state view) view:) (prefix (state store) store:)
             (prefix (sys glyph) glyph:) (prefix (sys sys) sys:) (prefix (test) test:))
     (widget:init!) (window:init!) (entry:init!) (control:init!) (table:init!) (finder:init!) (edit:init!)
     (define check test:check)
     (define root (format "/tmp/e-files-~a-~a" (get-process-id) (random 1000000)))
     (define (path name) (string-append root "/" name))
     (define names '("apple.txt" "APPLE.txt" "zeta.txt" "a 日本語 long (name).txt" "odd\nname.txt" ".dot"
                     "small/needle-one.txt" "small/nested/needle-only.txt"
                     "large/needle-a.txt" "large/needle-b.txt" "large/needle-c.txt"))
     (define directories '("empty" "large" "small" "small/nested" "small/.日本語\n" "small/.日本語\n/leaf"))
     (mkdir root)
     (for-each (lambda (name) (mkdir (path name))) directories)
     (for-each (lambda (name) (call-with-output-file (path name) (lambda (p) (display (if (string=? name "zeta.txt") "z\n" "one\ntwo\n") p)))) names)
     (include "tests/filesystem.sps")
     (define (get xs key) (cdr (assq key xs)))
     (define (child id name) (cadr (assq name (view:children (interaction:snapshot id)))))
     (paint:set-screen-cols! 300) (paint:window-layout)
     (define app (finder:open-directory! root))
     (define host (head:buffer-fact (head:current-buffer) 'widget-id #f))
     (define table (child app 'table))
     (define entry (child (child table 'filter) 'entry))
     (define query (view:source (interaction:snapshot table)))
     (define (metadata) (get (collection:summary query) 'value))
     (define (filter-text)
       (let-values ([(s d inputs) (widget:context entry 'current)]) (vector-ref (get s 'value) 0)))
     (define (selection) (get (view:state (interaction:snapshot table)) 'selection))
     (define (draw! . width)
       (range:pump!) (widget:pump!)
       (let ([f (widget:prepare! host (if (pair? width) (car width) 300) 20)])
         (widget:present! (list (list f 0 0))) f))
     (define (entry-frame f)
       (if (equal? (widget:frame-id f) entry) f (exists entry-frame (widget:frame-children f))))
     (define (settle!)
       (test:await 'finder-ready
         (lambda ()
           (let* ([f (draw!)] [v (metadata)] [s (selection)]
                  [r (range:read query (get v 'generation) 0 (min 18 (get v 'count)) '(name kind link size modified created permissions count exact))])
             (and (eq? (get v 'status) 'ready) (get v 'complete)
               (equal? (caddr (assq 'context (widget:frame-inputs (entry-frame f)))) v)
               (or (zero? (get v 'count)) (and s (= (cadr s) (get v 'generation))))
               (eq? (car r) 'ready)
               (for-all (lambda (row) (for-all (lambda (c) (not (eq? (cadr c) 'pending))) (caddr row))) (list-ref r 4)))))))
     (define (rows)
       (let* ([v (metadata)] [r (collection:range query (get v 'generation) 0 256 '(name path kind))])
         (if (eq? (car r) 'stale) (rows) (list-ref r 4))))
     (define (keys) (map cadr (rows)))
     (define (chosen) (and (selection) (caddr (selection))))
     (define (filter! value) (entry:set-text! entry value) (settle!))
     (define (press! . keys) (for-each dispatch:key! keys) (settle!))
     (define (contains? text needle) (and (string:search text needle 0 (string-length text)) #t))
     (define (visible? needle) (exists (lambda (s) (contains? s needle)) (widget:frame-lines (draw!))))
     (define (styled f row role)
       (let* ([s (list-ref (widget:frame-lines f) row)] [styles (widget:frame-styles f row s)])
         (list->string
           (map (lambda (i) (string-ref s i))
             (filter (lambda (i) (let ([r (vector-ref styles i)]) (if (pair? r) (memq role r) (eq? r role)))) (iota (string-length s)))))))
     (define (select! key) (table:select! table key) (settle!))
     (define (complete!)
       (finder:complete! app)
       (test:await 'finder-completion-applied
         (lambda () (draw!) (let ([v (metadata)])
                              (and (eq? (get v 'status) 'ready) (null? (get (get v 'details) 'completion)))))))
     (settle!)
     (check 'finder-starts-focused-in-entry-with-real-row-keys
       (list (equal? (widget:focused host) entry) (head:buffer-name (head:current-buffer))
         (map (lambda (r) (caddr (assq 'name (caddr r)))) (rows)))
       '(#t "<finder>" ("empty" "large" "small" "a 日本語 long (name).txt" "APPLE.txt" "apple.txt" "odd\nname.txt" "zeta.txt")))
     (press! "HOME")
     (let ([before (chosen)])
       (press! "DOWN")
       (check 'finder-arrows-work-before-any-pointer-event (list (not (equal? before (chosen))) (equal? (widget:focused host) entry)) '(#t #t)))
     (filter! (string-append root "/ needle"))
     (check 'finder-shares-base-hierarchy-and-safe-labels
       (list (length (keys)) (visible? "[5 matches]") (visible? " ∧ needle")) '(8 #t #t))
     (filter! (string-append root "/ only"))
     (check 'new-filter-adopts-the-querys-nested-file-suggestion
       (chosen) (list 'path (path "small/nested/needle-only.txt") 'file))
     (check 'path-tokens-are-underlined-without-marking-metadata
       (styled (draw!) 4 'mark) "only")
     (filter! (path "small/nested/"))
     (press! "LEFT" "LEFT")
     (check 'rapid-parent-motion-preserves-return-child (list (filter-text) (chosen)) (list (path "") (list 'path (path "small") 'directory)))
     (press! "RIGHT") (press! "RIGHT")
     (check 'directory-history-retraces-route (filter-text) (path "small/nested/"))
     (press! "LEFT" "LEFT" "RIGHT" "RIGHT")
     (check 'rapid-left-right-retains-all-navigation-intent (filter-text) (path "small/nested/"))
     (filter! (path "small")) (complete!) (settle!)
     (check 'base-completion-enters-unique-directory (filter-text) (path "small/"))
     (entry:insert! entry " ") (draw!)
     (check 'separator-projects-as-conjunction (visible? " ∧ ") #t)
     (press! "BACKSPACE")
     (check 'backspace-deletes-one-logical-separator (filter-text) (path "small/"))
     (press! "C-u" "/" "C-b" "DELETE")
     (check 'cleared-entry-keeps-empty-root (filter-text) "")
     (press! "a")
     (check 'typing-enforces-the-leading-path (filter-text) "/a")
     (filter! (path "a 日本語"))
     ;; Quoted path spaces are literal, not conjunction separators.
     (filter! (path-filter:format-keys (list (path "a 日本語 long (name).txt"))))
     (check 'quoted-unicode-path-keeps-literal-spaces (list (visible? " ∧ ") (get (get (metadata) 'details) 'matches)) '(#f 1))
     (filter! (string-append root "/ zeta"))
     (let ([v (metadata)] [old (filter-text)])
       (finder:complete! app)
       (entry:insert! entry "x") (draw!) (settle!)
       (check 'typing-supersedes-completion (filter-text) (string-append old "x")))
     (filter! (path ""))
     (press! "F2" "F2" "F1")
     (check 'finder-compound-sorting-uses-generic-table-api (get (metadata) 'sort) '((size descending) (name ascending)))
     (press! "F2" "F1" "F1")
     (filter! (string-append root "/ ."))
     (check 'finder-hidden-toggle-controls-dot-filter-and-indicator
       (let ([states '()])
         (for-each (lambda (toggle?)
                     (when toggle? (press! "M-."))
                     (set! states (cons (list (and (member (list 'path (path ".dot") 'file) (keys)) #t)
                                          (and (visible? "[showing hidden]") #t)) states))) '(#f #t #t))
         (reverse states))
       '((#f #f) (#t #t) (#f #f)))
     (filter! (path-filter:format-keys (list (path "small/.日本語\n/"))))
     (check 'finder-explicit-hidden-directory-preserves-visibility-setting
       (list (keys) (and (visible? "[showing hidden]") #t)) (list (list (list 'path (path "small/.日本語\n/leaf") 'directory)) #f))
     (filter! (path ""))
     (select! (list 'path (path "zeta.txt") 'file))
     (define finder-buffer (head:current-buffer))
     (define wide (widget:frame-lines (draw!)))
     (press! "RET")
     (check 'finder-opens-file-through-window-host (head:buffer-file (head:current-buffer)) (path "zeta.txt"))
     (finder:open!) (settle!)
     (check 'finder-wide-reopen-retains-metadata-and-fitting
       (list (eq? finder-buffer (head:current-buffer)) (equal? wide (widget:frame-lines (draw!)))
         (visible? "rw") (visible? "Modified")) '(#t #t #t #t))
     (draw! 35) (draw!)
     (check 'finder-width-belongs-to-mount-and-expands-again (equal? wide (widget:frame-lines (draw!))) #t)
     (filter! (path-filter:format-keys (list (path "new/inner 日本語/note.txt"))))
     (check 'finder-missing-hierarchy-has-proposal-identities
       (list (map car (keys)) (visible? "[create]") (visible? "[0 matches]")) '((proposal proposal proposal) #t #t))
     (let ([f (draw!)])
       (check 'missing-tail-and-creation-ghosts-use-italics
         (list (contains? (styled f 0 'italic) "new/inner 日本語/note.txt")
           (contains? (styled f 0 'ghost) "[0 matches]") (contains? (styled f 4 'ghost) "[create]")) '(#t #t #t)))
     (check 'narrow-proposals-preserve-create-ghost (contains? (styled (draw! 20) 4 'ghost) "[create]") #t)
     (select! (list 'proposal (path "new/inner 日本語/note.txt") 'file))
     (press! "RIGHT")
     (check 'right-on-proposed-file-has-no-side-effects (file-exists? (path "new")) #f)
     (press! "RET")
     (check 'creation-opens-file-and-logs-parent-first
       (list (head:buffer-file (head:current-buffer))
         (map log:datum (reverse (list-head (log:entries 'file:create!) 3))))
       (list (path "new/inner 日本語/note.txt")
         (list (string-append "Created directory " (path "new/"))
           (string-append "Created directory " (path "new/inner 日本語/"))
           (string-append "Created file " (path "new/inner 日本語/note.txt")))))
     (finder:open!) (settle!)
     (check 'creation-refreshes-proposals-without-losing-filter (map car (keys)) '(path))
     (filter! (path "only/inner/"))
     (select! (list 'proposal (path "only") 'directory))
     (press! "RET")
     (check 'intermediate-proposal-creates-only-the-picked-directory
       (list (filter-text) (file-directory? (path "only")) (file-exists? (path "only/inner"))) (list (path "only/") #t #f))
     (filter! (path "race"))
     (call-with-output-file (path "race") (lambda (p) (display "preserve" p)))
     (press! "RET")
     (check 'creation-race-refuses-stale-proposal
       (list (and (head:buffer-named "race") #t) (call-with-input-file (path "race") get-string-all)) '(#f "preserve"))
     (finder:open!) (settle!)
     ;; The same composition works unmounted from a window with an explicit
     ;; host command; it never finds or replaces the current window itself.
     (let* ([destination #f] [other (finder:create! '() root)]
            [receiver (view:create! head:ui-actor #f 'finder-fixture 1 '() '())])
       (widget:register! 'finder-fixture 1 (list (cons 'actions (list (cons 'open (lambda (id ref) (set! destination ref)))))))
       (let ([d (view:snapshot other)])
         (view:arrange! head:ui-actor (list (list other (get (model:snapshot other) 'revision) (view:children d)
                                              (list (list 'commands (list 'open receiver 'open '()))))) '()))
       (widget:mount! other 'embedded-finder) (widget:mount! receiver 'embedded-receiver)
       (let* ([q (view:source (view:snapshot other))] [before (head:current-buffer)])
         (test:await 'embedded-ready (lambda () (eq? (get (get (collection:summary q) 'value) 'status) 'ready)))
         (let* ([v (get (collection:summary q) 'value)] [key (list 'path (path "zeta.txt") 'file)])
           (finder:choose! other #f (list q (get v 'generation) key) (get v 'basis)))
         (check 'embedded-finder-delivers-reference-without-window-placement
           (list (eq? before (head:current-buffer)) (equal? destination (catalogue-host:reference (head:buffer-named "zeta.txt")))) '(#t #t)))
       (widget:unmount! other) (widget:unmount! receiver))
     (for-each (lambda (name) (delete-file (path name))) (append names '("new/inner 日本語/note.txt" "race")))
     (for-each (lambda (name) (delete-directory (path name))) (append '("new/inner 日本語" "new" "only") (reverse directories)))
     (delete-directory root)
     (test:finish! 'finder)))
