(let ()
  (import (prefix (service git-source) git-source:) (prefix (service git) git:))
  (define (get r k) (cdr (assq k r)))
  (define (child id key) (cadr (assq key (view:children (view:snapshot id)))))
  (define (query id) (view:source (view:snapshot id)))
  (define root #f)
  (define (pump!) (range:pump!) (widget:pump!) (widget:present! (list (list (widget:prepare! root 200 30) 0 0))))
  (define (rows id)
    (define answer #f)
    (test:await 'git-result
      (lambda ()
        (pump!)
        (let ([v (get (collection:summary id) 'value)])
          (when (eq? (get v 'status) 'unavailable) (error 'git-result "query failed" v))
          (and (eq? (get v 'status) 'ready)
            (let ([r (collection:range id (get v 'generation) 0 100 '(commit path subject))])
              (and (eq? (car r) 'ready) (begin (set! answer r) #t))))))) answer)
  (define (choose! id reply row)
    (git-view:choose! id (list (query id) (cadr reply) (cadr row)) (caddr reply)))
  (parameterize ([kernel:registering-module 'git-view-test]) (git-view:init!))
  (let* ([a (git-view:create! ".")] [b (git-view:create! "lib")]
         [qa (query a)] [qb (query b)] [patch (child a 'patch)] [qp (query patch)]
         [document (query (child patch 'text))])
    (check 'git-creation-does-not-start-work (get (get (model:snapshot qa) 'value) 'generation) 0)
    (set! root (view:create! head:ui-actor #f 'row 1 '() '()))
    (view:arrange! head:ui-actor (list (list root 0 (list (list 'a a '(grow 1)) (list 'b b '(grow 1))) '())) '())
    (widget:mount! root 'nested-git)
    (let* ([first (rows qa)] [other (rows qb)] [commit (car (list-ref first 4))])
      (test:await 'git-table-painted
        (lambda () (pump!) (exists (lambda (line) (string:search line "Subject" 0 (string-length line))) (widget:frame-lines (widget:prepared a)))))
      (check 'git-composition-renders-nested-table-and-editor
        (list (exists (lambda (line) (and (string:search line "Subject" 0 (string-length line)) #t)) (widget:frame-lines (widget:prepared a)))
          (exists (lambda (line) (and (string:search line "No patch selected" 0 (string-length line)) #t)) (widget:frame-lines (widget:prepared b)))) '(#t #t))
      (check 'git-history-is-bounded-and-independent (list (length (list-ref first 4)) (map cadr (list-ref other 4)))
        (list 20 (map cadr (list-ref first 4))))
      (choose! a first commit)
      (check 'git-patch-path-is-literal
        (map git:patch-line-text (git:patch-lines (git:file-patch (git:open ".") (cadadr commit) "*"))) '(""))
      (let* ([expanded (rows qa)] [files (filter (lambda (r) (eq? (caadr r) 'file)) (list-ref expanded 4))])
        (check 'git-expansion-only-changes-one-browser
          (list (> (length files) 0) (map cadr (list-ref (rows qb) 4))) (list #t (map cadr (list-ref other 4))))
        (check 'git-stale-selection-refuses (refused? (lambda () (choose! a first commit))) #t)
        (choose! a expanded (car files))
        (rows qp)
        (check 'git-patch-is-read-only-and-captures-the-selected-path
          (list (store:property document 'read-only) (store:line document 0))
          (list #t (format "~a  ~a" (cadadr (car files)) (caddr (cadr (car files))))))
        (let* ([fork (view:fork! head:ui-actor a)] [copy-query (query (child fork 'patch))]
               [copy-document (query (child (child fork 'patch) 'text))]
               [before (store:revision document)])
          (widget:mount! fork 'git-fork)
          (choose! fork expanded (car files))
          (rows copy-query)
          (check 'git-forks-own-their-patch-query-and-output
            (list (equal? (query fork) qa) (not (equal? copy-query qp)) (not (equal? copy-document document))
              (= before (store:revision document)) (store:line copy-document 0))
            (list #t #t #t #t (store:line document 0)))
          (widget:unmount! fork)
          (view:retire! head:ui-actor fork (model:revision fork))
          (test:await 'git-private-output-released (lambda () (not (store:exists? copy-document))))
          (check 'git-retirement-keeps-borrowed-history-and-other-preview
            (list (model:snapshot copy-query) (and (model:snapshot qa) #t) (store:exists? document)) '(#f #t #t)))
        (let ([last (car (reverse files))])
          (do ([i 0 (+ i 1)]) ((= i 6)) (choose! a expanded (if (even? i) (car files) last)))
          (rows qp)
          (check 'git-rapid-selection-publishes-only-the-last-request
            (store:line document 0) (format "~a  ~a" (cadadr last) (caddr (cadr last)))))
        (kernel:retract-module! 'git-view-test)
        (parameterize ([kernel:registering-module 'git-view-test]) (git-view:init!))
        (pump!)
        (check 'git-reload-keeps-query-and-patch-identity (list (query a) (query (child (child a 'patch) 'text))) (list qa document))
        (widget:unmount! root)
        (let ([before (store:revision document)])
          (git-source:refresh! head:ui-actor qa)
          (check 'hidden-history-refresh-does-not-touch-patch (store:revision document) before))))))
