;; Reuse the namespace process and the ordinary widget/collection pump.
(let ()
  (define history (history:create! who 'persistent))
  (define document (list 'buffer (store:create! who "history text" '("retained text") '((internal . #t)))))
  (define first (history:append! who history 0 (list 'text 1 document) document (list document)))
  (define second (history:append! who history 1 (list 'result 1 job) #f (list job env)))
  (define missing (history:append! who history 2 '(missing-example 1 (portable data)) #f '()))
  (define a #f)
  (define b #f)
  (define (step! id width)
    (range:pump!) (widget:pump!) (widget:present! (list (list (widget:prepare! id width 12) 0 0))))
  (define (page-ready? id text width)
    (step! id width)
    (and (exists (lambda (line) (string:search line text 0 (string-length line)))
           (widget:frame-lines (widget:prepare! id width 12))) #t))
  (history-view:init!) (table:init!)
  (check 'history-stale-append-is-atomic-and-projections-are-explicit
    (list (history:append! who history 0 '(text 1 ignored) #f '())
      (get (value history) 'count) (history-view:projection first) (history-view:projection second))
    '(#f 3 "retained text" "[Text projection unavailable]"))
  (set! a (history-view:create! history 1))
  (set! b (view:fork! who a))
  (widget:mount! a 'history-a) (widget:mount! b 'history-b)
  (test:await 'history-page (lambda () (and (page-ready? a "retained text" 30) (page-ready? b "retained text" 60))))
  (check 'history-views-host-independent-children
    (equal? (widget:descendant a 'item-0) (widget:descendant b 'item-0)) #f)
  (history-view:move! a 2)
  (test:await 'missing-history-definition (lambda () (page-ready? a "Unavailable presentation" 50)))
  (check 'history-navigation-is-bounded-and-independent
    (list (length (view:children (view:snapshot a))) (page-ready? b "retained text" 60)) '(2 #t))
  (history-view:register! 'missing-example 1
    (lambda (data) (view:create! who #f 'label 1 '((text . "Registered later")) '())))
  (test:await 'late-history-definition (lambda () (page-ready? a "Registered later" 50)))
  (widget:unmount! a) (widget:mount! a 'history-again)
  (test:await 'history-remount (lambda () (page-ready? a "Registered later" 50)))
  (widget:unmount! a) (widget:unmount! b)
  (check 'history-hiding-preserves-borrowed-work
    (list (and (model:snapshot job) #t) (store:exists? (cadr document))) '(#t #t))
  (load "examples/history.e")
  (let ([root (history-example:create!)])
    (widget:mount! root 'history-example)
    (test:await 'runtime-history-composition
      (lambda () (and (page-ready? root "Text, evaluation" 90) (page-ready? root "alpha.sls" 90))))
    (let ([table (widget:descendant root 'item-2 'table)])
      (widget:focus! root (widget:descendant table 'body 'rows))
      (table:move! table 'first)
      (test:await 'typed-history-preview (lambda () (page-ready? root "Selected: alpha.sls" 90))))
    (check 'history-zero-geometry (widget:frame-lines (widget:prepare! root 0 0)) '())
    (let* ([job (view:source (view:snapshot (widget:descendant root 'item-1)))]
           [environment (get (value job) 'environment)])
      (test:await 'history-example-job (lambda () (finished? job)))
      (widget:unmount! root)
      (environment:close! who environment (get (value environment) 'generation)))))
