(let ([formatted 0])
  (define (get r k) (cdr (assq k r)))
  (define root #f)
  (define a #f)
  (define b #f)
  (define (pump!) (range:pump!) (widget:pump!) (widget:present! (list (list (widget:prepare! root 600 8) 0 0))))
  (define (shown id needle)
    (exists (lambda (line) (string:search line needle 0 (string-length line))) (widget:frame-lines (widget:prepared id))))
  (define (ready id needle) (test:await 'journal-shown (lambda () (pump!) (shown id needle))))
  (define (state id) (view:state (interaction:snapshot id)))
  (log:register-formatter! 'journal-ui (lambda (datum) (set! formatted (+ 1 formatted)) (widget:pump!) datum)
    (lambda (text) (make-vector (string-length text) 'string)))
  (log:add! 'journal-ui "first\nsecond" #f)
  (parameterize ([kernel:registering-module 'journal-ui]) (log-view:init!))
  (set! a (log-view:create! 'journal-ui))
  (set! b (log-view:create! 'journal-ui))
  (set! root (view:create! head:ui-actor #f 'row 1 '() '()))
  (view:arrange! head:ui-actor (list (list root 0 (list (list 'a a '(grow 1)) (list 'b b '(grow 2))) '())) '())
  (widget:mount! root 'nested-journal)
  (ready a "second") (ready b "second")
  (check 'journal-multiline-records-render-at-independent-widths
    (list (and (shown a "first") #t) (and (shown b "first") #t) (car (state a)) (car (state b)))
    (list #t #t (car (state a)) (car (state a))))
  (let ([before formatted])
    (pump!) (pump!)
    (check 'unchanged-journal-does-not-reformat formatted before))
  (log-view:move! a 'start)
  (test:await 'journal-start (lambda () (pump!) (and (not (list-ref (state a) 4)) (= (caddr (car (state a))) 0))))
  (let ([held (state a)])
    (log:add! 'journal-ui "last" #f)
    (ready b "last")
    (check 'reader-stays-anchored-while-another-follows (state a) held))
  (let* ([p (car (state b))] [text (car (reverse (filter (lambda (line) (string:search line "last" 0 (string-length line))) (widget:frame-lines (widget:prepared b)))))]
         [end (string-length (string:trim-spaces text #f))])
    (log-view:select! b (list (car p) 0 end) (list (car p) 0 (- end 4)))
    (log-view:copy! b)
    (test:await 'journal-copy (lambda () (pump!) (string=? (seat:copy-text) "last"))))
  (let ()
    (kernel:retract-module! 'journal-ui)
    (parameterize ([kernel:registering-module 'journal-ui]) (log-view:init!))
    (ready a "first")
    (check 'journal-reload-retains-logical-reader-state (list-ref (state a) 4) #f))
  (log:retention 1)
  (test:await 'journal-expired-anchor (lambda () (pump!) (not (shown a "first"))))
  (check 'journal-retention-clamps-to-surviving-record (car (car (state a))) (car (car (state b))))
  (log:retention 4096)
  (do ([i 0 (+ i 1)]) ((= i 180)) (log:add! 'journal-ui (format "record-~a" i) #f))
  (test:await 'journal-records-published
    (lambda () (pump!) (= (get (get (model:snapshot (view:source (interaction:snapshot a))) 'value) 'count) 181)))
  (log-view:move! a 'start)
  (test:await 'journal-oldest (lambda () (pump!) (= (caddr (car (state a))) 0)))
  (let ([first (cadar (car (state a)))])
    (do ([i 0 (+ i 1)]) ((= i 100)) (log-view:move! a 'down))
    (test:await 'journal-motion-crosses-pages
      (lambda () (pump!) (>= (cadar (car (state a))) (+ first 100))))
    (check 'journal-keeps-fast-motion-while-acquiring-pages
      (cadar (car (state a))) (+ first 100)))
  (log-view:move! b 'finish)
  (ready b "record-179")
  (let ([caret (car (state b))])
    (log-view:scroll! b -80)
    (test:await 'journal-wheel-crosses-pages (lambda () (pump!) (< (cadar (caddr (state b))) (- (cadar caret) 50))))
    (check 'journal-wheel-preserves-caret (car (state b)) caret))
  (log-view:set-mark! a #t)
  (log-view:move! a 'finish)
  (ready a "record-179")
  (log-view:copy! a)
  (test:await 'journal-copy-across-pages
    (lambda () (pump!) (string:suffix? "record-179" (seat:copy-text))))
  (check 'journal-copy-keeps-record-order-with-no-page-duplication
    (length (string:lines (seat:copy-text))) 81)
  (widget:unmount! root)
  (log:retention 4096))
