#!/usr/bin/env scheme-script
;; Composed window integration; semantic selection/ranges live in markdown.ss.
(import (chezscheme))
(include "tests/roots.ss")
(test-roots! 'base)
(test-evaluate!
  '(begin
     (import (prefix (test) test:) (prefix (core kernel) kernel:)
             (prefix (head edit) edit:) (prefix (head head) head:) (prefix (service window) window:) (prefix (head window-control) window-control:)
             (prefix (head editor) editor:)
             (prefix (head widget) widget:) (prefix (head interaction) interaction:) (prefix (head range) range:)
             (prefix (head mode) mode:) (prefix (modes md-mode) md-mode:)
             (prefix (apps markdown) markdown:) (prefix (state collection) collection:)
             (prefix (state view) view:) (prefix (state store) store:)
             (prefix (service file) file:) (prefix (foundation text) text:))
     (define check test:check)
     (for-each kernel:load-module! '("collection" "window-control" "editor" "edit" "md-mode"))
     (parameterize ([kernel:registering-module 'markdown-test]) (markdown:init!))
     (define document (store:create! head:ui-actor "notes.md" '("# Heading" "" "one" "two" "" "# Tail")))
     (mode:choose! "markdown" document)
     (define manager (window:create-manager! #f))
     (define w (window:current manager))
     (widget:mount! manager 'markdown-test)
     (define editor (window-control:open-document! w document '((point 2 . 1))))
     (widget:present! (list (list (widget:prepare! manager 80 13) 0 0)))
     (define (source-state) (list (store:revision document) (store:properties document) (edit:buffer-text document)))
     (define before (source-state))
     (define root (markdown:view! w))
     (define body (widget:descendant root 'text))
     (define (pump!)
       (head:before-frame!) (range:pump!) (widget:pump!)
       (let ([f (widget:prepare! manager 80 13)])
         (widget:present! (list (list f 0 0)))))
     (define (state id) (view:state (interaction:snapshot id)))
     (test:await 'markdown-host-origin (lambda () (pump!) (view:basis (interaction:snapshot body))))
     (check 'markdown-host-keeps-source-and-maps-origin
       (list (source-state)
         (car (state body)) (window:document manager w))
       (list before '(2 2 0 0) root))
     (markdown:edit! body)
     (check 'markdown-source-return (list (window:document manager w) (car (state editor)) (store:revision document))
       (list document '(2 . 0) (car before)))
     (store:rename! head:ui-actor document "renamed.md")
     (check 'markdown-source-identity-retains-tool (markdown:view! w) root)
     (pump!)
     (let ([saved (state body)])
       (kernel:retract-module! 'markdown-test)
       (parameterize ([kernel:registering-module 'markdown-test]) (markdown:init!))
       (test:await 'markdown-reload (lambda () (pump!) (equal? (state body) saved)))
       (check 'markdown-definition-reload-keeps-selection (state body) saved))
     ;; Source-relative links are resolved through the explicit host, and a
     ;; linked Markdown document gets a new independently owned composition.
     (define directory (format "/tmp/e-markdown-host-~a" (get-process-id)))
     (mkdir directory)
     (define path (string-append directory "/child.md"))
     (file:write! path '#("# Child") #t)
     (store:set-properties! head:ui-actor document (list (cons 'file (string-append directory "/notes.md"))))
     (markdown:open-link! root document "child.md")
     (define linked (window:document manager w))
     (define linked-body (widget:descendant linked 'text))
     (test:await 'markdown-linked-page (lambda () (pump!) (view:basis (interaction:snapshot linked-body))))
     (check 'markdown-relative-link-opens-presentation
       (list (not (equal? linked root))
         (view:kind (interaction:snapshot linked-body)) (store:property (store:find-file path) 'file))
       (list #t 'markdown path))
     (markdown:edit! linked-body)
     (check 'markdown-linked-source-return (store:property (window:document manager w) 'file #f) path)
     (delete-file path) (delete-directory directory)
     ;; Retirement leaves an explicit unavailable presentation and cannot
     ;; reopen the removed source through a stale command.
     (window-control:open-document! w root)
     (pump!)
     (store:delete! head:ui-actor document)
     (test:await 'markdown-retired-source
       (lambda () (pump!) (test:raises? (lambda () (markdown:edit! body)))))
     (check 'markdown-source-retirement-refuses-return (test:raises? (lambda () (markdown:edit! body))) #t)
     (test:finish! 'markdown-view)))
