#!/usr/bin/env scheme-script
;; Default host integration; semantic selection/ranges live in markdown.ss.
(import (chezscheme))
(include "tests/roots.ss")
(test-roots! 'base)
(test-host!)
(eval
  '(begin
     (import (prefix (test) test:) (prefix (core kernel) kernel:)
             (prefix (head edit) edit:) (prefix (head head) head:) (prefix (head seat) seat:) (prefix (head window) window:)
             (prefix (head widget) widget:) (prefix (head interaction) interaction:) (prefix (head range) range:)
             (prefix (head mode) mode:) (prefix (modes md-mode) md-mode:)
             (prefix (apps markdown) markdown:) (prefix (state collection) collection:)
             (prefix (state view) view:) (prefix (state store) store:)
             (prefix (service file) file:) (prefix (foundation text) text:))
     (define check test:check)
     (collection:init!) (widget:init!) (edit:init!) (window:init!) (md-mode:init!)
     (parameterize ([kernel:registering-module 'markdown-test]) (markdown:init!))
     (define b (seat:new-buffer! "notes.md"))
     (seat:buffer-lines-set! b '#("# Heading" "" "one" "two" "" "# Tail"))
     (seat:with-buffer-mirror b (mode:choose! "markdown"))
     (seat:show-buffer-mirror! b) (seat:goto! '(2 . 1))
     (define document (seat:buffer-store-id b))
     (define before (list (store:revision document) (store:properties document) (seat:buffer-lines b)))
     (define w (seat:current-window))
     (seat:window-width-set! w 80) (seat:window-size-set! w 12)
     (define root (markdown:view! (seat:buffer-store-id b)))
     (define body (widget:descendant root 'app 'text))
     (define host (seat:current-buffer-mirror))
     (define (pump!)
       (head:before-frame!) (range:pump!) (widget:pump!)
       (let ([f (widget:prepare! (seat:buffer-fact (seat:current-buffer-mirror) 'widget-id root) 80 12)])
         (widget:present! (list (list f 0 0)))))
     (define (state id) (view:state (interaction:snapshot id)))
     (test:await 'markdown-host-origin (lambda () (pump!) (view:basis (interaction:snapshot body))))
     (check 'markdown-host-keeps-source-and-maps-origin
       (list (list (store:revision document) (store:properties document) (seat:buffer-lines b))
         (car (state body)) (seat:buffer-store-id host) (seat:buffer-file host))
       (list before '(2 2 0 0) #f #f))
     (markdown:edit! body)
     (check 'markdown-source-return (list (eq? (seat:current-buffer-mirror) b) (seat:point) (store:revision document))
       (list #t '(2 . 0) (car before)))
     (seat:buffer-name-set! b "renamed.md")
     (check 'markdown-source-identity-retains-tool (markdown:view!) root)
     (pump!)
     (let ([saved (state body)])
       (kernel:retract-module! 'markdown-test)
       (parameterize ([kernel:registering-module 'markdown-test]) (markdown:init!))
       (test:await 'markdown-reload (lambda () (pump!) (equal? (state body) saved)))
       (check 'markdown-definition-reload-keeps-selection (state body) saved))
     ;; Source-relative links are resolved through the explicit host, and a
     ;; linked Markdown document gets a new independently owned composition.
     (define directory (format "/tmp/e-markdown-host-~a" (get-process-id)))
     (mkdir directory)
     (define path (string-append directory "/child.md"))
     (file:write! path '#("# Child") #t)
     (seat:buffer-file-set! b (string-append directory "/notes.md"))
     (markdown:open-link! (widget:descendant root 'app) document "child.md")
     (define linked (seat:buffer-fact (seat:current-buffer-mirror) 'widget-id #f))
     (define linked-body (widget:descendant linked 'app 'text))
     (test:await 'markdown-linked-page (lambda () (pump!) (view:basis (interaction:snapshot linked-body))))
     (check 'markdown-relative-link-opens-presentation
       (list (not (equal? linked root))
         (view:kind (interaction:snapshot linked-body)) (store:property (store:find-file path) 'file))
       (list #t 'markdown path))
     (markdown:edit! linked-body)
     (check 'markdown-linked-source-return (seat:buffer-file (seat:current-buffer-mirror)) path)
     (delete-file path) (delete-directory directory)
     ;; Retirement leaves an explicit unavailable presentation and cannot
     ;; reopen the removed source through a stale command.
     (window:show-widget! w root)
     (pump!)
     (store:delete! head:ui-actor document)
     (test:await 'markdown-retired-source
       (lambda () (pump!) (test:raises? (lambda () (markdown:edit! body)))))
     (check 'markdown-source-retirement-refuses-return (test:raises? (lambda () (markdown:edit! body))) #t)
     (test:finish! 'markdown-view)))
