;; The actual head cache runs against an indexed synthetic base provider.
(let ()
  (define actor head:ui-actor)
  (define reads 0)
  (define hold? #f)
  (define entered (test:gate))
  (define release (test:gate))
  (define wide (make-string 65500 #\w))
  (define (field r k) (cdr (assq k r)))
  (define (ready id)
    (test:await 'range-summary (lambda () (eq? 'ready (field (field (collection:summary id) 'value) 'status))))
    (collection:summary id))
  (define (generation s) (field (field s 'value) 'generation))
  (define (page id g start count)
    (test:await 'range-page (lambda () (range:pump!) (eq? (car (range:read id g start count '(name))) 'ready)))
    (range:read id g start count '(name)))
  (model:register-kind! 'range-fixture 1 integer?)
  (collection:register! 'range-fixture 1
    (lambda (r query cancelled? publish!)
      (let ([count (field r 'value)] [revision (field r 'revision)])
        (publish! (collection:make-result '((name "Name" string) (size "Size" integer)) count
                    (lambda (i)
                      (set! reads (+ 1 reads))
                      (when hold? (set! hold? #f) (entered #t) (test:await 'release-range release))
                      (list i (list (cons 'name (if (< count 1000) wide (if (= i 1) "a界bc" (format "~a:~a" revision i)))) (cons 'size i))
                        (if (< count 1000) '()
                          (append (list (cons 'selectable (odd? i)) '(depth . 1))
                            (if (= i 1) '((matches (name 0 2)) (creation . file)) '())))))
                    (lambda (key) (and (integer? key) (<= 0 key) (< key count) key))
                    (lambda (at direction offset)
                      (and (> count 0)
                        (let* ([sign (if (eq? direction 'forward) 1 -1)]
                               [step (if (< count 1000) 1 2)] [first (if (or (< count 1000) (odd? at)) at (+ at sign))])
                          (min (- count (if (or (< count 1000) (even? count)) 1 2)) (max (if (< count 1000) 0 1) (+ first (* step sign offset)))))))
                    (if (< count 1000) '() '((default 3)))) #f))))
  (let* ([source (model:create! actor 'range-fixture 1 'session 'transient '() 10000000)]
         [query (collection:create! actor source "" '() 'transient)] [s (ready query)] [g (generation s)]
         [a (range:acquire! query void)] [b (range:acquire! query void)])
    (range:request! a g 0 32 '(name) '())
    (range:request! b g 16 32 '(name) '())
    (page query g 0 48)
    (let ([before reads])
      (range:read query g 3 20 '(name)) (range:read query g 18 4 '(name)) (range:pump!)
      (test:check 'range-overlapping-views-share-a-page-and-warm-reads-do-no-work
        (list before reads (list-ref (range:locate query g 30) 3)) '(64 64 30)))
    (table:register-presentation! 'range-fixture 1
      (list (list 'name 1 'text
              (lambda (value attributes)
                ;; Quotes are presentation only; matches refer to raw text.
                (cons (string-append "\"" value "\"")
                  (map (lambda (span) (list (+ 1 (cadr span)) (+ 1 (caddr span)) 'mark))
                    (cond [(assq 'matches attributes) => cdr] [else '()])))))))
    (let* ([table (table:create! actor query '(size name) '((identity . name) (presentation range-fixture 1)))] [before reads])
      (define (show width)
        (let ([frame (widget:prepare! table width 10)]) (widget:present! (list (list frame 0 0))) frame))
      (define (selection) (field (view:state (interaction:snapshot table)) 'selection))
      (define (await-key key)
        (test:await (list 'indexed-table key)
          (lambda () (show 300) (widget:pump!) (range:pump!) (let ([s (selection)]) (and s (equal? (caddr s) key))))))
      (define (body frame) (car (widget:frame-children (cadr (widget:frame-children frame)))))
      (define (face frame row char) (vector-ref (widget:frame-styles frame row (list-ref (widget:frame-lines frame) row)) char))
      (widget:mount! table 'ten-million-rows)
      (await-key 3)
      (table:move! table 'first) (await-key 1)
      (let* ([frame (show 5)] [line (cadr (widget:frame-lines (body frame)))])
        (test:check 'table-identity-is-not-first-and-clipped-matches-avoid-quotes-and-ellipsis
          (list line (map (lambda (i) (face frame 2 i)) '(0 1 2 3))
            (car (widget:frame-lines (car (widget:frame-children frame)))))
          '(" \"a… " (candidate (candidate italic) (candidate mark italic) candidate) "Name ")))
      (let* ([frame (show 300)] [line (cadr (widget:frame-lines (body frame)))] [fresh reads])
        (for-each show '(5 300 80 300))
        (test:check 'table-wide-reopen-restores-metadata-with-bounded-formatting-and-view-count
          (list (substring line 0 12) (length (view:tree table)) (= reads fresh) (< (- reads before) 300))
          '("           1" 4 #t #t)))
      (let ([before (selection)])
        (widget:pointer! '(pointer press primary ()) 2 1)
        (test:check 'table-sections-cannot-be-selected-by-pointer (selection) before))
      (table:move! table 'next) (await-key 3)
      (table:move! table 'page-next) (await-key 13)
      (let ([before reads])
        (table:move! table 'last) (await-key 9999999)
        (test:check 'table-indexed-section-navigation-does-not-walk-to-the-end (< (- reads before) 300) #t))
      (widget:unmount! table))
    (set! hold? #t)
    (range:request! a g 64 32 '(name) '())
    (range:pump!) (test:await 'range-held entered)
    (let ([r (model:snapshot source)])
      (model:commit! actor (list (list source (field r 'revision) '() 10000001))))
    (let* ([s (ready query)] [next (generation s)])
      (range:request! a next 64 32 '(name) '())
      (range:request! b next 64 16 '(name) '())
      (release #t)
      (let ([p (page query next 64 32)])
        (test:check 'range-late-old-generation-cannot-replace-current-pages
          (list (cadr p) (caddr (car (caddr (car (list-ref p 4)))))
            (range:read query g 64 1 '(name)))
          (list next "1:64" '(pending)))))
    (range:release! a) (range:release! b)
    (test:check 'range-last-release-ends-local-read-ownership
      (test:raises? (lambda () (range:summary query))) #t))
  (let* ([source (model:create! actor 'range-fixture 1 'session 'transient '() 9)]
         [query (collection:create! actor source "" '() 'transient)] [s (ready query)] [g (generation s)]
         [token (range:acquire! query void)])
    (range:request! token g 0 9 '(name) '())
    (test:check 'range-short-byte-limited-page-fetches-its-remainder
      (length (list-ref (page query g 0 9) 4)) 9)
    (range:release! token))
  (let* ([source (model:create! actor 'range-fixture 1 'session 'transient '() 160)]
         [query (collection:create! actor source "" '() 'transient)] [s (ready query)] [g (generation s)]
         [token (range:acquire! query void)])
    (range:request! token g 0 160 '(name) '())
    (test:await 'range-bounded-overload
      (lambda () (range:pump!) (eq? (car (range:read query g 0 160 '(name))) 'unavailable)))
    (let ([before reads])
      (range:pump!) (range:pump!)
      (test:check 'range-demand-over-budget-is-explicit-without-refetching
        (list (range:read query g 0 160 '(name)) reads) (list '(unavailable cache-budget) before)))
    (range:request! token g 0 1 '(name) '())
    (page query g 0 1)
    (range:release! token)))
