(let ()
  (define actor head:ui-actor)
  (define source (store:create! actor "Nested search" '("alpha ALPHA" "tail")))
  (define other-source (store:create! actor "Other search" '("omega")))
  (define target (create-view! actor source '()))
  (define other (create-view! actor other-source '()))
  (define root (view:create! actor #f 'search-fixture 1 '() '()))
  (define outcome #f)
  (define (get r k) (cdr (assq k r)))
  (define (point id) (car (view:state (interaction:snapshot id))))
  (define (show!) (widget:present! (list (list (widget:prepare! root 60 8) 0 0))))
  (define (pump!) (widget:pump!) (show!))
  (define (at id p) (test:await 'search-caret (lambda () (pump!) (equal? (point id) p))))
  (search-control:init!)
  (widget:register! 'search-fixture 1
    (append (layout:container 'y) (list (cons 'actions (list (cons 'finished (lambda (id . args) (set! outcome args))))))))
  (view:arrange! actor (list (list root 0 (list (list 'editor target '(grow 1)) (list 'other other '(grow 1))) '())) '())
  (widget:mount! root 'nested-search) (pump!)
  (let* ([search (search-control:create! target 'smart "alpha" (list (list 'finished root 'finished '())))]
         [request (view:source (view:snapshot search))])
    (interaction:flush!)
    (widget:arrange! (list (list root (get (model:snapshot root) 'revision)
                             (list (list 'editor target '(grow 1)) (list 'other other '(grow 1)) (list 'search search 'fit)) '())))
    (pump!)
    (let ([input (widget:descendant search 'entry)])
      (widget:focus! root input) (show!)
      (routing:input! root '(text "alpha" keyboard))
      (at target '(0 . 5))
      (check 'nested-search-entry-moves-explicit-editor (point other) '(0 . 0))
      (routing:input! root '(key "C-s" #f))
      (at target '(0 . 11))
      (check 'search-repeat-wrap-and-smart-case (point target) '(0 . 11))
      (routing:input! root '(key "M-c" #f))
      (at target '(0 . 5))
      (routing:input! root '(key "BACKSPACE" #f))
      (at target '(0 . 4))
      (check 'search-case-toggle-and-backspace (point target) '(0 . 4))
      (entry:set-text! input "tail") (widget:pump!)
      (move! target '(0 . 0)) (show!)
      (test:await 'search-late-result
        (lambda () (pump!)
          (let ([v (get (model:snapshot request) 'value)])
            (and (eq? (get v 'status) 'ready) (string=? (get (get v 'request) 'needle) "tail")))))
      (check 'search-result-does-not-overwrite-later-caret (point target) '(0 . 0))
      (search-control:retarget! search other)
      (entry:set-text! input "omega")
      (at other '(0 . 5))
      (check 'search-retarget-moves-only-new-receiver (point target) '(0 . 0))
      (store:edit! '(agent search-fixture) source 0 (text:make-span 0 0 0 0) '("x") #f)
      (pump!)
      (search-control:cancel! search)
      (check 'search-cancel-rebases-origin-without-undoing-source
        (list outcome (point target) (store:line source 0)) (list (list #f target "omega") '(0 . 1) "xalpha ALPHA"))
      (head:run-deferred!) (pump!)
      (test:await 'search-closed (lambda () (head:run-deferred!) (not (model:snapshot request))))
      (check 'search-close-retires-request-views-and-draft
        (list (model:snapshot search) (model:snapshot input) (store:exists? source)) '(#f #f #t))))
  (widget:unmount! root) (store:delete! actor source) (store:delete! actor other-source))
