(let ()
  (import (prefix (apps search) search:))
  (define actor head:ui-actor)
  (define source (store:create! actor "Nested search" '("alpha ALPHA" "tail")))
  (define other-source (store:create! actor "Other search" '("omega")))
  (define target (edit:create-view! actor source '()))
  (define other (edit:create-view! actor other-source '()))
  (define root (view:create! actor #f 'search-fixture 1 '() '()))
  (define outcome #f)
  (define (get r k) (cdr (assq k r)))
  (define (point id) (car (view:state (interaction:snapshot id))))
  (define (show!) (widget:present! (list (list (widget:prepare! root 60 8) 0 0))))
  (define (pump!) (widget:pump!) (show!))
  (define (at id p) (test:await 'search-caret (lambda () (pump!) (equal? (point id) p))))
  (kernel:load-module! "search")
  (widget:register! 'search-fixture 1
    (append (layout:container 'y) (list (cons 'actions (list (cons 'finished (lambda (id . args) (set! outcome args))))))))
  (view:arrange! actor (list (list root 0 (list (list 'editor target '(grow 1)) (list 'other other '(grow 1))) '())) '())
  (widget:mount! root 'nested-search) (pump!)
  (let* ([search (search-control:create! target 'smart "alpha" (list (list 'finished root 'finished '())))]
         [request (view:source (view:snapshot search))])
    (interaction:flush!)
    (widget:arrange! (list (list root (get (model:snapshot root) 'revision)
                             (list (list 'editor target '(grow 1)) (list 'other other '(grow 1)) (list 'search search 'fit)) '())))
    (pump!)
    (let ([input (widget:descendant search 'entry)])
      (widget:focus! root input) (show!)
      (routing:input! root '(text "alpha" keyboard))
      (at target '(0 . 5))
      (check 'nested-search-entry-moves-explicit-editor (point other) '(0 . 0))
      (routing:input! root '(key "C-s" #f))
      (at target '(0 . 11))
      (check 'search-repeat-wrap-and-smart-case (point target) '(0 . 11))
      (routing:input! root '(key "M-c" #f))
      (at target '(0 . 5))
      (routing:input! root '(key "BACKSPACE" #f))
      (at target '(0 . 4))
      (check 'search-case-toggle-and-backspace (point target) '(0 . 4))
      (entry:set-text! input "tail") (widget:pump!)
      (edit:move! target '(0 . 0)) (show!)
      (test:await 'search-late-result
        (lambda () (pump!)
          (let ([v (get (model:snapshot request) 'value)])
            (and (eq? (get v 'status) 'ready) (string=? (get (get v 'request) 'needle) "tail")))))
      (check 'search-result-does-not-overwrite-later-caret (point target) '(0 . 0))
      (search-control:retarget! search other)
      (entry:set-text! input "omega")
      (at other '(0 . 5))
      (check 'search-retarget-moves-only-new-receiver (point target) '(0 . 0))
      (store:edit! '(agent search-fixture) source 0 (text:make-span 0 0 0 0) '("x") #f)
      (pump!)
      (search-control:cancel! search)
      (check 'search-cancel-rebases-origin-without-undoing-source
        (list outcome (point target) (store:line source 0)) (list (list #f target "omega") '(0 . 1) "xalpha ALPHA"))
      (head:run-deferred!) (pump!)
      (test:await 'search-closed (lambda () (head:run-deferred!) (not (model:snapshot request))))
      (check 'search-close-retires-request-views-and-draft
        (list (model:snapshot search) (model:snapshot input) (store:exists? source)) '(#f #f #t))))
  (widget:focus! root other)
  ;; Publish a ready preview before the controller has adopted its hit. The
  ;; status can already show the first match; repeat must advance from it.
  (let* ([preview (search-control:create-preview! target 'fold '() root)]
         [query (view:source (view:snapshot preview))])
    (interaction:flush!)
    (widget:arrange! (list (list root (model:revision root)
                             (append (view:children (interaction:snapshot root)) (list (list 'preview preview 'fit))) '())))
    (pump!)
    (search-control:set-needle! preview "alpha") (pump!)
    (test:await 'preview-first-result
      (lambda () (let ([v (get (model:snapshot query) 'value)])
                   (and (eq? (get v 'status) 'ready) (equal? (get (get v 'request) 'needle) "alpha")
                     (equal? (get (get v 'result) 'count) 2)))))
    (show!)
    (let ([generation (get (get (model:snapshot query) 'value) 'generation)])
      (search-control:repeat! preview) (pump!)
      (test:await 'preview-repeated-result
        (lambda () (let ([v (get (model:snapshot query) 'value)])
                     (and (eq? (get v 'status) 'ready) (> (get v 'generation) generation)
                       (get (get v 'result) 'count)))))
      (check 'preview-repeat-adopts-the-ready-hit-before-requesting-the-next
        (get (get (get (model:snapshot query) 'value) 'result) 'hit) '(0 . 7)))
    (pump!)
    (for-each
      (lambda (directions)
        (let ([generation (get (get (model:snapshot query) 'value) 'generation)])
          (for-each (lambda (direction) (search-control:repeat! preview direction)) directions)
          (test:await 'preview-repeat-burst
            (lambda ()
              (pump!)
              (let ([v (get (model:snapshot query) 'value)])
                (and (eq? (get v 'status) 'ready)
                  (= (get v 'generation) (+ generation (length directions)))
                  (get (get v 'result) 'count)
                  (null? (caddr (view:state (interaction:snapshot preview))))))))
          (check 'preview-preserves-batched-repeat-order
            (get (get (get (model:snapshot query) 'value) 'result) 'hit) '(0 . 7))))
      '((next next) (previous next) (next previous)))
    (search-control:repeat! preview)
    (search-control:toggle-case! preview)
    (test:await 'preview-case-discards-obsolete-navigation
      (lambda () (pump!)
        (let ([v (get (model:snapshot query) 'value)])
          (and (eq? (get v 'status) 'ready) (not (get (get v 'request) 'fold?))
            (equal? (get (get v 'result) 'count) 1)))))
    (check 'preview-case-change-fences-queued-repeats
      (get (get (get (model:snapshot query) 'value) 'result) 'hit) '(0 . 1))
    (view:retire! actor preview (model:revision preview))
    (pump!) (head:run-deferred!))
  (edit:select! target '(0 . 1) '(0 . 6))
  (check 'replacement-captures-the-explicit-reversed-selection
    (list (search:count target "alpha") (search:count target "ALPHA")
      (search:replace! target "alpha" "β") (store:line source 0) (widget:focused root))
    (list 1 0 1 "xβ ALPHA" other))
  (edit:undo! target)
  (edit:set-mark! target #f)
  (check 'unmarked-replacement-spans-the-document-as-one-undo-step
    (list (search:count target "a") (search:replace! target "a" "Ω")
      (store:line source 0) (store:line source 1)
      (begin (edit:undo! target) (list (store:line source 0) (store:line source 1)))
      (store:line other-source 0))
    '(3 3 "xΩlphΩ ALPHA" "tΩil" ("xalpha ALPHA" "tail") "omega"))
  (widget:unmount! root) (store:delete! actor source) (store:delete! actor other-source))

(let ()
  (import (prefix (apps search) search:) (prefix (service window) window:)
          (prefix (head window-control) window-control:))
  (actor:call-as head:ui-actor
    (lambda ()
      (let* ([manager (window:create-manager! #f)] [first (window:current manager)]
             [second (window:split! manager first 'right)]
             [a (store:create! head:ui-actor "Search pane A" '("alpha tail"))]
             [b (store:create! head:ui-actor "Search pane B" '("beta alpha"))]
             [editor (window:open-document! manager first a)]
             [other (window:open-document! manager second b)])
        (define (show!)
          (widget:pump!) (head:run-deferred!)
          (widget:present! (list (list (widget:prepare! manager 60 8) 0 0))))
        (define (point id) (car (view:state (interaction:snapshot id))))
        (define (key! key) (routing:input! manager (list 'key key #f)) (show!))
        (define (at id p) (test:await 'composed-search-caret (lambda () (show!) (equal? (point id) p))))
        (widget:mount! manager 'composed-search) (show!)
        (widget:focus! manager editor) (show!)
        (key! "C-s")
        (let* ([panel (widget:descendant first 'search)] [search (widget:descendant panel 'search)]
               [input (widget:descendant search 'entry)] [query (view:source (interaction:snapshot search))])
          (routing:input! manager '(text "alpha" keyboard)) (at editor '(0 . 5))
          (check 'composed-search-is-an-ordinary-child-with-explicit-focus
            (list (view:parent (interaction:snapshot panel)) (widget:focused manager) (point other))
            (list first input '(0 . 0)))
          (window-control:select! second) (show!) (at other '(0 . 10))
          (check 'composed-search-retargets-and-moves-with-window-focus
            (list (view:parent (interaction:snapshot panel)) (widget:focused manager)
              (car (view:state (interaction:snapshot search))) (point editor))
            (list second input other '(0 . 5)))
          (key! "C-g")
          (test:await 'composed-search-closed (lambda () (show!) (not (model:snapshot query))))
          (check 'composed-search-cancel-restores-origin-and-releases-only-the-search
            (list (widget:focused manager) (point editor) (point other)
              (model:snapshot panel) (store:exists? a) (store:exists? b))
            (list editor '(0 . 0) '(0 . 10) #f #t #t)))
        (key! "C-s") (key! "C-s") (at editor '(0 . 5))
        (key! "RIGHT")
        (check 'composed-search-arrow-accepts-and-uses-normal-editor-navigation
          (list (widget:focused manager) (point editor) (assq 'search (view:children (interaction:snapshot first))))
          (list editor '(0 . 6) #f))
        (key! "C-s")
        (let ([query (view:source (interaction:snapshot (widget:descendant first 'search 'search)))])
          (window-control:close! first) (show!)
          (test:await 'closed-search-pane-releases-query (lambda () (show!) (not (model:snapshot query))))
          (check 'closing-search-pane-preserves-both-documents
            (list (window:list manager) (store:exists? a) (store:exists? b)) (list (list second) #t #t)))
        (widget:unmount! manager)
        (view:retire! head:ui-actor manager (model:revision manager))
        (store:delete! head:ui-actor a) (store:delete! head:ui-actor b)))))
