;; Shared selection, fitting and shown-frame interaction across both forms.
(let ()
  (define actor head:ui-actor)
  (define (get xs k) (cdr (assq k xs)))
  (define (contains? text needle) (and (string:search text needle 0 (string-length text)) #t))
  (define activated '())
  (define (selection id) (get (view:state (interaction:snapshot id)) 'selection))
  (define (key id) (let ([s (selection id)]) (and s (caddr s))))
  (define source (collection:create-source! actor '((name "Name" string) (size "Size" integer) (flag "Flag" boolean))
                   (list->vector (map (lambda (i) (list i (list (cons 'name (format "path/界/~3,'0d" i)) (cons 'size (- 200 i)) (cons 'flag (even? i))) '())) (iota 200))) 'transient))
  (define query (collection:create! actor source "" '() 'transient))
  (define table (table:create! actor query '(name size flag)))
  (define list-view (table:create! actor query '(name) 'list))
  (define target (view:create! actor #f 'table-target 1 '() '()))
  (define root (view:create! actor #f 'row 1 '() '()))
  (define (show! width)
    (let ([f (widget:prepare! root width 6)]) (widget:present! (list (list f 0 0))) f))
  (define (pump!) (range:pump!) (widget:pump!) (show! 80))
  (define (await-key id expected)
    (test:await 'table-row (lambda () (pump!) (equal? expected (key id)))))
  (table:init!)
  (widget:register! 'table-target 1 (list (cons 'actions (list (cons 'open (lambda (id selection basis) (set! activated (cons selection activated))))))))
  (let ([d (view:snapshot table)])
    (view:arrange! actor (list (list table 1 (view:children d) (append (view:options d) (list (list 'commands (list 'activate target 'open '())))))) '()))
  (view:arrange! actor (list (list root 0 (list (list 'table table '(grow 1)) (list 'list list-view '(grow 1)) (list 'target target 'fit)) '())) '())
  (widget:mount! root 'table-fixture)
  (await-key table 0) (await-key list-view 0)
  (check 'table-and-list-share-data-not-selection
    (begin (table:move! table 'next) (list (key table) (key list-view))) '(1 0))
  (table:select! table 199)
  (check 'table-pending-navigation-cannot-expose-or-activate-old-row
    (list (selection table) (refused? (lambda () (table:activate! table)))) '(#f #t))
  (table:move! table 'previous)
  (await-key table 0)
  (table:select! table 199) (await-key table 199)
  (table:activate! table)
  (check 'table-activation-delivers-stable-row-reference (cadar activated) (get (get (collection:summary query) 'value) 'generation))
  (table:sort-by! table '((size ascending)))
  (test:await 'table-sort (lambda () (pump!)
                            (let* ([v (get (collection:summary query) 'value)] [s (selection table)])
                              (and (eq? (get v 'status) 'ready) s (= (cadr s) (get v 'generation))))))
  (check 'table-sort-keeps-key (key table) 199)
  (table:move! table 'next) (await-key table 198)
  (let* ([frame (show! 600)] [left (car (widget:frame-children frame))] [heading (car (widget:frame-children left))])
    (check 'table-wide-layout-retains-real-metadata
      (and (> (string-length (car (widget:frame-lines heading))) 290)
        (contains? (car (widget:frame-lines heading)) "Size")) #t))
  (show! 8) (show! 600)
  (check 'table-reopen-and-resize-do-not-lose-metadata
    (contains? (car (widget:frame-lines (car (widget:frame-children (widget:prepared root))))) "Size") #t)
  (table:toggle-sort! table 'size)
  (table:toggle-sort! table 'name)
  (check 'table-sort-priority-and-cycle
    (get (get (collection:summary query) 'value) 'sort) '((size descending) (name ascending)))
  (test:await 'table-resort (lambda () (pump!) (eq? (get (get (collection:summary query) 'value) 'status) 'ready)))
  (table:move! table 'first) (await-key table 0) (show! 80)
  (test:await 'table-reveal-after-uncached-rank
    (lambda () (pump!)
      (let* ([scroll (cadr (assq 'body (view:children (interaction:snapshot table))))]
             [anchor (view:state (interaction:snapshot scroll))])
        (and (list? anchor) (= (length anchor) 3) (equal? (caddr anchor) 0)))))
  (let ([before (selection table)])
    (widget:pointer! '(scroll 0 70 line) 2 2)
    (show! 80)
    (test:await 'table-scroll-page
      (lambda () (pump!)
        (let* ([d (interaction:snapshot table)] [scroll (cadr (assq 'body (view:children d)))]
               [anchor (view:state (interaction:snapshot scroll))])
          (and (list? anchor) (= (length anchor) 3) (equal? (caddr anchor) 70)))))
    (check 'table-wheel-scrolls-without-changing-selection (selection table) before))
  (let ([before (length activated)])
    (show! 80)
    (widget:pointer! '(pointer press primary ()) 2 2)
    (check 'table-row-click-uses-shown-key-and-explicit-command
      (list (key table) (- (length activated) before)) '(71 1)))
  (show! 80)
  (let ([before (length activated)] [r (collection:summary query)])
    (collection:configure! actor query (get r 'revision) '((sort (name descending))))
    (test:await 'table-stale-shown (lambda () (eq? (get (get (collection:summary query) 'value) 'status) 'ready)))
    (widget:pointer! '(pointer press primary ()) 2 2)
    (check 'table-old-shown-generation-cannot-activate (length activated) before))
  (table:set-columns! table '(name flag))
  (check 'table-columns-are-a-view-preference (get (view:options (interaction:snapshot table)) 'columns) '(name flag))
  (let ([r (collection:summary query)])
    (collection:configure! actor query (get r 'revision) '((filter . "000"))))
  (await-key table 0)
  (check 'table-disappearing-selection-falls-back-to-first-survivor (key list-view) 0)
  (let* ([r (model:snapshot source)] [value (get r 'value)] [rows (vector-copy (cadr value))]
         [old (vector-ref rows 0)])
    (vector-set! rows 0 (cons #f (cdr old)))
    (model:commit! actor (list (list source (get r 'revision) '() (list (car value) rows)))))
  (test:await 'table-false-key
    (lambda () (pump!) (let ([s (selection table)]) (and s (eq? (caddr s) #f)))))
  (table:activate! table)
  (check 'table-false-is-a-real-row-key (caddar activated) #f)
  (let ([r (collection:summary query)])
    (collection:configure! actor query (get r 'revision) '((filter . "absent"))))
  (test:await 'table-empty (lambda () (pump!) (not (selection table))))
  (check 'table-empty-result-cannot-activate (refused? (lambda () (table:activate! table))) #t)
  (widget:prepare! root 0 0)
  (widget:unmount! root) (widget:invalidate!))
