;; Shared selection, fitting and shown-frame interaction across both forms.
(let ()
  (define actor head:ui-actor)
  (define (get xs k) (cdr (assq k xs)))
  (define (contains? text needle) (and (string:search text needle 0 (string-length text)) #t))
  (define activated '())
  (define (selection id) (get (view:state (interaction:snapshot id)) 'selection))
  (define (key id) (let ([s (selection id)]) (and s (caddr s))))
  (define source (collection:create-source! actor '((name "Name" string) (size "Size" integer) (flag "Flag" boolean))
                   (list->vector (map (lambda (i) (list i (list (cons 'name (format "path/界/~3,'0d" i)) (cons 'size (- 200 i)) (cons 'flag (even? i))) '())) (iota 200))) 'transient))
  (define query (collection:create! actor source "" '() 'transient))
  (define table (table:create! actor query '(name size flag)))
  (define list-view (table:create! actor query '(name) '((kind . list))))
  (define target (view:create! actor #f 'table-target 1 '() '()))
  (define root (view:create! actor #f 'row 1 '() '()))
  (define height 6)
  (define (show! width)
    (let ([f (widget:prepare! root width height)]) (widget:present! (list (list f 0 0))) f))
  (define (face frame row column)
    (vector-ref (widget:frame-styles frame row (list-ref (widget:frame-lines frame) row)) column))
  (define (pump!) (range:pump!) (widget:pump!) (show! 80))
  (define (await-key id expected)
    (test:await (list 'table-row expected) (lambda () (pump!) (equal? expected (key id)))))
  (table:init!)
  (widget:register! 'table-target 1 (list (cons 'actions (list (cons 'open (lambda (id selection basis) (set! activated (cons selection activated))))))))
  (let ([d (view:snapshot table)])
    (view:arrange! actor (list (list table 1 (view:children d) (append (view:options d) (list (list 'commands (list 'activate target 'open '())))))) '()))
  (view:arrange! actor (list (list root 0 (list (list 'table table '(grow 1)) (list 'list list-view '(grow 1)) (list 'target target 'fit)) '())) '())
  (widget:mount! root 'table-fixture)
  (await-key table 0) (await-key list-view 0)
  (check 'table-and-list-share-data-not-selection
    (begin (table:move! table 'next) (list (key table) (key list-view))) '(1 0))
  (show! 80)
  (let ([before (view:state (interaction:snapshot table))] [focus (widget:focused root)])
    (widget:pointer! '(pointer move none ()) 2 3)
    (let ([f (show! 80)])
      (check 'table-hover-is-one-local-candidate-without-focus-or-selection-publication
        (list (map (lambda (row) (face f row 0)) '(1 2 3))
          (view:state (interaction:snapshot table)) (widget:focused root))
        (list '(#f #f candidate-hover) before focus)))
    (table:move! table 'next)
    (let ([f (show! 80)])
      (check 'table-keys-continue-from-hover-and-restore-keyboard-style
        (list (key table) (face f 3 0) (face f 4 0)) '(3 #f candidate)))
    (widget:pointer! '(pointer move none ()) 2 3)
    (table:invoke! table)
    (check 'table-enter-adopts-the-hovered-row (list (key table) (caddar activated)) '(2 2)))
  (widget:pointer! '(pointer move none ()) 2 0)
  (let ([f (show! 80)])
    (check 'table-heading-hover-retains-its-background
      (list (face f 0 0) (face f 0 39) (face f 3 0)) '((header hover) header candidate)))
  (widget:set-active! root #f)
  (widget:pointer! '(pointer move none ()) 2 4)
  (let* ([f (show! 80)] [hovered (list (face f 3 0) (face f 4 0))])
    (widget:pointer! '(pointer move none ()) 99 99)
    (let ([inactive (face (show! 80) 3 0)])
      (widget:set-active! root #t)
      (check 'table-leave-and-host-focus-restore-only-the-keyboard-candidate
        (list hovered inactive (face (show! 80) 3 0) (key table))
        '((#f candidate-hover) #f candidate 2))))
  (table:select! table 1)
  (table:select! table 199)
  (check 'table-pending-selection-cannot-expose-or-destructively-activate-old-row
    (list (selection table) (refused? (lambda () (table:invoke! table 'trash)))) '(#f #t))
  (table:move! table 'previous)
  (await-key table 0)
  (table:select! table 199)
  (table:invoke! table)
  (test:await 'table-explicit-selection-reveals-uncached-row
    (lambda () (pump!) (contains? (string:join (widget:frame-lines (widget:prepared root)) "\n") "199")))
  (check 'table-activation-delivers-stable-row-reference (cadar activated) (get (get (collection:summary query) 'value) 'generation))
  (table:sort-by! table '((size ascending)))
  (test:await 'table-sort (lambda () (pump!)
                            (let* ([v (get (collection:summary query) 'value)] [s (selection table)])
                              (and (eq? (get v 'status) 'ready) s (= (cadr s) (get v 'generation))))))
  (check 'table-sort-keeps-key (key table) 199)
  (table:move! table 'next) (await-key table 198)
  (let* ([frame (show! 600)] [left (car (widget:frame-children frame))] [heading (car (widget:frame-children left))])
    (check 'table-wide-layout-retains-real-metadata
      (and (> (string-length (car (widget:frame-lines heading))) 290)
        (contains? (car (widget:frame-lines heading)) "Size")) #t))
  (show! 8) (show! 600)
  (check 'table-reopen-and-resize-do-not-lose-metadata
    (contains? (car (widget:frame-lines (car (widget:frame-children (widget:prepared root))))) "Size") #t)
  (table:toggle-sort! table 'size)
  (table:toggle-sort! table 'name)
  (check 'table-sort-priority-and-cycle
    (get (get (collection:summary query) 'value) 'sort) '((size descending) (name ascending)))
  (test:await 'table-resort (lambda () (pump!) (eq? (get (get (collection:summary query) 'value) 'status) 'ready)))
  (table:move! table 'first) (await-key table 0) (show! 80)
  (test:await 'table-reveal-after-uncached-rank
    (lambda () (pump!)
      (let* ([scroll (cadr (assq 'body (view:children (interaction:snapshot table))))]
             [anchor (view:state (interaction:snapshot scroll))])
        (and (list? anchor) (= (length anchor) 3) (equal? (caddr anchor) 0)))))
  (let ([before (selection table)])
    (widget:pointer! '(scroll 0 70 line) 2 2)
    (show! 80)
    (test:await 'table-scroll-page
      (lambda () (pump!)
        (let* ([d (interaction:snapshot table)] [scroll (cadr (assq 'body (view:children d)))]
               [anchor (view:state (interaction:snapshot scroll))])
          (and (list? anchor) (= (length anchor) 3) (equal? (caddr anchor) 70)))))
    (check 'table-wheel-scrolls-without-changing-selection (selection table) before))
  (let ([before (length activated)])
    (show! 80)
    (widget:pointer! '(pointer move none ()) 2 2)
    (let ([f (show! 80)])
      (check 'table-hover-marks-the-shown-scrolled-row
        (map (lambda (row) (face f row 0)) '(1 2 3))
        '(#f candidate-hover #f)))
    (widget:pointer! '(pointer press primary ()) 2 2)
    (check 'table-row-click-uses-shown-key-and-explicit-command
      (list (key table) (- (length activated) before)) '(71 1)))
  (show! 80)
  ;; Streaming results insert rows before a scrolled viewport. Summary,
  ;; anchor rank and page arrive separately; every intermediate frame must
  ;; keep the same visible rows, including across a metadata-only refresh.
  ;; A resize can expose cached rows before service has retained that slice.
  (set! height 8)
  (let* ([body (lambda (f) (car (widget:frame-children (cadr (widget:frame-children (car (widget:frame-children f)))))))]
         [before (widget:frame-lines (body (show! 80)))] [stable? #t])
    (for-each
      (lambda (insert?)
        (let* ([r (model:snapshot source)] [value (get r 'value)]
               [rows (if insert?
                       (list->vector
                         (append (vector->list (cadr value))
                           (map (lambda (i) (list (- i) (list (cons 'name (format "added/~a" i)) (cons 'size (+ 200 i)) '(flag . #f)) '()))
                             (map add1 (iota 80)))))
                       (cadr value))])
          (model:commit! actor (list (list source (get r 'revision) '() (list (car value) rows))))
          (test:await 'table-streamed-insertion-ready
            (lambda () (eq? (get (get (collection:summary query) 'value) 'status) 'ready)))
          (let ([g (get (get (collection:summary query) 'value) 'generation)])
            (test:await 'table-streamed-viewport
              (lambda ()
                (let* ([f (body (pump!))] [s (selection table)])
                  (set! stable? (and stable? (equal? before (widget:frame-lines f))))
                  (and s (= (cadr s) g) (= (cadr (widget:frame-rect f)) -149)))))))) '(#t #f))
    (check 'table-streamed-rows-and-anchor-adopt-together-without-jumps stable? #t))
  (set! height 6)
  (let ([before (length activated)] [r (collection:summary query)])
    (collection:configure! actor query (get r 'revision) '((sort (name descending))))
    (test:await 'table-stale-shown (lambda () (eq? (get (get (collection:summary query) 'value) 'status) 'ready)))
    (widget:pointer! '(pointer press primary ()) 2 2)
    (check 'table-old-shown-generation-cannot-activate (length activated) before))
  (table:set-columns! table '(name flag))
  (check 'table-columns-are-a-view-preference (get (view:options (interaction:snapshot table)) 'columns) '(name flag))
  (let ([r (collection:summary query)])
    (collection:configure! actor query (get r 'revision) '((filter . "000"))))
  (await-key table 0)
  (check 'table-disappearing-selection-falls-back-to-first-survivor (key list-view) 0)
  (let* ([r (model:snapshot source)] [value (get r 'value)] [rows (vector-copy (cadr value))]
         [old (vector-ref rows 0)])
    (vector-set! rows 0 (cons #f (cdr old)))
    (model:commit! actor (list (list source (get r 'revision) '() (list (car value) rows)))))
  (test:await 'table-false-key
    (lambda () (pump!) (let ([s (selection table)]) (and s (eq? (caddr s) #f)))))
  (table:invoke! table)
  (check 'table-false-is-a-real-row-key (caddar activated) #f)
  (let ([r (collection:summary query)])
    (collection:configure! actor query (get r 'revision) '((filter . "absent"))))
  (test:await 'table-empty (lambda () (pump!) (not (selection table))))
  (check 'table-empty-result-cannot-activate (refused? (lambda () (table:invoke! table))) #t)
  (widget:prepare! root 0 0)
  (widget:unmount! root) (widget:invalidate!))
