;; Composition and input stay on the existing API fixture; actual PTY
;; arbitration, stale frame fencing and lifetime use terminal-process.ss.
(let* ([actor head:ui-actor] [owner '(app terminal 9876)] [messages '()]
       [source (store:create! owner "widget terminal" '("zero" "one " "two " "last")
                 `((app . ,owner) (mode . "terminal") (read-only . #t) (manages-viewport . #t)
                   (alive . #t) (size 3 4) (wrap . #f) (capture except "MOUSE-CLICK" "MOUSE-DRAG" "MOUSE-RELEASE" "WHEEL-UP" "WHEEL-DOWN")))]
       [a (terminal:create-view! actor source)] [b (terminal:create-view! actor source)]
       [root (view:create! actor #f 'row 1 '() '())] [host-count 0])
  (define (publish cursor)
    (surface:publish! source (let ([old (surface:snapshot source)]) (and old (car old)))
      (store:revision source)
      (map (lambda (row) (list row '#("31" "31" "31" "31") '#(#f #f #f #f) '())) '(0 1 2 3)) cursor '(3 4)))
  (define (show! width)
    (let ([frame (widget:prepare! root width 2)]) (widget:present! (list (list frame 0 0))) frame))
  (define (child id) (widget:descendant id 'text))
  (define (state id) (view:state (interaction:snapshot id)))
  (define (take) (let ([out (reverse messages)]) (set! messages '()) out))
  (define (key value) (dispatch:input! root (list 'key value #f) 'terminal-host-fixture))
  (terminal:init!)
  (actor:register! owner (lambda (message) (set! messages (cons message messages))))
  (publish '(3 2 #f))
  (view:arrange! actor (list (list root 0 (list (list 'a a '(grow 1)) (list 'b b '(grow 1))) '())) '())
  (widget:mount! root 'terminal-fixture)
  (let* ([frame (show! 16)] [before (map state (list (child a) (child b)))])
    (widget:pump!) (take)
    (check 'terminal-nests-with-readonly-editor-children-and-a-hidden-process-cursor
      (list (widget:caret frame) (car (widget:frame-lines (widget:prepared (child a))))
        (state a) (state b) (not (head:buffer-of-store-id source)))
      '(#f "two     " (partial #t) (partial #t) #t))
    (publish '(2 1 #t)) (widget:pump!)
    (check 'process-cursor-following-is-derived-without-view-publications
      (list (widget:caret (show! 16)) (map state (list (child a) (child b)))) (list '(1 . 1) before)))
  (keymap:bind-default! 'terminal-host-fixture "C-x F10" (lambda () (set! host-count (+ host-count 1))))
  (key "C-x") (key "F10") (key "UP") (widget:pump!)
  (check 'partial-capture-yields-chords-and-input-carries-view-and-size-once
    (list host-count (map (lambda (message) (list (car message) (cadddr message))) (take)))
    '(1 ((input "UP"))))
  (terminal:set-capture! a 'full) (key "C-x") (key "F10")
  (check 'capture-is-independent-between-two-process-views
    (list (map cadddr (take)) (map car (map state (list a b)))) '(("C-x" "F10") (full partial)))
  (let* ([spans (widget:status a #t)] [control (find (lambda (span) (keymap:call-action? (cdr span))) spans)])
    (keymap:run! (cdr control))
    (check 'terminal-status-control-is-the-explicit-public-command
      (list (car control) (car (state a)) (keymap:call-action-arguments (cdr control))) (list "●" 'partial (list a))))
  (let ([before (length (log:entries 'terminal-control:present-notices!))])
    (store:set-properties! owner source (list (list 'clipboard 7 actor "shared clipboard") '(diagnostics "fixture diagnostic")))
    (widget:pump!) (widget:pump!)
    (check 'nested-views-share-one-clipboard-and-diagnostic-delivery
      (list (copy-text) (- (length (log:entries 'terminal-control:present-notices!)) before)) '("shared clipboard" 2))
    (store:set-property! owner source 'clipboard '(8 (head "another actor") "foreign clipboard"))
    (widget:pump!)
    (check 'clipboard-replies-stay-with-their-controlling-head (copy-text) "shared clipboard"))
  (show! 16) (widget:pointer! '(scroll 0 -3 cells) 1 0)
  (check 'ordinary-wheel-leaves-following-without-sending-process-input
    (list (cadr (state a)) (take)) '(#f ()))
  (terminal:follow! a #t) (show! 16)
  (store:set-property! owner source 'capture 'all) (widget:pump!) (take)
  (let ([frame (show! 16)])
    (widget:pointer! '(pointer press primary ()) 1 0)
    (check 'captured-pointer-uses-the-shown-grid-and-view-witness
      (let* ([message (car (take))] [data (list-ref message 4)])
        (list (cadddr message) (cdr (assq 'view data)) (cdr (assq 'cell data))
          (cdr (assq 'generation data))))
      (list "MOUSE-CLICK" (list a (view:generation (interaction:snapshot a))) '(1 . 1) (car (surface:snapshot source)))))
  (widget:pointer! '(pointer release primary ()) 99 99)
  (check 'process-drag-releases-outside-the-widget (map cadddr (take)) '("MOUSE-RELEASE"))
  (widget:pointer! '(pointer press primary ()) 1 0) (take)
  (widget:cancel! root 'blur)
  (widget:pointer! '(pointer release primary ()) 99 99)
  (check 'process-drag-cancellation-releases-the-button (map cadddr (take)) '("MOUSE-RELEASE"))
  (show! 0)
  (check 'zero-allocation-refuses-terminal-input (refused? (lambda () (terminal:send! a "x"))) #t)
  (show! 16)
  (surface:withdraw! source (car (surface:snapshot source)))
  (store:set-property! owner source 'alive #f) (widget:pump!) (show! 16)
  (check 'exit-removes-capture-and-retains-the-editor
    (list (exists (lambda (scope) (memq 'terminal-capture (cadr scope))) (cadr (widget:key-scopes root "C-]")))
      (refused? (lambda () (terminal:toggle-capture! a)))
      (begin (select! (child a) '(0 . 0) '(0 . 2)) (cadddr (state (child a)))))
    '(#f #t #t))
  (widget:unmount! root) (actor:detach! owner)
  (check 'unmount-keeps-the-process-document (store:exists? source) #t))
