#!/usr/bin/env scheme-script

;; Cached text readers receive a complete, owned provenance chain or #f.
(import (chezscheme))
(include "tests/roots.ss")
(test-roots! 'base)
(eval
  '(begin
     (import (prefix (foundation text) text:) (prefix (head text-source) source:)
             (prefix (state store) store:) (prefix (test) test:))
     (define actor '(agent source-test))
     (define check test:check)
     (define (since source basis) (call-with-values (lambda () (source:snapshot source basis)) list))
     (define (replay lines changes)
       (fold-left (lambda (lines entry)
                    (let ([delta (caddr entry)])
                      (let-values ([(next ignored) (text:apply-edit lines (text:delta-span delta) (text:delta-inserted delta))]) next)))
         lines changes))
     (define id (store:create! actor "source-history" '("alpha" "middle" "omega")))
     (define source (source:open! actor id))
     (define initial (since source #f))
     (define basis (cadr initial))
     (define (edit! span replacement)
       (store:edit! actor id (store:revision id) span replacement)
       (source:open! actor id))
     (store:set-property! actor id 'custom 'changed)
     (check 'facts-do-not-change-content-basis (since source #f) initial)
     (edit! (text:make-span 0 0 0 0) '("before" ""))
     (edit! (text:make-span 3 5 3 5) '("!"))
     (let* ([snapshot (since source basis)] [changes (caddr snapshot)])
       (check 'source-chain-preserves-positions-and-exact-text
         (list (map car changes)
           (fold-left text:rebase-position '(1 . 2) (map caddr changes))
           (replay (car initial) changes) (eq? (car snapshot) (source:lines source))
           (caddr (since source (cadr snapshot))) (caddr (since source (+ (cadr snapshot) 1))))
         (list (list (+ basis 1) (+ basis 2)) '(2 . 2) (car snapshot) #t '() #f))
       (set-car! (car changes) -1)
       (check 'history-read-owns-list (caar (caddr (since source basis))) (+ basis 1))
       (store:edit! actor id (store:revision id) (text:make-span 0 0 0 0) '("ahead" ""))
       (check 'unadopted-store-text-cannot-leak (since source #f)
         (list (car snapshot) (cadr snapshot) #f)))
     (source:open! actor id)
     (store:reset! actor id '("reset"))
     (check 'unadopted-reset-keeps-cached-chain (length (caddr (since source basis))) 3)
     (source:open! actor id)
     (check 'adopted-reset-bridges-line-diff
       (let ([snapshot (since source basis)])
         (list (length (caddr snapshot)) (replay (car initial) (caddr snapshot)))) '(4 #("reset")))
     (let* ([source (source:make #f '#("local") 0)] [text '#("new baseline")])
       (source:adopt! source 0 text 1 #f)
       (let-values ([(next delta) (text:apply-edit text (text:make-span 0 0 0 0) '("suffix"))])
         (source:adopt! source 1 next 2 (list (list 2 actor delta))))
       (check 'missing-history-is-never-a-partial-chain (caddr (since source 0)) #f))
     (let ([basis (source:revision source)])
       (do ([i 0 (+ i 1)]) ((= i 256)) (edit! (text:make-span 0 0 0 0) '("x")))
       (check 'retention-keeps-complete-boundary (length (caddr (since source basis))) 256)
       (edit! (text:make-span 0 0 0 0) '("x"))
       (check 'expiration-keeps-only-complete-suffix
         (list (caddr (since source basis)) (length (caddr (since source (+ basis 1))))) '(#f 256)))
     (for-each
       (lambda (read!)
         (let* ([id (store:create! actor "bridge-history" '("alpha" "middle" "omega")
                      '((base . "alpha\nmiddle\nomega") (trailing . #f)))]
                [source (source:open! actor id)])
           (store:edit! actor id (store:revision id) (text:make-span 1 6 1 6) '("!"))
           (source:open! actor id)
           (let ([initial (since source #f)])
             (read! actor id '("ALPHA" "middle" "OMEGA") '((base . "ALPHA\nmiddle\nOMEGA") (trailing . #f)))
             (source:open! actor id)
             (let ([snapshot (since source (cadr initial))])
               (check 'adoption-keeps-multiple-steps-and-revision-jumps
                 (and (> (length (caddr snapshot)) 1)
                   (equal? (car snapshot) (replay (car initial) (caddr snapshot)))) #t)))))
       (list store:reload! store:reread!))
     (test:finish! 'text-source)))
