#!/usr/bin/env scheme-script

;; Command history selects mine, all, or a named actor through the
;; store journal, using explicit editor views and journal result statuses.

(import (chezscheme))

(include "tests/roots.ss")
(test-roots! 'base)

(test-evaluate!
  '(begin
     (import (prefix (test) test:) (prefix (head head) head:) (prefix (head widget) widget:)
       (prefix (state store) store:) (prefix (foundation text) text:) (prefix (foundation string) string:)
       (prefix (head mode) mode:) (prefix (core kernel) kernel:))
     (define check test:check)
     (include "tests/editor-fixture.sps")
     (store:log-retention 256)
     (define bot '(agent undo-test))
     (define b (fresh "undo-foreign" '("base" "other")))
     (define id b)
     (edit:insert! editing "A")
     (store:edit! bot id (store:revision id) (text:make-span 1 0 1 0) '("G"))
     (refresh!)
     (goto! '(0 . 5))
     (edit:insert! editing "B")
     (edit:undo! editing)
     (check 'first-undo-preserves-foreign-text (text-of b) '("Abase" "Gother"))
     (check
       'undo-retains-foreign-provenance
       (and (exists (lambda (entry) (equal? (cadr entry) bot)) (store:history id 256)) #t)
       #t)
     (check
       'second-undo-applies
       (eq? (call-with-values (lambda () (edit:undo! editing)) (lambda (status detail) status)) 'blocked)
       #f)
     (check 'second-undo-keeps-foreign-text (text-of b) '("base" "Gother"))
     (check
       'mine-does-not-fall-through-to-other-actors
       (eq? (call-with-values (lambda () (edit:undo! editing)) (lambda (status detail) status)) 'nothing)
       #t)
     (edit:redo! editing)
     (edit:redo! editing)
     (check 'redo-keeps-foreign-text (text-of b) '("AbaseB" "Gother"))
     (edit:undo! editing)
     (check 'undo-after-redo-keeps-foreign-text (text-of b) '("Abase" "Gother"))
     (define plain (fresh "undo-plain" '("base" "other")))
     (define plain-id plain)
     (store:set-mark! bot plain-id 'anchor '(1 . 2))
     (edit:insert! editing "A")
     (edit:insert! editing "B")
     (edit:undo! editing)
     (edit:undo! editing)
     (check 'repeated-ordinary-undo (text-of plain) '("base" "other"))
     (check 'undo-keeps-unrelated-mark (store:mark bot plain-id 'anchor) '(1 . 2))
     (edit:redo! editing)
     (edit:redo! editing)
     (check 'repeated-ordinary-redo (text-of plain) '("ABbase" "other"))
     (define reset-buffer (fresh "undo-reset" '("base" "other")))
     (define reset-id reset-buffer)
     (edit:insert! editing "A")
     (store:reset! bot reset-id '("foreign reset"))
     (refresh!)
     (check
       'reset-gap-has-no-undo
       (eq? (call-with-values (lambda () (edit:undo! editing)) (lambda (status detail) status)) 'nothing)
       #t)
     (check 'reset-gap-keeps-text (text-of reset-buffer) '("foreign reset"))
     (define truncated (fresh "undo-truncated" '("base" "other")))
     (define truncated-id truncated)
     (edit:insert! editing "A")
     (store:edit! bot truncated-id (store:revision truncated-id) (text:make-span 1 0 1 0) '("G"))
     (do ([i 0 (+ i 1)])
         ((= i 257))
       (store:edit! bot truncated-id (store:revision truncated-id) (text:make-span 1 0 1 0) '("x")
         '(long "long agent action")))
     (refresh!)
     (define truncated-text (text-of truncated))
     (check
       'truncated-provenance-refuses-undo
       (eq? (call-with-values (lambda () (edit:undo! editing)) (lambda (status detail) status)) 'blocked)
       #t)
     (check 'truncated-provenance-keeps-text (text-of truncated) truncated-text)
     (define raced (fresh "undo-callback" '("base" "other")))
     (define raced-id raced)
     (edit:insert! editing "A")
     (define token
       (store:subscribe!
         raced-id
         (lambda (event)
           (when (and (eq? (car event) 'edit) (equal? (cadddr event) head:ui-actor))
             (store:edit! bot raced-id (store:revision raced-id) (text:make-span 1 0 1 0) '("G"))))))
     (edit:undo! editing)
     (store:unsubscribe! token)
     (check 'foreign-edit-during-undo-is-kept (text-of raced) '("base" "Gother"))
     (check
       'redo-after-disjoint-racing-foreign-edit-applies
       (eq? (call-with-values (lambda () (edit:redo! editing)) (lambda (status detail) status)) 'blocked)
       #f)
     (check 'redo-keeps-racing-foreign-edit (text-of raced) '("Abase" "Gother"))
     (define overlap (fresh "undo-overlap" '("base" "other")))
     (define overlap-id overlap)
     (edit:insert! editing "A")
     (store:edit! bot overlap-id (store:revision overlap-id) (text:make-span 0 0 0 5) '("BOT"))
     (refresh!)
     (define groups-before (store:undo-labels overlap-id))
     (check
       'overlap-refuses
       (eq? (call-with-values (lambda () (edit:undo! editing)) (lambda (status detail) status)) 'blocked)
       #t)
     (check 'overlap-keeps-foreign-text (text-of overlap) '("BOT" "other"))
     (check 'refusal-keeps-the-undo-groups (equal? (store:undo-labels overlap-id) groups-before) #t)
     (edit:undo-actor! bot editing)
     (check 'targeted-undo-restores-covered-own-edit (text-of overlap) '("Abase" "other"))
     (edit:undo! editing)
     (check 'mine-can-follow-another-actors-undo (text-of overlap) '("base" "other"))
     (check 'default-scope (edit:undo-scope) 'mine)
     (check 'invalid-scope-refuses (guard (ex [else #t]) (edit:undo-scope 'everyone) #f) #t)
     (check 'invalid-scope-keeps-default (edit:undo-scope) 'mine)
     (define scoped (fresh "undo-scoped" '("base" "other")))
     (define scoped-id scoped)
     (edit:insert! editing "A")
     (store:edit! bot scoped-id (store:revision scoped-id) (text:make-span 1 0 1 0) '("G"))
     (refresh!)
     (parameterize ([edit:undo-scope 'all])
       (edit:undo! editing)
       (check 'all-selects-latest-foreign-action (text-of scoped) '("Abase" "other"))
       (edit:undo! editing)
       (check 'all-continues-to-own-action (text-of scoped) '("base" "other"))
       (edit:redo! editing)
       (edit:redo! editing)
       (check 'all-redo-restores-both-authors (text-of scoped) '("Abase" "Gother"))
       (parameterize ([edit:undo-scope 'mine]) (edit:undo! editing))
       (check 'one-off-mine-preserves-other-author (text-of scoped) '("base" "Gother"))
       (check 'one-off-scope-keeps-preference (edit:undo-scope) 'all))
     (check 'scope-is-head-local-configuration (store:property scoped-id 'undo-scope) #f)
     (parameterize ([edit:undo-scope 'all]) (edit:undo! editing))
     (check 'one-off-all-undo-with-no-own-history (text-of scoped) '("base" "other"))
     (edit:redo! editing)
     (check 'redo-a-foreign-action-while-default-is-mine (text-of scoped) '("base" "Gother"))
     (check 'scope-restores-after-parameterize (edit:undo-scope) 'mine)
     (define grouped (fresh "undo-grouped" '("base" "other")))
     (edit:call-as-one-edit!
       "two lines"
       (lambda ()
         (edit:insert! editing "A")
         (editor:insert-at! editing "\n" #f)
         (edit:insert! editing "B")))
     (define grouped-text (text-of grouped))
     (edit:undo! editing)
     (check 'grouped-command-undo (text-of grouped) '("base" "other"))
     (edit:redo! editing)
     (check 'grouped-command-redo (text-of grouped) grouped-text)
     (define formatted (fresh "undo-formatted" '("base" "other")))
     (mode:register! "undo-format" '() '() (lambda (line) #f))
     (mode:choose! "undo-format" formatted)
     (store:set-property! head:ui-actor formatted 'trailing #f)
     (mode:register-formatter! "undo-format" (lambda (b from to) '("BASE" "OTHER")))
     (edit:format-buffer! editing)
     (check 'format-applies (text-of formatted) '("BASE" "OTHER"))
     (edit:undo! editing)
     (check 'format-undo (text-of formatted) '("base" "other"))
     (check 'format-undo-restores-final-newline (store:property formatted 'trailing #f) #f)
     (edit:redo! editing)
     (check 'format-redo (text-of formatted) '("BASE" "OTHER"))
     (check 'format-redo-restores-final-newline (store:property formatted 'trailing #f) #t)
     (store:set-property! head:ui-actor formatted 'trailing #f)
     (edit:format-buffer! editing)
     (check 'format-can-change-only-final-newline (store:property formatted 'trailing #f) #t)
     (edit:undo! editing)
     (check 'metadata-only-format-undo (edit:buffer-text formatted) "BASE\nOTHER")
     (edit:redo! editing)
     (check 'metadata-only-format-redo (edit:buffer-text formatted) "BASE\nOTHER\n")
     (mode:register-indenter! "undo-format" (lambda (b from to) '(2 4)))
     (edit:indent-buffer! editing)
     (check 'indent-applies (text-of formatted) '("  BASE" "    OTHER"))
     (edit:undo! editing)
     (check 'indent-undo (text-of formatted) '("BASE" "OTHER"))
     (define foreign-fact (fresh "undo-foreign-fact" '("base" "other")))
     (define foreign-fact-id foreign-fact)
     (edit:insert! editing "A")
     (store:set-property! bot foreign-fact-id 'trailing #f)
     (edit:undo! editing)
     (check 'ordinary-undo-preserves-foreign-final-newline (edit:buffer-text foreign-fact) "base\nother")
     (mode:choose! "undo-format" foreign-fact)
     (edit:format-buffer! editing)
     (store:set-property! bot foreign-fact-id 'trailing #f)
     (check
       'format-undo-refuses-foreign-fact-change
       (eq? (call-with-values (lambda () (edit:undo! editing)) (lambda (status detail) status)) 'blocked)
       #t)
     (check 'fact-conflict-keeps-entire-formatted-result (edit:buffer-text foreign-fact) "BASE\nOTHER")
     (show! plain)
     (store:set-property! head:ui-actor plain 'read-only #t)
     (define protected-text (text-of plain))
     (check
       'read-only-history-commands-refuse
       (map (lambda (command)
              (call-with-values command (lambda (status detail) (equal? (list status detail) '(refused read-only)))))
            (list
              (lambda () (edit:undo! editing))
              (lambda () (parameterize ([edit:undo-scope 'all]) (edit:undo! editing)))
              (lambda () (edit:undo-actor! bot editing))
              (lambda () (edit:redo! editing))))
       '(#t #t #t #t))
     (check
       'read-only-shared-entrypoints-refuse
       (cons
         (guard (ex [(kernel:refusal? ex) (condition-message ex)] [else (raise ex)])
           (submit! plain (text:make-span 0 0 0 0) '("bad"))
           #f)
         (map (lambda (direction)
                (call-with-values (lambda () (text-source:history! head:ui-actor plain direction 'mine)) list))
              '(undo redo)))
       '("Edit not applied: the buffer is read-only" (refused read-only) (refused read-only)))
     (check 'read-only-keeps-text (text-of plain) protected-text)
     (store:set-property! head:ui-actor plain 'read-only #f)
     (test:finish! 'undo)))
