;; Corpus work and private page publication remain in the base. Local
;; module documentation accompanies a query instead of becoming global.
(library (reference)
  (export fetch! page page! lookup entries browser-url)
  (import (chezscheme) (prefix (client) client:) (prefix (doc) doc:))
  (define (documents) (map doc:to-datum (doc:entries)))
  (define (fetch!) (client:request 'reference-fetch))
  (define (check-head head)
    (unless (equal? head (client:identity)) (error 'reference "a head addresses its own page")))
  (define (page head) (check-head head) (client:request 'reference-page))
  (define (page! head name keys . basis)
    (check-head head)
    (client:request 'reference-page! name keys basis (documents)))
  (define (lookup name)
    (map doc:from-datum (client:request 'reference-lookup name (documents))))
  (define (entries . predicate)
    (let ([entries (map doc:from-datum (client:request 'reference-entries (documents)))])
      (if (pair? predicate) (filter (car predicate) entries) entries)))
  (define (browser-url entry) (client:request 'reference-url (doc:to-datum entry)))
)
