#!/usr/bin/env scheme-script
;; extract.ss -- build describe.sdata from the downloaded reference HTML.
;;
;; Run from this directory (download.sh does):  scheme --script extract.ss
;;
;; Both books are generated by the same LaTeX-to-HTML converter, so one
;; parser covers them.  An entry is one or more consecutive lines
;;
;;   <span class=formdef><b>KIND</b>: <tt>TEMPLATE</tt></span>
;;
;; followed by optional "returns:" and "libraries:" lines and prose
;; paragraphs, up to the next entry or section heading.  Every entry
;; becomes one record in describe.sdata, an s-expression database read
;; by lib/scheme-describe.e:
;;
;;   (names        list of symbols the entry defines
;;    forms        list of (kind-string . template-string)
;;    returns      string or #f
;;    libraries    list of strings, e.g. ("(rnrs base)" "(rnrs)")
;;    source       tspl or csug
;;    chapter      the page's chapter title
;;    url          page anchor, e.g. "objects.html#./objects:s25"
;;    description) the prose, paragraphs separated by blank lines

(import (chezscheme))

(define (read-file path)
  (call-with-input-file path (lambda (p) (get-string-all p))))

(define (find-str s needle start)
  ;; Index of needle in s at or after start, or #f.
  (let ([n (string-length s)] [m (string-length needle)])
    (let loop ([i start])
      (cond [(> (+ i m) n) #f]
            [(let ok ([j 0])
               (or (= j m)
                   (and (char=? (string-ref s (+ i j)) (string-ref needle j))
                        (ok (+ j 1)))))
             i]
            [else (loop (+ i 1))]))))

;;; HTML to text ---------------------------------------------------------------

;; &nbsp; decodes to a hard space (code indentation and alignment), so
;; tidy can collapse the soft spaces that come from source-line wrapping
;; without touching it; the hard spaces become plain at the very end.
(define hard-space #\xA0)

(define (tag-name tag)
  ;; "b" for "b" or "/b"; "p" for "p align=..."
  (let* ([t (if (and (> (string-length tag) 0) (char=? (string-ref tag 0) #\/))
                (substring tag 1 (string-length tag))
                tag)]
         [n (string-length t)])
    (let loop ([i 0])
      (if (and (< i n) (char-alphabetic? (string-ref t i)))
          (loop (+ i 1))
          (substring t 0 i)))))

(define (closing-tag? tag)
  (and (> (string-length tag) 0) (char=? (string-ref tag 0) #\/)))

(define (html->text html)
  ;; <br> and <p> become line and paragraph breaks, the eval-arrow
  ;; images become =>, sup becomes ^, other tags vanish; entities are
  ;; decoded; the HTML source's own newlines are soft spaces.
  (let ([out (open-output-string)]
        [n (string-length html)])
    (let loop ([i 0])
      (when (< i n)
        (let ([c (string-ref html i)])
          (cond
            [(char=? c #\newline)
             (put-char out #\space)
             (loop (+ i 1))]
            [(char=? c #\<)
             (let* ([end (let scan ([j (+ i 1)] [quoted #f])
                           ;; the tag's closing >, honoring quoted
                           ;; attribute values (alt="<graphic>")
                           (cond [(>= j n) (- n 1)]
                                 [(char=? (string-ref html j) #\") (scan (+ j 1) (not quoted))]
                                 [(and (not quoted) (char=? (string-ref html j) #\>)) j]
                                 [else (scan (+ j 1) quoted)]))]
                    [tag (substring html (+ i 1) end)]
                    [name (tag-name tag)])
               (cond [(string=? name "br") (put-char out #\newline)]
                     [(and (string=? name "p") (not (closing-tag? tag)))
                      (put-string out "\n\n")]
                     [(string=? name "img") (put-string out " => ")]
                     [(and (string=? name "sup") (not (closing-tag? tag)))
                      (put-char out #\^)])
               (loop (+ end 1)))]
            [(char=? c #\&)
             (let* ([end (or (find-str html ";" i) (- n 1))]
                    [entity (and (< (- end i) 8) (substring html i (+ end 1)))])
               (cond [(not entity) (put-char out c) (loop (+ i 1))]
                     [(string=? entity "&nbsp;")
                      (put-char out hard-space) (loop (+ end 1))]
                     [(string=? entity "&lt;") (put-char out #\<) (loop (+ end 1))]
                     [(string=? entity "&gt;") (put-char out #\>) (loop (+ end 1))]
                     [(string=? entity "&amp;") (put-char out #\&) (loop (+ end 1))]
                     [(string=? entity "&quot;") (put-char out #\") (loop (+ end 1))]
                     [else (put-char out c) (loop (+ i 1))]))]
            [else (put-char out c) (loop (+ i 1))]))))
    (tidy (get-output-string out))))

(define (tidy s)
  ;; Collapse soft-space runs, trim line edges, cap blank runs at one
  ;; line, drop leading/trailing blank lines, harden the hard spaces.
  (define (soft? c) (char=? c #\space))
  (let ([out (open-output-string)]
        [n (string-length s)])
    (let loop ([i 0] [line-start? #t] [blanks 0] [pending-space #f] [any? #f])
      (if (= i n)
          (void)
          (let ([c (string-ref s i)])
            (cond
              [(soft? c)
               (loop (+ i 1) line-start? blanks (not line-start?) any?)]
              [(char=? c #\newline)
               (loop (+ i 1) #t (+ blanks 1) #f any?)]
              [else
               ;; emit the newlines owed (at most a blank line), then
               ;; a soft space if one is pending, then the character
               (when (and any? (> blanks 0))
                 (put-string out (if (> blanks 1) "\n\n" "\n")))
               (when (and pending-space (not line-start?) (= blanks 0))
                 (put-char out #\space))
               (put-char out (if (char=? c hard-space) #\space c))
               (loop (+ i 1) #f 0 #f #t)]))))
    (get-output-string out)))

;;; Entry parsing ---------------------------------------------------------------

(define formdef-mark "<span class=formdef>")

(define (formdef-positions s)
  (let loop ([i 0] [acc '()])
    (let ([p (find-str s formdef-mark i)])
      (if p (loop (+ p 1) (cons p acc)) (reverse acc)))))

(define (parse-formdef s pos)
  ;; -> (values kind template end-of-span)
  (let* ([end (or (find-str s "</span>" pos) (string-length s))]
         [inner (substring s (+ pos (string-length formdef-mark)) end)]
         [kb (find-str inner "<b>" 0)]
         [ke (find-str inner "</b>" 0)]
         [kind (if (and kb ke) (html->text (substring inner (+ kb 3) ke)) "")]
         [colon (and ke (find-str inner ":" ke))]
         [template (if colon
                       (html->text (substring inner (+ colon 1)
                                              (string-length inner)))
                       "")])
    (values kind template (+ end 7))))

(define (separators-only? s)
  ;; Is this inter-formdef gap just whitespace, breaks, and anchors?
  (let ([t (html->text s)])
    (let loop ([i 0])
      (or (= i (string-length t))
          (and (memv (string-ref t i) '(#\space #\newline))
               (loop (+ i 1)))))))

(define (template-names template)
  ;; The symbols a template defines: the operator of a parenthesized
  ;; form, or a bare token; quote/backquote/hash shorthands define
  ;; nothing themselves.
  (define (token-end i)
    (let loop ([i i])
      (if (or (= i (string-length template))
              (memv (string-ref template i) '(#\space #\( #\) #\[ #\])))
          i
          (loop (+ i 1)))))
  (let ([n (string-length template)])
    (cond [(= n 0) '()]
          [(char=? (string-ref template 0) #\()
           (let ([end (token-end 1)])
             (if (> end 1)
                 (list (string->symbol (substring template 1 end)))
                 '()))]
          [(memv (string-ref template 0) '(#\' #\` #\, #\#)) '()]
          [(= (token-end 0) n) (list (string->symbol template))]
          [else '()])))

(define (extract-title s)
  (let* ([a (find-str s "<title>" 0)]
         [b (and a (find-str s "</title>" a))])
    (if (and a b) (html->text (substring s (+ a 7) b)) "")))

(define (nearest-anchor s pos)
  ;; The last <a name="./..."> before pos, for the entry's url.
  (let loop ([i 0] [best #f])
    (let ([p (find-str s "<a name=\"./" i)])
      (if (and p (< p pos))
          (loop (+ p 1) p)
          (and best
               (let ([end (find-str s "\"" (+ best 9))])
                 (and end (substring s (+ best 9) end))))))))

(define (parse-labeled-line body label start limit)
  ;; The text of a `<b>label</b>value` line near start: (value . end),
  ;; or #f when the label is not there.
  (let ([p (find-str body label start)])
    (and p (< p limit)
         (let* ([vs (+ p (string-length label))]
                [br (find-str body "<br>" vs)]
                [blank (find-str body "\n\n" vs)]
                [end (min (or br (string-length body))
                          (or blank (string-length body)))])
           (cons (html->text (substring body vs end)) end)))))

(define (split-libraries s)
  ;; "(rnrs base), (rnrs)" -> ("(rnrs base)" "(rnrs)")
  (let loop ([i 0] [start 0] [depth 0] [acc '()])
    (define (grab end acc)
      (let ([piece (html->text (substring s start end))])
        (if (string=? piece "") acc (cons piece acc))))
    (cond [(= i (string-length s)) (reverse (grab i acc))]
          [(char=? (string-ref s i) #\() (loop (+ i 1) start (+ depth 1) acc)]
          [(char=? (string-ref s i) #\)) (loop (+ i 1) start (- depth 1) acc)]
          [(and (char=? (string-ref s i) #\,) (= depth 0))
           (loop (+ i 1) (+ i 1) 0 (grab i acc))]
          [else (loop (+ i 1) start depth acc)])))

(define (parse-body body)
  ;; -> (values returns libraries description)
  (let* ([r (parse-labeled-line body "<b>returns: </b>" 0 200)]
         [l (parse-labeled-line body "<b>libraries: </b>"
                                (if r (cdr r) 0) (+ (if r (cdr r) 0) 60))]
         [rest-start (cond [l (cdr l)] [r (cdr r)] [else 0])]
         [stop (let loop ([candidates '("<h2" "<h3" "<h4" "<hr")]
                          [best (string-length body)])
                 (if (null? candidates)
                     best
                     (loop (cdr candidates)
                           (let ([p (find-str body (car candidates) rest-start)])
                             (if (and p (< p best)) p best)))))])
    (values (and r (car r))
            (if l (split-libraries (substring body (+ (find-str body "<b>libraries: </b>" (if r (cdr r) 0)) 18) (cdr l))) '())
            (html->text (substring body rest-start stop)))))

(define (parse-page path source page)
  (let* ([s (read-file path)]
         [chapter (extract-title s)]
         [positions (formdef-positions s)])
    ;; group consecutive formdefs separated only by breaks and anchors
    (let loop ([ps positions] [entries '()])
      (if (null? ps)
          (reverse entries)
          (let gather ([pos (car ps)] [rest (cdr ps)] [forms '()])
            (let-values ([(kind template span-end) (parse-formdef s pos)])
              (let ([forms (cons (cons kind template) forms)])
                (if (and (pair? rest)
                         (separators-only? (substring s span-end (car rest))))
                    (gather (car rest) (cdr rest) forms)
                    (let* ([body-end (if (pair? rest)
                                         (car rest)
                                         (string-length s))]
                           [body (substring s span-end body-end)]
                           [forms (reverse forms)]
                           [names (apply append
                                         (map (lambda (f) (template-names (cdr f)))
                                              forms))])
                      (let-values ([(returns libraries description)
                                    (parse-body body)])
                        (let ([anchor (nearest-anchor
                                        (substring s (max 0 (- pos 400)) pos)
                                        400)]
                              [entry (lambda (anchor)
                                       (list names forms returns libraries
                                             source chapter
                                             (if anchor
                                                 (format "~a.html#~a" page anchor)
                                                 (format "~a.html" page))
                                             description))])
                          (loop rest
                                (cons (entry anchor) entries)))))))))))))

;;; Main -------------------------------------------------------------------------

(define tspl-pages
  '("binding" "control" "exceptions" "io" "libraries" "objects" "records"
    "syntax"))
(define csug-pages
  '("binding" "compat" "control" "debug" "expeditor" "foreign" "io"
    "libraries" "numeric" "objects" "smgmt" "syntax" "system" "threads"))

(define entries
  (append
    (apply append
           (map (lambda (p) (parse-page (string-append "tspl4/" p ".html")
                                        'tspl p))
                tspl-pages))
    (apply append
           (map (lambda (p) (parse-page (string-append "csug/" p ".html")
                                        'csug p))
                csug-pages))))

(with-output-to-file "describe.sdata"
  (lambda ()
    (display ";; generated by extract.ss -- do not edit\n")
    (display "(\n")
    (for-each (lambda (e) (write e) (newline)) entries)
    (display ")\n"))
  'replace)

(printf "describe.sdata: ~a entries (~a names)\n"
        (length entries)
        (fold-left + 0 (map (lambda (e) (length (car e))) entries)))
