;; describe.e -- a Scheme manual inside the editor: the library (describe).
;;
;; An e extension module: the library (describe), loaded at startup by
;; the core.  Serves the reference documentation for the whole default
;; corpus -- R6RS from TSPL4, the Chez extensions from the Chez Scheme
;; User's Guide.  The whole pipeline lives here: fetch-describe-data!
;; downloads the corpus into data/describe next to lib (the
;; byte transfer is delegated to curl, since Chez speaks no TLS; page
;; lists, orchestration, and parsing are all this module), extracts it
;; into data/describe/describe.sdata, and loads it.  Run it once:
;;
;;   M-x (fetch-describe-data!)
;;
;; and from then on
;;
;;   M-x (describe eq-hashtable-ref)
;;
;; pops up a *describe* buffer with the entry: its forms, what it
;; returns, its libraries, source, and the full prose.  The database is
;; structured and queryable: doc-lookup returns the entries for a name,
;; doc-entries all of them (optionally filtered), and the doc-*
;; accessors take them apart, so M-x expressions can slice the corpus:
;;
;;   (length (doc-entries))
;;   (doc-entries (lambda (e) (eq? (doc-source e) 'csug)))
;;   (filter (lambda (e) (member "(rnrs io ports)" (doc-libraries e)))
;;           (doc-entries))

(library (describe)
  (export init! describe describe! describe-at-point! fetch-describe-data!
          doc-lookup doc-entries
          doc-names doc-forms doc-returns doc-libraries
          doc-source doc-chapter doc-url doc-browser-url doc-description)
  ;; (only ...) because (eval) also exports an init!, which a library
  ;; body may not shadow; the import also orders the two modules'
  ;; initialization, whatever their load order.
  (import (chezscheme) (core) (only (eval) register-signatures!))

  (define-record-type (doc-entry make-doc-entry doc-entry?)
    (fields (immutable names doc-names)           ; symbols defined
            (immutable forms doc-forms)           ; ((kind . template) ...)
            (immutable returns doc-returns)       ; string or #f
            (immutable libraries doc-libraries)   ; ("(rnrs base)" ...)
            (immutable source doc-source)         ; tspl or csug
            (immutable chapter doc-chapter)       ; chapter title
            (immutable url doc-url)               ; page anchor
            (immutable description doc-description)))  ; markdown

  (define (data-dir)
    (string-append (data-directory) "/describe"))

  (define (signatures-path)
    (string-append (data-dir) "/signatures.sdata"))

  (define (data-path)
    (string-append (data-dir) "/describe.sdata"))

  ;;; HTML to text ---------------------------------------------------------------

  ;; Both books are generated by the same LaTeX-to-HTML converter, so
  ;; one parser covers them.  An entry is one or more consecutive lines
  ;;
  ;;   <span class=formdef><b>KIND</b>: <tt>TEMPLATE</tt></span>
  ;;
  ;; followed by optional "returns:" and "libraries:" lines and prose
  ;; paragraphs, up to the next entry or section heading.

  (define (find-str s needle start)
    ;; Index of needle in s at or after start, or #f.
    (let ([n (string-length s)] [m (string-length needle)])
      (let loop ([i start])
        (cond [(> (+ i m) n) #f]
              [(let ok ([j 0])
                 (or (= j m)
                     (and (char=? (string-ref s (+ i j)) (string-ref needle j))
                          (ok (+ j 1)))))
               i]
              [else (loop (+ i 1))]))))

  ;; &nbsp; decodes to a hard space (code indentation and alignment), so
  ;; tidy can collapse the soft spaces that come from source-line
  ;; wrapping without touching it; hard spaces become plain at the end.
  (define hard-space #\xA0)

  (define (tag-name tag)
    ;; "b" for "b" or "/b"; "p" for "p align=..."
    (let* ([t (if (and (> (string-length tag) 0)
                       (char=? (string-ref tag 0) #\/))
                  (substring tag 1 (string-length tag))
                  tag)]
           [n (string-length t)])
      (let loop ([i 0])
        (if (and (< i n) (char-alphabetic? (string-ref t i)))
            (loop (+ i 1))
            (substring t 0 i)))))

  (define (closing-tag? tag)
    (and (> (string-length tag) 0) (char=? (string-ref tag 0) #\/)))

  (define (html->text html) (convert-html html #f))

  ;; The markdown variant, for description bodies: <tt> becomes inline
  ;; `code`, or a fenced block when it spans lines (the example groups);
  ;; <i> and <b> outside code become *emphasis* and **bold**.
  (define (html->markdown html) (convert-html html #t))

  (define (convert-html html md?)
    ;; <br> and <p> become line and paragraph breaks, the eval-arrow
    ;; images become =>, sup becomes ^, other tags vanish; entities are
    ;; decoded; the HTML source's own newlines are soft spaces.
    (let ([out (open-output-string)]
          [n (string-length html)]
          [tt #f])                ; capture inside a <tt> span, when md?
      (define (sink) (or tt out))
      (define (end-tt!)
        (let ([content (get-output-string tt)])
          (set! tt #f)
          (cond [(string=? content "") (void)]
                [(find-str content "\n" 0)
                 ;; a code block: markdown's four-space indentation (hard
                 ;; spaces, so tidy keeps them), which md-mode styles as
                 ;; Scheme line by line
                 (put-string out "\n\n")
                 (let loop ([i 0] [line-start #t])
                   (when (< i (string-length content))
                     (when line-start
                       (put-string out (make-string 4 hard-space)))
                     (let ([c (string-ref content i)])
                       (put-char out c)
                       (loop (+ i 1) (char=? c #\newline)))))
                 (put-string out "\n\n")]
                [(find-str content "`" 0)   ; backticks cannot nest
                 (put-string out content)]
                [else (put-char out #\`)
                      (put-string out content)
                      (put-char out #\`)])))
      (let loop ([i 0])
        (when (< i n)
          (let ([c (string-ref html i)])
            (cond
              [(char=? c #\newline)
               (put-char (sink) #\space)
               (loop (+ i 1))]
              [(char=? c #\<)
               (let* ([end (let scan ([j (+ i 1)] [quoted #f])
                             ;; the tag's closing >, honoring quoted
                             ;; attribute values (alt="<graphic>")
                             (cond [(>= j n) (- n 1)]
                                   [(char=? (string-ref html j) #\")
                                    (scan (+ j 1) (not quoted))]
                                   [(and (not quoted)
                                         (char=? (string-ref html j) #\>))
                                    j]
                                   [else (scan (+ j 1) quoted)]))]
                      [tag (substring html (+ i 1) end)]
                      [name (tag-name tag)])
                 (cond [(string=? name "br") (put-char (sink) #\newline)]
                       [(and (string=? name "p") (not (closing-tag? tag)))
                        (put-string (sink) "\n\n")]
                       [(string=? name "img") (put-string (sink) " => ")]
                       [(and (string=? name "sup") (not (closing-tag? tag)))
                        (put-char (sink) #\^)]
                       [(and md? (string=? name "tt"))
                        (if (closing-tag? tag)
                            (when tt (end-tt!))
                            (unless tt (set! tt (open-output-string))))]
                       [(and md? (not tt) (string=? name "i"))
                        (put-char out #\*)]
                       [(and md? (not tt) (string=? name "b"))
                        (put-string out "**")])
                 (loop (+ end 1)))]
              [(char=? c #\&)
               (let* ([end (or (find-str html ";" i) (- n 1))]
                      [entity (and (< (- end i) 8)
                                   (substring html i (+ end 1)))])
                 (cond [(not entity) (put-char (sink) c) (loop (+ i 1))]
                       [(string=? entity "&nbsp;")
                        (put-char (sink) hard-space) (loop (+ end 1))]
                       [(string=? entity "&lt;")
                        (put-char (sink) #\<) (loop (+ end 1))]
                       [(string=? entity "&gt;")
                        (put-char (sink) #\>) (loop (+ end 1))]
                       [(string=? entity "&amp;")
                        (put-char (sink) #\&) (loop (+ end 1))]
                       [(string=? entity "&quot;")
                        (put-char (sink) #\") (loop (+ end 1))]
                       [else (put-char (sink) c) (loop (+ i 1))]))]
              [else (put-char (sink) c) (loop (+ i 1))]))))
      (when tt (end-tt!))
      (tidy (get-output-string out))))

  (define (tidy s)
    ;; Collapse soft-space runs, trim line edges, cap blank runs at one
    ;; line, drop leading/trailing blank lines, harden the hard spaces.
    (let ([out (open-output-string)]
          [n (string-length s)])
      (let loop ([i 0] [line-start? #t] [blanks 0] [pending-space #f] [any? #f])
        (if (= i n)
            (void)
            (let ([c (string-ref s i)])
              (cond
                [(char=? c #\space)
                 (loop (+ i 1) line-start? blanks (not line-start?) any?)]
                [(char=? c #\newline)
                 (loop (+ i 1) #t (+ blanks 1) #f any?)]
                [else
                 (when (and any? (> blanks 0))
                   (put-string out (if (> blanks 1) "\n\n" "\n")))
                 (when (and pending-space (not line-start?) (= blanks 0))
                   (put-char out #\space))
                 (put-char out (if (char=? c hard-space) #\space c))
                 (loop (+ i 1) #f 0 #f #t)]))))
      (get-output-string out)))

  ;;; Entry parsing ---------------------------------------------------------------

  (define formdef-mark "<span class=formdef>")

  (define (formdef-positions s)
    (let loop ([i 0] [acc '()])
      (let ([p (find-str s formdef-mark i)])
        (if p (loop (+ p 1) (cons p acc)) (reverse acc)))))

  (define (parse-formdef s pos)
    ;; -> (values kind template end-of-span)
    (let* ([end (or (find-str s "</span>" pos) (string-length s))]
           [inner (substring s (+ pos (string-length formdef-mark)) end)]
           [kb (find-str inner "<b>" 0)]
           [ke (find-str inner "</b>" 0)]
           [kind (if (and kb ke)
                     (html->text (substring inner (+ kb 3) ke))
                     "")]
           [colon (and ke (find-str inner ":" ke))]
           [template (if colon
                         (html->text (substring inner (+ colon 1)
                                                (string-length inner)))
                         "")])
      (values kind template (+ end 7))))

  (define (separators-only? s)
    ;; Is this inter-formdef gap just whitespace, breaks, and anchors?
    (let ([t (html->text s)])
      (let loop ([i 0])
        (or (= i (string-length t))
            (and (memv (string-ref t i) '(#\space #\newline))
                 (loop (+ i 1)))))))

  (define (template-names template)
    ;; The symbols a template defines: the operator of a parenthesized
    ;; form, or a bare token; quote/backquote/hash shorthands define
    ;; nothing themselves.
    (define (token-end i)
      (let loop ([i i])
        (if (or (= i (string-length template))
                (memv (string-ref template i) '(#\space #\( #\) #\[ #\])))
            i
            (loop (+ i 1)))))
    (let ([n (string-length template)])
      (cond [(= n 0) '()]
            [(char=? (string-ref template 0) #\()
             (let ([end (token-end 1)])
               (if (> end 1)
                   (list (string->symbol (substring template 1 end)))
                   '()))]
            [(memv (string-ref template 0) '(#\' #\` #\, #\#)) '()]
            [(= (token-end 0) n) (list (string->symbol template))]
            [else '()])))

  (define (extract-title s)
    (let* ([a (find-str s "<title>" 0)]
           [b (and a (find-str s "</title>" a))])
      (if (and a b) (html->text (substring s (+ a 7) b)) "")))

  (define (nearest-anchor s pos)
    ;; The last <a name="./..."> before pos, for the entry's url.
    (let loop ([i 0] [best #f])
      (let ([p (find-str s "<a name=\"./" i)])
        (if (and p (< p pos))
            (loop (+ p 1) p)
            (and best
                 (let ([end (find-str s "\"" (+ best 9))])
                   (and end (substring s (+ best 9) end))))))))

  (define (parse-labeled-line body label start limit)
    ;; The text of a `<b>label</b>value` line near start: (value . end),
    ;; or #f when the label is not there.
    (let ([p (find-str body label start)])
      (and p (< p limit)
           (let* ([vs (+ p (string-length label))]
                  [br (find-str body "<br>" vs)]
                  [blank (find-str body "\n\n" vs)]
                  [end (min (or br (string-length body))
                            (or blank (string-length body)))])
             (cons (html->text (substring body vs end)) end)))))

  (define (split-libraries s)
    ;; "(rnrs base), (rnrs)" -> ("(rnrs base)" "(rnrs)")
    (let loop ([i 0] [start 0] [depth 0] [acc '()])
      (define (grab end acc)
        (let ([piece (html->text (substring s start end))])
          (if (string=? piece "") acc (cons piece acc))))
      (cond [(= i (string-length s)) (reverse (grab i acc))]
            [(char=? (string-ref s i) #\()
             (loop (+ i 1) start (+ depth 1) acc)]
            [(char=? (string-ref s i) #\))
             (loop (+ i 1) start (- depth 1) acc)]
            [(and (char=? (string-ref s i) #\,) (= depth 0))
             (loop (+ i 1) (+ i 1) 0 (grab i acc))]
            [else (loop (+ i 1) start depth acc)])))

  (define (parse-body body)
    ;; -> (values returns libraries description)
    (let* ([r (parse-labeled-line body "<b>returns: </b>" 0 200)]
           [l (parse-labeled-line body "<b>libraries: </b>"
                                  (if r (cdr r) 0)
                                  (+ (if r (cdr r) 0) 60))]
           [rest-start (cond [l (cdr l)] [r (cdr r)] [else 0])]
           [stop (let loop ([candidates '("<h2" "<h3" "<h4" "<hr")]
                            [best (string-length body)])
                   (if (null? candidates)
                       best
                       (loop (cdr candidates)
                             (let ([p (find-str body (car candidates)
                                                rest-start)])
                               (if (and p (< p best)) p best)))))])
      (values (and r (car r))
              (if l
                  (split-libraries
                    (substring body
                               (+ (find-str body "<b>libraries: </b>"
                                            (if r (cdr r) 0))
                                  18)
                               (cdr l)))
                  '())
              (html->markdown (substring body rest-start stop)))))

  (define (read-file path)
    (call-with-input-file path (lambda (p) (get-string-all p))))

  (define (parse-page path source page)
    ;; Every entry of one chapter page, as raw entry lists.
    (let* ([s (read-file path)]
           [chapter (extract-title s)])
      ;; group consecutive formdefs separated only by breaks and anchors
      (let loop ([ps (formdef-positions s)] [entries '()])
        (if (null? ps)
            (reverse entries)
            (let gather ([pos (car ps)] [rest (cdr ps)] [forms '()])
              (let-values ([(kind template span-end) (parse-formdef s pos)])
                (let ([forms (cons (cons kind template) forms)])
                  (if (and (pair? rest)
                           (separators-only?
                             (substring s span-end (car rest))))
                      (gather (car rest) (cdr rest) forms)
                      (let* ([body-end (if (pair? rest)
                                           (car rest)
                                           (string-length s))]
                             [body (substring s span-end body-end)]
                             [forms (reverse forms)]
                             [names (apply append
                                           (map (lambda (f)
                                                  (template-names (cdr f)))
                                                forms))]
                             [anchor (nearest-anchor
                                       (substring s (max 0 (- pos 400)) pos)
                                       400)])
                        (let-values ([(returns libraries description)
                                      (parse-body body)])
                          (loop rest
                                (cons (list names forms returns libraries
                                            source chapter
                                            (if anchor
                                                (format "~a.html#~a"
                                                        page anchor)
                                                (format "~a.html" page))
                                            description)
                                      entries))))))))))))

  ;;; Fetching ------------------------------------------------------------------

  (define tspl-base "https://www.scheme.com/tspl4/")
  (define csug-base "https://cisco.github.io/ChezScheme/csug10.0/")

  (define tspl-pages
    '("binding" "control" "exceptions" "io" "libraries" "objects"
      "records" "syntax"))
  (define csug-pages
    '("binding" "compat" "control" "debug" "expeditor" "foreign" "io"
      "libraries" "numeric" "objects" "smgmt" "syntax" "system" "threads"))

  (define (doc-browser-url entry)
    ;; The entry's documentation in the browser: its page anchor made
    ;; absolute against its book's site.
    (string-append (case (doc-source entry)
                     [(tspl) tspl-base]
                     [(csug) csug-base]
                     [else ""])
                   (doc-url entry)))

  (define (ensure-directory! path)
    (unless (file-directory? path) (mkdir path)))

  (define (fetch-url! url path)
    ;; curl carries the bytes -- Chez speaks no TLS; everything else
    ;; about the pipeline is Scheme.
    (unless (zero? (system (format "curl -fsS '~a' -o '~a'" url path)))
      (error 'fetch-describe-data! "download failed" url)))

  (define (fetch-book! ref book base pages progress)
    (for-each (lambda (page)
                (progress (format "~a/~a.html" book page))
                (fetch-url! (format "~a~a.html" base page)
                            (format "~a/~a/~a.html" ref book page)))
              pages))

  (define (parse-book ref book source pages)
    (apply append
           (map (lambda (page)
                  (parse-page (format "~a/~a/~a.html" ref book page)
                              source page))
                pages)))

  (define (write-data! entries)
    (with-output-to-file (data-path)
      (lambda ()
        (display ";; generated by (describe) -- do not edit\n")
        (display "(\n")
        (for-each (lambda (e) (write e) (newline)) entries)
        (display ")\n"))
      'replace))

  (define (fetch-describe-data!)
    ;; Download the reference corpus into the describe-data directory next
    ;; to lib (kept out of git), extract it into describe.sdata, and
    ;; load it, reporting progress in the echo area.
    (parameterize ([message-source 'describe])
    (let* ([ref (data-dir)]
           [total (+ (length tspl-pages) (length csug-pages))]
           [done 0]
           [progress (lambda (what)
                       (set! done (+ done 1))
                       (set-message! (format "Fetching ~a (~a/~a)"
                                      what done total)))])
      (ensure-directory! ref)
      (ensure-directory! (string-append ref "/tspl4"))
      (ensure-directory! (string-append ref "/csug"))
      (fetch-book! ref "tspl4" tspl-base tspl-pages progress)
      (fetch-book! ref "csug" csug-base csug-pages progress)
      (set-message! "Extracting the reference corpus...")
      (write-data! (append (parse-book ref "tspl4" 'tspl tspl-pages)
                           (parse-book ref "csug" 'csug csug-pages)))
      (set! all-entries #f)
      (load-data!)
      (let ([sigs (generate-signatures)])
        (write-signatures! sigs)
        (register-signatures! sigs)
        (set-message! (format "Generated ~a signatures" (length sigs))))
      (set-message!
        (format "Describe database ready: ~a entries covering ~a names"
                (length all-entries)
                (fold-left + 0 (map (lambda (e) (length (doc-names e)))
                                    all-entries))))
      (void))))

  ;;; Loading -------------------------------------------------------------------

  (define all-entries #f)   ; list of doc-entry, or #f before loading
  (define by-name #f)       ; symbol -> (doc-entry ...), tspl first

  (define (generate-signatures)
    ;; The documented procedure call shapes, one per name (the longest
    ;; when a procedure has several forms), read off the corpus
    ;; templates -- what scheme-sigs.e used to transcribe by hand.
    (define (arity d)
      (let loop ([d (cdr d)] [n 0])
        (if (pair? d) (loop (cdr d) (+ n 1)) n)))
    (load-data!)
    (let ([best (make-eq-hashtable)])
      (for-each
        (lambda (e)
          (for-each
            (lambda (form)
              (when (equal? (car form) "procedure")
                (let ([datum (guard (ex [else #f])
                               (with-input-from-string (cdr form) read))])
                  (when (and (pair? datum) (symbol? (car datum)))
                    (let ([prev (eq-hashtable-ref best (car datum) #f)])
                      (when (or (not prev) (> (arity datum) (arity prev)))
                        (eq-hashtable-set! best (car datum) datum)))))))
            (doc-forms e)))
        all-entries)
      (vector->list (hashtable-values best))))

  (define (write-signatures! sigs)
    (with-output-to-file (signatures-path)
      (lambda ()
        (display ";; generated from the describe corpus -- do not edit\n")
        (write sigs)
        (newline))
      'replace))

  (define (load-signatures!)
    ;; Register the cached signatures with eval -- the cache is small
    ;; and loads at startup; when it is missing but the corpus is
    ;; there, build it once from the corpus.
    (guard (ex [else (void)])
      (cond
        [(file-exists? (signatures-path))
         (register-signatures!
           (with-input-from-file (signatures-path) read))]
        [(file-exists? (data-path))
         (let ([sigs (generate-signatures)])
           (write-signatures! sigs)
           (register-signatures! sigs))])))

  (define (load-data!)
    (unless all-entries
      (unless (file-exists? (data-path))
        (error 'describe
               "no reference data -- run (fetch-describe-data!) once"))
      (set! all-entries
        (map (lambda (e) (apply make-doc-entry e))
             (with-input-from-file (data-path) read)))
      (set! by-name (make-eq-hashtable))
      (for-each (lambda (entry)
                  (for-each (lambda (name)
                              (eq-hashtable-update! by-name name
                                (lambda (old) (cons entry old)) '()))
                            (doc-names entry)))
                (reverse all-entries))))

  ;;; Queries -------------------------------------------------------------------

  (define (doc-lookup name)
    ;; The entries documenting name (a symbol or its string), TSPL
    ;; before CSUG; '() when it is not in the corpus.
    (load-data!)
    (eq-hashtable-ref by-name
                      (if (string? name) (string->symbol name) name)
                      '()))

  (define (doc-entries . maybe-pred)
    ;; Every entry, or those a predicate accepts.
    (load-data!)
    (if (pair? maybe-pred)
        (filter (car maybe-pred) all-entries)
        all-entries))

  ;;; Display -------------------------------------------------------------------

  (define (wrap-line s width)
    ;; s broken at spaces into lines of at most width columns; a line
    ;; without spaces (or short enough) stays whole.
    (let loop ([start 0] [acc '()])
      (let ([n (string-length s)])
        (if (<= (- n start) width)
            (reverse (cons (substring s start n) acc))
            (let find ([i (min (+ start width) (- n 1))])
              (cond [(<= i start)
                     (reverse (cons (substring s start n) acc))]
                    [(char=? (string-ref s i) #\space)
                     (loop (+ i 1) (cons (substring s start i) acc))]
                    [else (find (- i 1))]))))))

  (define (split-on-newlines s)
    (let loop ([i 0] [start 0] [acc '()])
      (cond [(= i (string-length s))
             (reverse (cons (substring s start i) acc))]
            [(char=? (string-ref s i) #\newline)
             (loop (+ i 1) (+ i 1) (cons (substring s start i) acc))]
            [else (loop (+ i 1) start acc)])))

  (define (wrapped-lines text width)
    (apply append
           (map (lambda (line) (wrap-line line width))
                (split-on-newlines text))))

  (define (entry-lines entry)
    (append
      (map (lambda (form)
             (if (find-str (cdr form) "`" 0)
                 (format "**~a**: ~a" (car form) (cdr form))
                 (format "**~a**: `~a`" (car form) (cdr form))))
           (doc-forms entry))
      (if (doc-returns entry)
          (wrapped-lines (format "returns: ~a" (doc-returns entry)) 72)
          '())
      (if (pair? (doc-libraries entry))
          (list (format "libraries: ~a"
                        (string-join (doc-libraries entry) ", ")))
          '())
      (list (format "source: ~a, ~a"
                    (case (doc-source entry)
                      [(tspl) "TSPL4"]
                      [(csug) "Chez Scheme User's Guide"]
                      [else (doc-source entry)])
                    (doc-chapter entry))
            (format "url: ~a" (doc-browser-url entry))
            "")
      (wrapped-lines (doc-description entry) 72)))

  (define (describe! name)
    ;; Pop up a *describe* buffer with the documentation for name (a
    ;; symbol or its string); every matching entry is shown.
    (let ([entries (doc-lookup name)])
      (if (null? entries)
          (set-message! (format "No documentation for ~a" name))
          (begin
            (let ([b (fresh-buffer "*describe*")])
              (apply buffer-append! b
                     (let loop ([es entries] [acc '()])
                       (if (null? es)
                           (reverse acc)
                           (loop (cdr es)
                                 (append
                                   (reverse (entry-lines (car es)))
                                   (if (null? acc)
                                       acc
                                       (cons "" (cons (make-string 72 #\-)
                                                      (cons "" acc)))))))))
              (set-buffer-read-only! b #t)
              (set-buffer-mode! b "markdown")
              (call-with-buffer b (lambda () (goto-point! '(0 . 0))))
              (if (display-buffer! b)
                  (set-message! "")
                  (set-message!
                    (format "~a: see the *describe* buffer" name))))))
      (void)))

  (define-syntax describe
    (syntax-rules ()
      [(_ name) (describe! 'name)]))

  ;;; The symbol at point ---------------------------------------------------------

  (define (scheme-delimiter? c)
    (or (char-whitespace? c)
        (memv c '(#\( #\) #\[ #\] #\{ #\} #\" #\; #\' #\` #\,))))

  (define (symbol-at-point)
    ;; The symbol the cursor is on -- or just after, as at the end of a
    ;; word -- in the current buffer; #f when point is not at one.
    (let* ([b (current-buffer)]
           [p (point)]
           [s (buffer-line b (car p))]
           [n (string-length s)]
           [on? (lambda (i)
                  (and (>= i 0) (< i n)
                       (not (scheme-delimiter? (string-ref s i)))))]
           [col (cond [(on? (cdr p)) (cdr p)]
                      [(on? (- (cdr p) 1)) (- (cdr p) 1)]
                      [else #f])])
      (and col
           (let ([start (let back ([i col]) (if (on? (- i 1)) (back (- i 1)) i))]
                 [end (let fwd ([i col]) (if (on? i) (fwd (+ i 1)) i))])
             (string->symbol (substring s start end))))))

  (define (describe-at-point!)
    ;; Describe the symbol the cursor is on -- M-., in Scheme buffers.
    (cond [(not (member (buffer-mode-name (current-buffer))
                        '("scheme")))
           (set-message! "Not a Scheme buffer")]
          [(symbol-at-point) => describe!]
          [else (set-message! "No symbol at point")])
    (void))

  (define (describe-input! text pos)
    ;; M-. at a prompt: describe the symbol at the cursor, or the one
    ;; just before it, trailing spaces skipped -- "vector-sort " M-.
    ;; pops the page for vector-sort while the prompt stays open.
    (define (delim? c)
      (or (char-whitespace? c)
          (memv c '(#\( #\) #\[ #\] #\{ #\} #\" #\; #\' #\` #\,))))
    (let* ([n (string-length text)]
           [i (min pos n)]
           [end (if (and (< i n) (not (delim? (string-ref text i))))
                    (let fwd ([j i])
                      (if (and (< j n) (not (delim? (string-ref text j))))
                          (fwd (+ j 1))
                          j))
                    (let back ([j i])
                      (if (and (> j 0)
                               (memv (string-ref text (- j 1))
                                     '(#\space #\tab)))
                          (back (- j 1))
                          j)))]
           [start (let back ([j end])
                    (if (and (> j 0)
                             (not (delim? (string-ref text (- j 1)))))
                        (back (- j 1))
                        j))])
      (when (> end start)
        (describe! (string->symbol (substring text start end))))))

  (define (init!)
    (load-signatures!)
    (prompt-inspector describe-input!)
    (bind-key! "M-." describe-at-point!)))
