;; scheme-sigs.e -- parameter names for common builtins, for M-x signatures.
;;
;; An e extension module: the library (scheme-sigs), loaded at startup by
;; the core, which calls init!.  Compiled builtins carry no source,
;; so their parameter names cannot be recovered at run time; this table
;; transcribes them from The Scheme Programming Language and the Chez
;; Scheme User's Guide.  Each entry is the documented call shape itself:
;; a parenthesized parameter is optional, ... allows any more.  The
;; import of (eval) supplies register-signatures! -- and orders the two
;; modules' initialization, whatever their load order.

(library (scheme-sigs)
  (export init!)
  ;; (only ...) because (eval) also exports an init!, which a library
  ;; body may not shadow.
  (import (chezscheme) (only (eval) register-signatures!))

  (define (init!)
    (register-signatures!
      '(;; pairs and lists
        (car pair)
        (cdr pair)
        (cons obj1 obj2)
        (list obj ...)
        (list* obj ... final)
        (append list ...)
        (length list)
        (reverse list)
        (list-tail list n)
        (list-ref list n)
        (memq obj list)
        (memv obj list)
        (member obj list)
        (assq obj alist)
        (assv obj alist)
        (assoc obj alist)
        (remq obj list)
        (remv obj list)
        (remove obj list)
        (last-pair list)
        (list-copy list)
        ;; higher order
        (map procedure list ...)
        (for-each procedure list ...)
        (apply procedure obj ... list)
        (filter procedure list)
        (partition procedure list)
        (find procedure list)
        (exists procedure list ...)
        (for-all procedure list ...)
        (fold-left procedure acc list ...)
        (fold-right procedure acc list ...)
        (sort predicate list)
        (list-sort predicate list)
        (vector-sort predicate vector)
        ;; numbers
        (+ num ...)
        (- num ...)
        (* num ...)
        (/ num ...)
        (= num1 num2 ...)
        (< num1 num2 ...)
        (> num1 num2 ...)
        (<= num1 num2 ...)
        (>= num1 num2 ...)
        (quotient int1 int2)
        (remainder int1 int2)
        (modulo int1 int2)
        (min num1 num2 ...)
        (max num1 num2 ...)
        (abs num)
        (expt num1 num2)
        (exact num)
        (inexact num)
        (floor num)
        (ceiling num)
        (round num)
        (truncate num)
        (number->string num (radix))
        (string->number string (radix))
        ;; predicates
        (eq? obj1 obj2)
        (eqv? obj1 obj2)
        (equal? obj1 obj2)
        (not obj)
        ;; characters and strings
        (char->integer char)
        (integer->char n)
        (char=? char1 char2 ...)
        (char-upcase char)
        (char-downcase char)
        (string char ...)
        (make-string n (char))
        (string-length string)
        (string-ref string n)
        (string-set! string n char)
        (string=? string1 string2 ...)
        (string<? string1 string2 ...)
        (substring string start end)
        (string-append string ...)
        (string-copy string)
        (string->list string)
        (list->string char-list)
        (string->symbol string)
        (symbol->string symbol)
        (string-upcase string)
        (string-downcase string)
        ;; vectors and hashtables
        (vector obj ...)
        (make-vector n (obj))
        (vector-length vector)
        (vector-ref vector n)
        (vector-set! vector n obj)
        (vector->list vector)
        (list->vector list)
        (vector-fill! vector obj)
        (vector-map procedure vector ...)
        (vector-for-each procedure vector ...)
        (vector-append vector ...)
        (vector-copy vector (start) (length))
        (make-eq-hashtable (size))
        (make-hashtable hash equiv? (size))
        (hashtable-ref hashtable key default)
        (hashtable-set! hashtable key obj)
        (hashtable-delete! hashtable key)
        (hashtable-contains? hashtable key)
        (hashtable-keys hashtable)
        ;; control
        (values obj ...)
        (call-with-values producer consumer)
        (call/cc procedure)
        (call-with-current-continuation procedure)
        (dynamic-wind before thunk after)
        (error who msg irritant ...)
        (assertion-violation who msg irritant ...)
        ;; ports and input/output
        (display obj (port))
        (write obj (port))
        (newline (port))
        (read (port))
        (read-char (port))
        (peek-char (port))
        (write-char char (port))
        (format fmt-string obj ...)
        (printf fmt-string obj ...)
        (open-input-file path)
        (open-output-file path (options))
        (close-port port)
        (call-with-input-file path procedure)
        (call-with-output-file path procedure (options))
        (with-input-from-file path thunk)
        (with-output-to-file path thunk (options))
        (with-output-to-string thunk)
        (get-line port)
        (get-string-all port)
        (put-string port string)
        (flush-output-port (port))
        ;; system
        (system command-string)
        (getenv name)
        (putenv name value)
        (exit (obj))
        (current-directory (path))
        (directory-list path)
        (file-exists? path)
        (file-directory? path)
        (delete-file path)
        (rename-file old new)
        (load path)
        (eval expr (environment))))))
