;; One subscribed buffer inventory; collection providers own derived indexes.
(import (only (foundation edoc) elibrary))
(elibrary (state catalogue)
  (export create-query! create-source! neighbor)
  (import (chezscheme) (prefix (core descriptor) descriptor:) (prefix (core kernel) kernel:)
          (prefix (core property) property:) (prefix (core row) row:)
          (prefix (foundation string) string:)
          (prefix (state actor) actor:)
          (prefix (state collection) collection:) (prefix (state connection) connection:) (prefix (state model) model:)
          (prefix (state store) store:))

  (define (get row key default) (cond [(assq key row) => cdr] [else default]))
  (define (natural? n) (and (integer? n) (exact? n) (>= n 0)))
  (define lock (make-mutex))
  (define ready (make-condition))
  (define changed? #t)
  (define running? #f)
  (define take-events #f)
  (define jobs (make-hashtable equal-hash equal?))
  (define job-order '())
  (define pending-views (make-hashtable equal-hash equal?))
  (define reset-views? #t)
  (define inventory (make-eqv-hashtable)) ; worker-owned, metadata only
  (define orders (make-hashtable equal-hash equal?)) ; worker-owned, shared across filters
  (define rings (make-eq-hashtable)) ; ordered live list -> vector and key indexes
  (define view-rows (make-hashtable equal-hash equal?)) ; id -> (row audience)
  (define (wake!) (with-mutex lock (set! changed? #t) (condition-signal ready)))
  (define model-changes
    (model:subscribe! #f
      (lambda (notice)
        ;; Identify changed views without copying unrelated model payloads.
        (let ([ids (cadr notice)])
          (with-mutex lock
            (if (not ids) (begin (set! reset-views? #t) (set! changed? #t))
              (let ([kinds (model:metadata ids)])
                (for-each (lambda (id)
                            (case (cond [(assoc id kinds) => cadr] [else #f])
                              [(widget-view #f) (hashtable-set! pending-views id #t) (set! changed? #t)]
                              [(buffer-catalogue) (set! changed? #t)])) ids)))
            (when changed? (condition-signal ready)))))))
  (define (recipe? v)
    (and (list? v) (for-all pair? v) (equal? (map car v) '(owner home epoch))
      (actor:identity? (get v 'owner #f)) (string? (get v 'home #f)) (natural? (get v 'epoch #f))))
  (define kind
    (model:register-kind! 'buffer-catalogue 1 recipe?))
  (define (sources)
    (filter (lambda (id)
              (let ([r (model:snapshot id)])
                (and r (= (get r 'schema 0) 1) (recipe? (get r 'value #f)) (model:available? id))))
      (model:ids 'buffer-catalogue)))

  (define (start!)
    (with-mutex lock
      (unless running?
        ;; Subscribe before the first snapshot. A racing change is in the
        ;; snapshot, the pending IDs, or both; one worker applies both reads.
        (let-values ([(token take) (store:watch! wake!)]) (set! take-events take))
        (set! running? #t) (fork-thread work!))))

  (edoc "Create a buffer catalogue source for a head, with explicit home spelling for filtering. Shared document and named root-view inventories are rebuilt from base state; only this small recipe persists."
        (actor actor "owner/head") (home string "absolute home directory")
        (persistence (one-of transient persistent) "restart policy") (returns row-source))
  (define (create-source! actor home persistence)
    (unless (and (string? home) (> (string-length home) 0) (char=? (string-ref home 0) #\/)) (error 'create-source! "expected absolute home directory"))
    (start!)
    (let ([id (model:create! actor 'buffer-catalogue 1 'session persistence '()
                (list (cons 'owner actor) (cons 'home home) '(epoch . 0)))]) (wake!) id))

  (edoc "Create a catalogue query with its own internal editable filter. The query owns the supplied source and filter; views borrow them. Returns the query and filter reference."
        (actor actor "owner/head") (source row-source "unshared persistent catalogue source")
        (returns list "(query (buffer id))"))
  (define (create-query! actor source)
    (let ([r (model:snapshot source)])
      (unless (and r (eq? (get r 'kind #f) 'buffer-catalogue) (eq? (get r 'persistence #f) 'persistent)
                (equal? actor (get (get r 'value '()) 'owner #f)))
        (error 'create-query! "expected this head's persistent catalogue source" source))
      (let* ([filter (list 'buffer (store:create! actor "Buffet filter" '("")
                                     (list '(internal . #t) (cons 'audience (list actor)))))]
             [query (collection:create! actor source "" '() (get r 'persistence 'persistent) (list source filter))])
        (connection:bind! actor query (list (list query 'filter #f (list filter 'text))))
        (list query filter))))

  (edoc "The next or previous live catalogue key in a query's unfiltered sort order, wrapping at the ends. Uses the provider's cached index; archives never participate."
        (actor actor "owner/head") (query row-source "catalogue query") (key datum "current row key")
        (direction (one-of next previous) "ring direction") (returns any) (effects internal))
  (define (neighbor actor query key direction)
    (unless (memq direction '(next previous)) (error 'neighbor "invalid direction" direction))
    (start!)
    (let ([mutex (make-mutex)] [done (make-condition)] [answer #f] [complete? #f])
      (with-mutex lock
        (let ([ticket (gensym "neighbor")])
          (hashtable-set! jobs ticket
            (lambda ()
              (let ([result
                     (guard (ex [else (cons 'error ex)])
                       (let* ([q (collection:summary query)] [v (and q (get q 'value '()))]
                              [source (and v (model:snapshot (get v 'source #f)))])
                         (unless (and source (eq? (get source 'kind #f) 'buffer-catalogue)
                                   (equal? actor (get (get source 'value '()) 'owner #f)))
                           (error 'neighbor "unavailable catalogue query" query))
                         (let* ([rows (car (ordered source (get v 'sort '()) (lambda () #f)))]
                                [ring (or (hashtable-ref rings rows #f)
                                        (let ([keys (list->vector (map car rows))] [positions (make-hashtable equal-hash equal?)])
                                          (vector-for-each (lambda (i k) (hashtable-set! positions k i)) (list->vector (iota (vector-length keys))) keys)
                                          (let ([ring (cons keys positions)]) (hashtable-set! rings rows ring) ring)))]
                                [at (hashtable-ref (cdr ring) key #f)] [n (vector-length (car ring))])
                           (cons 'ready (and (> n 0) (vector-ref (car ring)
                                                       (if at (mod (+ at (if (eq? direction 'next) 1 -1)) n) 0)))))))])
                (with-mutex mutex (set! answer result) (set! complete? #t) (condition-signal done)))))
          (set! job-order (append job-order (list ticket))) (condition-signal ready)))
      (with-mutex mutex (let wait () (unless complete? (condition-wait done mutex) (wait))))
      (if (eq? (car answer) 'error) (raise (cdr answer)) (cdr answer))))

  (define columns
    '((modified "Modified" integer) (flags "Flags" (list-of buffer-flag)) (name "Buffer" string)
      (lines "Lines" integer) (mode "Mode" string) (file "File" string)
      (version "Version" integer) (archive "Archive" (one-of live backup trash)) (archived-at "Archived" integer)
      (expires-at "Expires" integer)))
  (define (document m)
    (let ([trashed (get m 'trashed #f)] [backup (get m 'backup #f)])
      (list (list 'buffer (get m 'id #f))
        (append (list (cons 'name (get m 'name "")) (cons 'flags (get m 'flags '())) (cons 'version (get m 'version 0))
                  (cons 'lines (get m 'lines 0)) (cons 'archive (if trashed (if backup 'backup 'trash) 'live)))
          (if (and (get m 'modified #f) (get m 'modified-at #f)) (list (cons 'modified (get m 'modified-at #f))) '())
          (if trashed (list (cons 'archived-at (car trashed))) '())
          (if (and trashed (not backup)) (list (cons 'expires-at (+ (car trashed) (* 86400 (store:trash-retention))))) '())
          (filter values (map (lambda (k) (let ([v (if (and (eq? k 'file) backup) (car backup) (get m k #f))])
                                            (and (string? v) (cons k v)))) '(mode file))))
        (cond [trashed '((roles ghost))] [(get m 'modified #f) '((roles italic))] [else '()]))))
  (define (view-row id)
    (let* ([r (model:snapshot id)] [d (and r (get r 'value #f))])
      (and r (eq? (get r 'kind #f) 'widget-view) (descriptor:valid? d)
        (not (descriptor:parent d))
        (let* ([options (descriptor:options d)] [name (get options 'name #f)])
          (and (string? name) (actor:audience? (get options 'audience 'all))
            (list (list id (list (cons 'name name) (cons 'version (descriptor:generation d))
                             '(flags) '(mode . "widget") '(archive . live)) '())
              (get options 'audience 'all)))))))
  (define (cell r name) (assq name (cadr r)))
  (define (order-key r) (format "~s" (car r)))
  (define (ordered source sort cancelled?)
    (let* ([v (get source 'value '())] [actor (get v 'owner #f)] [home (get v 'home "")]
           [key (list actor home sort)] [cached (hashtable-ref orders key #f)])
      (or cached
        (let ([rows (append
                      (filter values (map (lambda (m)
                                            (and (not (get m 'internal #f)) (actor:in-audience? actor (get m 'audience 'all)) (document m)))
                                       (vector->list (hashtable-values inventory))))
                      (filter values (map (lambda (p) (and (actor:in-audience? actor (cadr p)) (car p)))
                                       (vector->list (hashtable-values view-rows)))))])
          (define (fallback a b)
            (let ([a-name (cdr (cell a 'name))] [b-name (cdr (cell b 'name))])
              (or (string-ci<? a-name b-name)
                (and (string-ci=? a-name b-name) (or (string<? a-name b-name)
                                                   (and (string=? a-name b-name) (string<? (order-key a) (order-key b))))))))
          (define (less a b)
            (when (cancelled?) (error 'catalogue "cancelled"))
            (let loop ([keys sort])
              (if (null? keys) (fallback a b)
                (let* ([key (caar keys)] [x (cell a key)] [y (cell b key)]
                       [before? (if (eq? key 'flags) (lambda (x y) (property:flags<? (if x (cdr x) '()) (if y (cdr y) '()))) row:less?)])
                  (cond [(before? x y) (eq? (cadar keys) 'ascending)] [(before? y x) (eq? (cadar keys) 'descending)] [else (loop (cdr keys))])))))
          (define (archived<? a b)
            (when (cancelled?) (error 'catalogue "cancelled"))
            (let ([x (cdr (cell a 'archived-at))] [y (cdr (cell b 'archived-at))])
              (or (> x y) (and (= x y) (> (cadar a) (cadar b))))))
          (let ([parts (map (lambda (kind)
                              (list-sort (if (eq? kind 'live) less archived<?)
                                (filter (lambda (r) (eq? (cdr (cell r 'archive)) kind)) rows))) '(live backup trash))])
            (hashtable-set! orders key parts) parts)))))
  (define (prepare source query cancelled?)
    (let* ([home (get (get source 'value '()) 'home "")]
           [needle (get query 'filter "")] [match (string:searcher needle #t)]
           [parts (ordered source (get query 'sort '()) cancelled?)])
      (define (matches? r)
        (when (cancelled?) (error 'catalogue "cancelled"))
        (or (string=? needle "")
          (exists (lambda (s) (match s 0 (string-length s)))
            (let* ([name (cdr (cell r 'name))] [path (and (cell r 'file) (cdr (cell r 'file)))]
                   [home (if (string:suffix? "/" home) home (string-append home "/"))])
              (append (list name) (if path (list path) '())
                (if (and path (string:prefix? home path)) (list (string-append "~/" (substring path (string-length home) (string-length path)))) '()))))))
      (let* ([parts (map (lambda (rows) (filter matches? rows)) parts)]
             [rows (list->vector (append (car parts)
                                   (apply append (map (lambda (kind label entries)
                                                        (if (null? entries) '()
                                                          (cons (list (list 'section kind) (list (cons 'name label)) '((selectable . #f))) entries)))
                                                   '(backup trash) '("Backups" "Trash") (cdr parts)))))]
             [positions (make-hashtable equal-hash equal?)] [eligible '()])
        (vector-for-each (lambda (i r) (hashtable-set! positions (car r) i)
                           (when (row:selectable? r) (set! eligible (cons i eligible))))
          (list->vector (iota (vector-length rows))) rows)
        (let* ([eligible (list->vector (reverse eligible))] [n (vector-length eligible)])
          (collection:make-result columns (vector-length rows) (lambda (i) (vector-ref rows i))
            (lambda (key) (hashtable-ref positions key #f))
            (lambda (at direction offset)
              (and (> n 0)
                (let search ([lo 0] [hi n])
                  (if (= lo hi)
                    (vector-ref eligible (max 0 (min (- n 1) (+ (if (eq? direction 'forward) lo (- lo 1)) (if (eq? direction 'forward) offset (- offset))))))
                    (let ([mid (div (+ lo hi) 2)])
                      (if (if (eq? direction 'forward) (< (vector-ref eligible mid) at) (<= (vector-ref eligible mid) at))
                        (search (+ mid 1) hi) (search lo mid)))))))
            '((sortable modified flags name lines mode file)))))))
  (define (touch-sources!)
    (for-each (lambda (id)
                (let ([r (model:snapshot id)])
                  (when r
                    (let ([v (get r 'value '())])
                      (model:commit! '(base catalogue)
                        (list (list id (get r 'revision 0) (get r 'references '())
                                (map (lambda (p) (if (eq? (car p) 'epoch) (cons 'epoch (+ 1 (cdr p))) p)) v))))))))
      (sources)))
  (define (work!)
    (let loop ([initial? #t])
      (let-values ([(dirty? view-ids job)
                    (with-mutex lock
                      (let wait () (unless (or changed? (> (hashtable-size jobs) 0)) (condition-wait ready lock) (wait)))
                      (let ([dirty? changed?] [job (and (pair? job-order) (hashtable-ref jobs (car job-order) #f))])
                        (set! changed? #f)
                        (when job (hashtable-delete! jobs (car job-order)) (set! job-order (cdr job-order)))
                        (let ([ids (and (not reset-views?) (vector->list (hashtable-keys pending-views)))])
                          (set! reset-views? #f) (hashtable-clear! pending-views)
                          (values dirty? ids job))))])
        (let* ([source-ids (sources)] [sources? (pair? source-ids)] [events (take-events)] [ids (and events (map car events))]
               [packet (and sources? (or initial? (not events) (pair? ids)) (if (or initial? (not events)) (store:metadata) (store:metadata ids)))]
               [updated? initial?])
          (unless sources? (hashtable-clear! inventory) (hashtable-clear! orders) (hashtable-clear! rings) (hashtable-clear! view-rows))
          (when packet
            (when (or initial? (not events)) (hashtable-clear! inventory) (set! updated? #t))
            (for-each (lambda (p)
                        (let ([m (and (cadr p) (not (get (cadr p) 'internal #f)) (cadr p))])
                          (unless (equal? m (hashtable-ref inventory (car p) #f))
                            (set! updated? #t)
                            (if m (hashtable-set! inventory (car p) m) (hashtable-delete! inventory (car p)))))) (cadr packet)))
          (when (and sources? (or dirty? initial?))
            (when (or initial? (not view-ids))
              (when (> (hashtable-size view-rows) 0) (set! updated? #t))
              (hashtable-clear! view-rows))
            (for-each (lambda (id)
                        (let ([row (view-row id)])
                          (unless (equal? row (hashtable-ref view-rows id #f))
                            (set! updated? #t)
                            (if row (hashtable-set! view-rows id row) (hashtable-delete! view-rows id)))))
              (if (or initial? (not view-ids)) (model:ids 'widget-view) view-ids)))
          (when updated?
            (hashtable-clear! orders) (hashtable-clear! rings) (touch-sources!))
          (when job
            (if (procedure? job) (job)
              (let ([cancelled? (caddr job)] [publish! (cadddr job)])
                (unless (cancelled?)
                  (guard (ex [else (unless (cancelled?) (publish! #f (kernel:condition-text ex)))])
                    (publish! (prepare (car job) (cadr job) cancelled?) #f))))))
          (loop (not sources?))))))
  (define provider
    (collection:register! 'buffer-catalogue 1
      (lambda (source query cancelled? publish!)
        (start!)
        (with-mutex lock
          (let ([id (get query 'id #f)])
            (unless (hashtable-contains? jobs id) (set! job-order (append job-order (list id))))
            (hashtable-set! jobs id (list source query cancelled? publish!)))
          (condition-signal ready)))))
)
