;; Small composable controls. Authored text remains in the existing entry.
(import (only (foundation edoc) elibrary))
(elibrary (head control)
  (export activate! create-filter! init!)
  (import (chezscheme) (prefix (foundation string) string:) (prefix (head keymap) keymap:) (prefix (head layout) layout:)
          (prefix (head widget) widget:) (prefix (state view) view:)
          (prefix (sys glyph) glyph:))
  (define hover (make-hashtable equal-hash equal?))
  (define held (make-hashtable equal-hash equal?))
  (define (release! id) (hashtable-delete! held id) (hashtable-delete! hover id))
  (define (input inputs name fallback)
    (let ([p (assq name inputs)]) (if (and p (eq? (cadr p) 'ready)) (caddr p) fallback)))
  (define (data id source inputs)
    (list id (input inputs 'text "[Unavailable]") (input inputs 'enabled #f)
      (let ([p (assq 'text inputs)]) (and p (eq? (cadr p) 'ready)))))
  (define (enabled? id)
    (let-values ([(source d inputs) (widget:context id 'current)])
      (and (input inputs 'enabled #f) (assq 'activate (widget:commands id)) #t)))
  (define (service! id frame)
    (when (and (hashtable-ref held id #f) (not (enabled? id))) (hashtable-delete! held id)))

  (edoc "Invoke an enabled action-text control's explicit command target." (id model "action view") (returns any))
  (define (activate! id)
    (unless (enabled? id) (error 'activate! "action is unavailable" id))
    (widget:invoke! id 'activate))

  (define (label-lines text d width)
    (if (and (eq? (view:kind d) 'label) (cond [(assq 'wrap (view:options d)) => cdr] [else #f]))
      (apply append (map (lambda (line)
                           (map (lambda (i) (glyph:slice line (* i (max 1 width)) (max 1 width)))
                             (iota (max 1 (div (+ (glyph:cells line) (max 1 width) -1) (max 1 width))))))
                      (string:lines text))) (list (glyph:fit text width))))
  (define (render data d width height range)
    (let* ([lines (label-lines (cadr data) d width)] [start (min (car range) (length lines))])
      (list-head (list-tail lines start) (min (cdr range) (- (length lines) start)))))
  (define (measure data d axis cross child)
    (if (eq? axis 'y) (let ([n (length (label-lines (cadr data) d cross))]) (list n n)) (list 0 (glyph:cells (cadr data)))))
  (define (decorate data d width height range)
    (let* ([id (car data)] [role (cond [(assq 'role (view:options d)) => cdr] [else #f])]
           [face (cond [(not (cadddr data)) 'ghost] [(and (hashtable-ref hover id #f) (caddr data)) 'hover] [else role])])
      (if (and face (zero? (car range))) (list (list (list 0 0 (min width (glyph:cells (cadr data))) 1) face)) '())))
  (define (inside? f inputs x y)
    (let* ([rect (widget:frame-rect f)] [clip (widget:frame-clip f)])
      (and (= y 0) (<= 0 x) (< x (glyph:cells (input inputs 'text "")))
        (layout:contains? clip (+ (car rect) x) (+ (cadr rect) y)))))
  (define (pointer-bindings f x y)
    (if (and (inside? f (widget:frame-inputs f) x y) (enabled? (widget:frame-id f)))
      (list (list '(click primary ()) (keymap:call activate! (widget:frame-id f)))) '()))
  (define (event! id source d event)
    (case (car event)
      [(cancel blur)
       (hashtable-delete! held id) (hashtable-delete! hover id) (widget:repaint! id)]
      [(pointer)
       (let-values ([(source d inputs) (widget:context id)])
         (let* ([phase (cadr event)] [inside (and (not (eq? phase 'leave)) (inside? (widget:event-frame) inputs (list-ref event 4) (list-ref event 5)))]
                [old (hashtable-ref hover id #f)])
           (if inside (hashtable-set! hover id #t) (hashtable-delete! hover id))
           (unless (eq? old inside) (widget:repaint! id))
           (case phase
             [(press) (and inside (eq? (caddr event) 'primary) (enabled? id)
                        (begin (widget:capture! id) (hashtable-set! held id #t) #t))]
             [(release)
              (let ([pressed (hashtable-ref held id #f)])
                (hashtable-delete! held id)
                (when (and pressed inside)
                  (let ([binding (assoc '(click primary ()) (pointer-bindings (widget:event-frame) (list-ref event 4) (list-ref event 5)))])
                    (when binding (keymap:run! (cadr binding)))))
                (and pressed #t))]
             [else (memq phase '(move leave))])))]))

  (edoc "Compose a label, an existing single-line text entry and status text; the root exposes the entry's text output."
        (actor datum "creator") (owner (or model #f) "lifetime owner, false for a session root") (source list "text buffer reference") (label string "label") (status string "status text") (returns model "root view"))
  (define (create-filter! actor owner source label status)
    (let* ([root (view:create! actor source 'filter 1 '((spacing . normal)) '() owner)]
           [label (view:create! actor #f 'label 1 (list (cons 'text label)) '() root)]
           [entry (view:create! actor source 'entry 1 '() '((0 . 0) (0 . 0)) root)]
           [status (view:create! actor #f 'label 1 (list (cons 'text status) '(role . ghost)) '() root)])
      (view:arrange! actor (list (list root 0 (list (list 'label label 'fit) (list 'entry entry '(grow 1)) (list 'status status 'fit)) '((spacing . normal)))) '())
      root))

  (edoc "Install filter, label and action-text presentations and their public keyboard actions." (public))
  (define (init!)
    (widget:register! 'filter 1 (layout:container 'x))
    (widget:register! 'label 1 (list (cons 'prepare data) (cons 'render render) (cons 'measure measure) (cons 'decorate decorate)))
    (widget:register! 'action-text 1
      (list (cons 'prepare data) (cons 'render render) (cons 'measure measure) (cons 'decorate decorate)
        (cons 'focus #t) (cons 'contexts '(widget-action)) (cons 'event event!) (cons 'pointer-bindings pointer-bindings) (cons 'service service!) (cons 'release release!) (cons 'actions (list (cons 'activate activate!)))))
    (keymap:bind-default! 'widget-action "RET" (keymap:call activate! widget:target))
    (keymap:bind-default! 'widget-action "SPC" (keymap:call activate! widget:target))))
