;; One bounded annotation query over a borrowed document; no copied text.
(import (only (foundation edoc) elibrary))
(elibrary (service change-preview)
  (export create!)
  (import (chezscheme) (prefix (core work-queue) work-queue:)
          (prefix (state connection) connection:) (prefix (state model) model:)
          (prefix (state store) store:) (prefix (state view) view:))
  (define (get r k) (cdr (assq k r)))
  (define (positive-integer? n) (and (integer? n) (exact? n) (> n 0)))
  (define kind (model:register-kind! 'change-preview 1
                 (lambda (v) (and (list? v) (for-all pair? v)
                               (equal? (map car v) '(document selection basis status annotations))
                               (positive-integer? (get v 'document)) (memq (get v 'status) '(pending ready unavailable))
                               (list? (get v 'annotations))))))
  (define worker (work-queue:create))
  (define lock (make-mutex))
  (define active (make-hashtable equal-hash equal?))
  (define (record id)
    (let ([r (model:snapshot id)]) (and r (eq? (get r 'kind) 'change-preview) r)))
  (define (spec document owner)
    (list 'change-preview 1 owner 'transient (list (list 'buffer document))
      (map cons '(document selection basis status annotations) (list document #f #f 'pending '()))))

  (edoc "Create a transient revision/conflict annotation query over a borrowed document. Connect selection to false or (revision entry)/(conflict entry); annotations contain at most one revision-bound span. Base workers locate it only while demanded. The owning view must declare this query in owned."
        (actor actor "creator") (document integer "borrowed document") (owner model "owning view") (returns model))
  (define (create! actor document owner)
    (unless (and (store:visible? actor document) (view:snapshot owner)) (error 'create! "document or owner is unavailable"))
    (apply model:create! actor (spec document owner)))
  (define (close! actor id)
    (let retry ()
      (let ([r (record id)])
        (when r (let-values ([(status ignored) (model:retire! actor id (get r 'revision))])
                  (when (eq? status 'stale) (retry)))))))
  (define (copy! actor r)
    (values (lambda (mapped) (spec (get (get r 'value) 'document) (mapped (get r 'scope)))) '() void))
  (define lifecycle (view:register-resource-kind! 'change-preview 1 copy! close!))
  (define (stamp r)
    (let* ([document (get (get r 'value) 'document)]
           [metadata (cadar (cadr (store:metadata (list document))))]
           [selection (connection:read (get r 'id) 'selection)])
      (list (list-head selection 2) (and metadata (get metadata 'version)) (map car (caddr selection)))))
  (define (current? id key)
    (let ([r (record id)]) (and r (model:demanded? id) (equal? key (stamp r)))))
  (define (publish! id key status annotations)
    (let retry ()
      (let ([r (record id)])
        (when (and r (current? id key))
          (let-values ([(status ignored)
                        (model:commit! '(base change-preview)
                          (list (list id (get r 'revision) (get r 'references)
                                  (map cons '(document selection basis status annotations)
                                    (list (get (get r 'value) 'document) #f key status annotations)))))])
            (when (eq? status 'stale) (retry)))))))
  (define (schedule! id)
    (let ([r (record id)])
      (if (not (and r (model:demanded? id))) (with-mutex lock (hashtable-delete! active id))
        (let* ([key (stamp r)] [document (get (get r 'value) 'document)]
               [needed? (with-mutex lock
                          (and (not (equal? key (hashtable-ref active id #f)))
                            (begin (hashtable-set! active id key) #t)))])
          (when needed?
            (work-queue:submit! worker id (lambda () (current? id key))
              (lambda (check!)
                (let ([selection (cadar key)])
                  (cond [(and (eq? (caar key) 'ready) (not selection)) (publish! id key 'ready '())]
                    [(and (cadr key) (eq? (caar key) 'ready) (list? selection) (= (length selection) 2)
                       (memq (car selection) '(revision conflict)) (positive-integer? (cadr selection)))
                     (let ([span ((if (eq? (car selection) 'revision) store:revision-span store:conflict-span) document (cadr selection))])
                       (check!)
                       (publish! id key (if (cadr span) 'ready 'unavailable)
                         (if (cadr span) (list document (car span) (list (list (cadr span) 'match))) '())))]
                    [else (publish! id key 'unavailable '())])))
              (lambda (ex) (publish! id key 'unavailable '()))))))))
  (define observers
    (list (model:observe-demand! (lambda (ids) (for-each schedule! ids)))
      (model:subscribe! #f
        (lambda (notice)
          (let-values ([(ids keys) (with-mutex lock (hashtable-entries active))])
            (vector-for-each (lambda (id key)
                               (when (or (not (cadr notice)) (member id (cadr notice))
                                       (exists (lambda (dep) (member dep (cadr notice))) (caddr key))) (schedule! id))) ids keys))))
      (store:subscribe! #f
        (lambda (event)
          (vector-for-each (lambda (id)
                             (let ([r (record id)])
                               (when (and r (= (cadr event) (get (get r 'value) 'document))) (schedule! id))))
            (with-mutex lock (hashtable-keys active))))))))
