;; Reviewed alternatives and picks belong to explicit base drafts.
(import (only (foundation edoc) elibrary))
(elibrary (service conflict-review)
  (export choose! close! create! preview refresh! settle!)
  (import (chezscheme) (prefix (foundation text) text:)
          (prefix (state model) model:) (prefix (state store) store:) (prefix (state view) view:))
  (define (get r k) (cdr (assq k r)))
  (define (natural? n) (and (integer? n) (exact? n) (>= n 0)))
  (define (document? n) (and (natural? n) (> n 0)))
  (define (unique? xs) (or (null? xs) (and (not (member (car xs) (cdr xs))) (unique? (cdr xs)))))
  (define (scope? xs) (and (list? xs) (for-all document? xs) (unique? xs)))
  (define (fields? v ks) (and (list? v) (for-all pair? v) (equal? (map car v) ks)))
  (define (alternative? c)
    (and (list? c) (= (length c) 6) (document? (car c)) (list? (caddr c))
      (guard (ex [else #f]) (text:datum->span (cadddr c)) #t)
      (for-all (lambda (lines) (and (list? lines) (pair? lines) (for-all string? lines))) (cddddr c))))
  (define (entry? e)
    (and (fields? e '(document basis alternatives mine invalidated)) (document? (get e 'document))
      (natural? (get e 'basis)) (list? (get e 'alternatives)) (for-all alternative? (get e 'alternatives))
      (unique? (map car (get e 'alternatives))) (scope? (get e 'mine)) (scope? (get e 'invalidated))
      (for-all (lambda (n) (assv n (get e 'alternatives))) (get e 'mine))))
  (define kind (model:register-kind! 'conflict-review 1
                 (lambda (v) (and (fields? v '(scope records)) (scope? (get v 'scope))
                               (list? (get v 'records)) (for-all entry? (get v 'records))
                               (unique? (map (lambda (e) (get e 'document)) (get v 'records)))
                               (for-all (lambda (d) (find (lambda (e) (= d (get e 'document))) (get v 'records))) (get v 'scope))))))
  (define lock (make-mutex))
  (define (record id)
    (let ([r (model:snapshot id)])
      (unless (and r (eq? (get r 'kind) 'conflict-review)) (error 'conflict-review "review is unavailable" id)) r))
  (define (current id revision)
    (let ([r (record id)])
      (unless (equal? revision (get r 'revision)) (error 'conflict-review "review changed")) r))
  (define (entry v document)
    (or (find (lambda (e) (= document (get e 'document))) (get v 'records))
      (error 'conflict-review "document is outside the review" document)))
  (define (replace r k v) (map (lambda (p) (if (eq? k (car p)) (cons k v) p)) r))
  (define (references records) (map (lambda (e) (list 'buffer (get e 'document))) records))
  (define (commit! actor r value)
    (unless (equal? value (get r 'value))
      (let-values ([(status rows) (model:commit! actor (list (list (get r 'id) (get r 'revision) (references (get value 'records)) value)))])
        (unless (eq? status 'applied) (error 'conflict-review "review changed"))))
    (record (get r 'id)))
  (define (span c) (text:datum->span (cadddr c)))
  (define (overlap? a b)
    (let ([a (span a)] [b (span b)])
      (or (equal? (text:span->datum a) (text:span->datum b)) (and (text:position<? (text:span-start a) (text:span-end b))
                                                               (text:position<? (text:span-start b) (text:span-end a))))))
  (define (disjoint! cs)
    (let loop ([cs cs])
      (when (pair? cs)
        (when (exists (lambda (b) (overlap? (car cs) b)) (cdr cs))
          (error 'choose! "Mine alternatives overlap; choose individually"))
        (loop (cdr cs)))))
  (define (capture document basis)
    ;; Retry only when a writer crossed the two coherent store reads.
    (let loop ([left 3])
      (let-values ([(text revision cs) (store:conflict-state document)])
        (if (or (not basis) (= basis revision)) (values text revision cs '())
          (let-values ([(unused end changes) (store:snapshot-since document basis)])
            (cond [(= revision end) (values text revision cs changes)]
              [(> left 0) (loop (- left 1))]
              [else (error 'conflict-review "document is changing; retry review")]))))))
  (define (same-alternative? old new changes)
    (or (equal? old new)
      (and changes (equal? (list-head old 3) (list-head new 3)) (equal? (cddddr old) (cddddr new))
           (let ([carried (fold-left (lambda (s change) (and s (text:rebase-span s (caddr change)))) (span old) changes)])
             (and carried (equal? (cadddr new) (text:span->datum carried)))))))
  (define (refreshed document old)
    (let-values ([(text revision cs changes) (capture document (and old (get old 'basis)))])
      (let* ([mine (if old (get old 'mine) '())]
             [kept (filter (lambda (n) (let ([next (assv n cs)])
                                         (and next (same-alternative? (assv n (get old 'alternatives)) next changes)))) mine)])
        (map cons '(document basis alternatives mine invalidated)
          (list document revision cs kept (filter (lambda (n) (not (memv n kept))) mine))))))

  (edoc "Create an independent persistent conflict review over an ordered, deduplicated scope of borrowed documents. Unpicked alternatives show Disk."
        (actor actor "creator") (scope (list-of integer) "document IDs") (returns model))
  (define (create! actor scope)
    (unless (and (scope? scope) (for-all (lambda (d) (store:visible? actor d)) scope)) (error 'create! "invalid review scope"))
    (let ([records (map (lambda (d) (refreshed d #f)) scope)])
      (model:create! actor 'conflict-review 1 'session 'persistent (references records)
        (list (cons 'scope scope) (cons 'records records)))))

  (edoc "Refresh a review and its explicit scope at the expected model revision. Retain picks only when exact alternatives or retained edit evidence proves their identity. Removed documents retain choices but cannot settle; changed picks are listed as invalidated. Return the updated envelope."
        (actor actor "caller") (id model "review") (revision integer "expected draft revision")
        (scope (list-of integer) "ordered document IDs") (returns list))
  (define (refresh! actor id revision scope)
    (unless (and (scope? scope) (for-all (lambda (d) (store:visible? actor d)) scope)) (error 'refresh! "invalid review scope"))
    (with-mutex lock
      (let* ([r (current id revision)] [old (get (get r 'value) 'records)]
             [records (append (map (lambda (d) (refreshed d (find (lambda (e) (= d (get e 'document))) old))) scope)
                        (filter (lambda (e) (not (memv (get e 'document) scope))) old))])
        (commit! actor r (list (cons 'scope scope) (cons 'records records))))))

  (edoc "Choose Mine or Disk for exact displayed alternatives. Groups are (document alternative ...). A single Mine choice displaces overlapping picks; multiple Mine choices must be disjoint. All groups validate before changing the draft. Return its envelope; no source is edited."
        (actor actor "caller") (id model "review") (revision integer "expected draft revision")
        (groups list "document and exact alternatives per group") (side (one-of mine disk) "choice") (returns list))
  (define (choose! actor id revision groups side)
    (unless (and (memq side '(mine disk)) (list? groups)
              (for-all (lambda (g) (and (pair? g) (document? (car g)) (list? (cdr g)) (for-all alternative? (cdr g)))) groups)
              (unique? (map car groups))) (error 'choose! "invalid choices"))
    (with-mutex lock
      (let* ([r (current id revision)] [v (get r 'value)])
        (for-each (lambda (g)
                    (unless (and (memv (car g) (get v 'scope))
                              (let ([e (entry v (car g))])
                                (and (equal? (get e 'alternatives) (store:conflicts (car g)))
                                  (for-all (lambda (c) (member c (get e 'alternatives))) (cdr g)))))
                      (error 'choose! "conflict alternatives changed; refresh the review"))
                    (when (eq? side 'mine) (disjoint! (cdr g)))) groups)
        (commit! actor r
          (replace v 'records
            (map (lambda (e)
                   (let ([g (assv (get e 'document) groups)])
                     (if (not g) e
                       (replace e 'mine
                         (fold-left (lambda (mine c)
                                      (let ([kept (filter (lambda (n) (and (not (= n (car c)))
                                                                        (or (eq? side 'disk) (not (overlap? c (assv n (get e 'alternatives))))))) mine)])
                                        (if (eq? side 'mine) (cons (car c) kept) kept))) (get e 'mine) (cdr g))))))
              (get v 'records)))))))

  (define (project text conflicts mine)
    (let loop ([cs (list-sort (lambda (a b) (text:position<? (text:span-start (span a)) (text:span-start (span b)))) conflicts)]
               [text text] [deltas '()] [regions '()])
      (if (null? cs) (values text (reverse regions))
        (let* ([c (car cs)]
               [region (fold-left (lambda (s d)
                                    (or (text:rebase-span s d)
                                      (let ([a (text:rebase-position (text:span-start s) d)] [z (text:rebase-position (text:span-end s) d 'stay)])
                                        (text:make-span (car a) (cdr a) (car z) (cdr z))))) (span c) (reverse deltas))])
          (if (memv (car c) mine)
            (let-values ([(next delta) (text:apply-edit text region (list-ref c 4))])
              (let ([a (text:span-start (text:delta-span delta))] [z (text:delta-new-end delta)])
                (loop (cdr cs) next (cons delta deltas)
                  (cons (list (car c) 'mine (text:span->datum (text:make-span (car a) (cdr a) (car z) (cdr z)))) regions))))
            (loop (cdr cs) text deltas (cons (list (car c) 'disk (text:span->datum region)) regions)))))))

  (edoc "Derive read-only preview text and semantic regions from an explicit reviewed document. Return (draft-revision document source-revision text regions). Refuse changed alternatives instead of projecting stale coordinates."
        (id model "review") (document integer "scoped source") (returns list))
  (define (preview id document)
    (let* ([r (record id)] [v (get r 'value)] [e (entry v document)])
      (unless (memv document (get v 'scope)) (error 'preview "document is outside the review scope"))
      (let-values ([(text revision cs) (store:conflict-state document)])
        (unless (equal? cs (get e 'alternatives)) (error 'preview "conflict alternatives changed; refresh the review"))
        (let-values ([(text regions) (project text cs (get e 'mine))])
          (list (get r 'revision) document revision text regions)))))

  (edoc "Settle explicit documents in the review's current scope against complete displayed alternatives, including Disk. Return (document status detail) results; each source settles atomically and undoably. Refused documents retain their choices. This operation never refreshes stale witnesses before writing."
        (actor actor "caller") (id model "review") (revision integer "expected draft revision")
        (documents (list-of integer) "ordered subset of current scope") (returns list))
  (define (settle! actor id revision documents)
    (with-mutex lock
      (let* ([r (current id revision)] [v (get r 'value)])
        (unless (and (scope? documents) (for-all (lambda (d) (memv d (get v 'scope))) documents))
          (error 'settle! "documents are outside the review scope"))
        (let* (
               [results (map (lambda (d)
                               (let ([e (entry v d)])
                                 (let-values ([(status detail) (store:resolve-picks! actor d (get e 'alternatives) (get e 'mine) 'any)])
                                   (list d status detail)))) documents)])
          (commit! actor r (replace v 'records
                             (map (lambda (e) (let ([result (assv (get e 'document) results)])
                                                (if (and result (eq? (cadr result) 'applied))
                                                  (map cons '(document basis alternatives mine invalidated) (list (car result) (caddr result) '() '() '()))
                                                  e))) (get v 'records))))
          results))))

  (edoc "Retire a review and its scoped views at the expected revision, preserving all borrowed sources."
        (actor actor "caller") (id model "review") (revision integer "expected draft revision"))
  (define (close! actor id revision)
    (with-mutex lock
      (current id revision)
      (let-values ([(status r) (model:retire! actor id revision)])
        (when (eq? status 'applied) (view:retire-scope! actor id)) status))))
