;; Indexed history rows over an independent rewrite draft.
(import (only (foundation edoc) elibrary))
(elibrary (service rewrite-source)
  (export settle! toggle!)
  (import (chezscheme) (prefix (core kernel) kernel:) (prefix (core row) row:)
          (prefix (core work-queue) work-queue:) (prefix (foundation string) string:)
          (prefix (service rewrite) rewrite:) (prefix (state collection) collection:)
          (prefix (state model) model:) (prefix (state store) store:))
  (define (get r k) (cdr (assq k r)))
  (define worker (work-queue:create))
  (define lock (make-mutex))
  (define jobs (make-hashtable equal-hash equal?))
  (define-record-type job (fields query draft document selector cancelled? publish (mutable stamp)))
  (define (record id)
    (let ([r (model:snapshot id)])
      (unless (and r (eq? (get r 'kind) 'rewrite-draft)) (error 'rewrite-source "draft is unavailable")) r))
  (define (alive? j)
    (and (with-mutex lock (eq? j (hashtable-ref jobs (job-query j) #f)))
         (model:demanded? (job-query j)) (not ((job-cancelled? j)))))
  (define columns '((revision "Rev" integer) (actor "Actor" datum) (position "At" datum)
                    (removed "Removed" string) (inserted "Inserted" string)
                    (state "State" symbol) (choice "Preview" symbol) (labels "Labels" datum)))
  (define (prepare! j check!)
    (let* ([r (record (job-draft j))] [v (get r 'value)] [document (job-document j)]
           [revision (store:revision document)] [stamp (list (get r 'revision) revision)])
      (unless (equal? stamp (job-stamp j))
        (let* ([entries (store:log document (job-selector j))] [positions (make-hashtable equal-hash equal?)]
               [rows (list->vector
                       (map (lambda (e)
                              (check!)
                              (let ([delta (list-ref e 3)])
                                (list (list document (car e))
                                  (map cons '(revision actor position removed inserted state choice labels)
                                    (list (car e) (cadr e) (list-head (car delta) 2)
                                      (string:join (cadr delta) "\n") (string:join (caddr delta) "\n")
                                      (list-ref e 5) (if (memv (car e) (get v 'disabled)) 'omit 'keep) (caddr e))) '()))) entries))]
               [n (vector-length rows)])
          (check!)
          (unless (= revision (store:revision document)) (error 'rewrite-source "source changed while preparing history"))
          (do ([i 0 (+ i 1)]) ((= i n)) (check!) (hashtable-set! positions (car (vector-ref rows i)) i))
          ((job-publish j)
           (collection:make-result columns n (lambda (i) (vector-ref rows i))
             (lambda (key) (hashtable-ref positions key #f))
             (lambda (at direction offset) (and (> n 0) (max 0 (min (- n 1) (+ at (if (eq? direction 'forward) offset (- offset)))))))
             (list '(sortable) (cons 'details (list (cons 'draft (job-draft j)) (cons 'revision (get r 'revision))
                                                (cons 'source-revision revision))))) #f)
          (job-stamp-set! j stamp)))))
  (define (queue! j)
    (work-queue:submit! worker (job-query j) (lambda () (alive? j)) (lambda (check!) (prepare! j check!))
      (lambda (ex) (job-stamp-set! j #f) ((job-publish j) #f (kernel:condition-text ex)))))
  (define changes
    (store:subscribe! #f (lambda (event)
                           (for-each (lambda (j) (when (equal? (cadr event) (job-document j)) (queue! j)))
                             (with-mutex lock (vector->list (hashtable-values jobs)))))))
  (define demand
    (model:observe-demand! (lambda (ids)
                             (with-mutex lock (for-each (lambda (id) (unless (model:demanded? id) (hashtable-delete! jobs id))) ids)))))
  (define (start! source query cancelled? publish)
    (unless (null? (get query 'sort))
      (error 'start! "Rewrite history retains revision order"))
    (let* ([input (get query 'filter)]
           [selector (if (string=? input "") '()
                       (let* ([p (open-input-string input)] [value (read p)])
                         (unless (and (list? value) (eof-object? (read p))) (error 'start! "expected a history selector")) value))]
           [j (make-job (get query 'id) (get source 'id) (get (get source 'value) 'document) selector cancelled? publish #f)])
      (with-mutex lock (hashtable-set! jobs (job-query j) j)) (queue! j)))
  (define provider (collection:register! 'rewrite-draft 1 start!))
  (define (review query generation basis)
    (let* ([meta (collection:summary query)] [v (and meta (get meta 'value))]
           [details (and v (assq 'details v))])
      (unless (and details (eq? (get v 'status) 'ready) (= generation (get v 'generation))
                (equal? basis (get v 'basis)) (assq 'draft (cdr details)) (assq 'source-revision (cdr details)))
        (error 'rewrite-source "shown history changed"))
      (let ([r (record (get (cdr details) 'draft))])
        (unless (and (equal? (get v 'source) (get r 'id)) (= (get r 'revision) (get (cdr details) 'revision))
                  (= (store:revision (get (get r 'value) 'document)) (get (cdr details) 'source-revision)))
          (error 'rewrite-source "draft or source changed; review the current history")) r)))

  (edoc "Toggle the exact displayed history entry in its independent rewrite draft. Query generation, source revision and draft revision fence the command."
        (actor actor "caller") (selection row-selection "shown query, generation and entry key") (basis datum "shown result basis"))
  (define (toggle! actor selection basis)
    (unless (row:selection? selection) (error 'toggle! "expected a shown selection"))
    (let* ([r (review (car selection) (cadr selection) basis)] [key (caddr selection)]
           [row (collection:lookup (car selection) (cadr selection) key '())])
      (unless (and (eq? (car row) 'ready) (pair? (list-ref row 4))) (error 'toggle! "entry is unavailable"))
      (rewrite:toggle! actor (get r 'id) (get r 'revision) (list (cadr key))) (void)))

  (edoc "Settle the exact displayed rewrite draft. Return (status detail); stale history refuses without changing choices."
        (actor actor "caller") (query row-source "history rows") (generation integer "shown generation")
        (basis datum "shown result basis") (returns list))
  (define (settle! actor query generation basis)
    (let ([r (review query generation basis)])
      (call-with-values (lambda () (rewrite:settle! actor (get r 'id) (get r 'revision))) list))))
