;; Explicit incremental-search requests; no head, window or terminal geometry.
(import (only (foundation edoc) elibrary))
(elibrary (service search-request)
  (export close! close-owner! configure! create!)
  (import (chezscheme) (prefix (core descriptor) descriptor:) (prefix (core handle) handle:) (prefix (core kernel) kernel:)
          (prefix (core work-queue) work-queue:) (prefix (foundation string) string:)
          (prefix (foundation text) text:) (prefix (state model) model:)
          (prefix (state store) store:) (prefix (state view) view:))
  (define (get r k) (cdr (assq k r)))
  (define (natural? n) (and (integer? n) (exact? n) (>= n 0)))
  (define (position? p) (and (pair? p) (natural? (car p)) (natural? (cdr p))))
  (define (fields? v keys) (and (list? v) (for-all pair? v) (equal? (map car v) keys)))
  (define (request? v)
    (and (fields? v '(target document basis sequence start needle fold? visible direction summary? overlap?))
      (model:reference? (get v 'target)) (handle:buffer? (get v 'document))
      (natural? (get v 'basis)) (natural? (get v 'sequence)) (position? (get v 'start))
      (string? (get v 'needle)) (not (string:search (get v 'needle) "\n" 0 (string-length (get v 'needle))))
      (boolean? (get v 'fold?)) (memq (get v 'direction) '(next previous)) (boolean? (get v 'summary?)) (boolean? (get v 'overlap?))
      (guard (ex [else #f]) (text:datum->span (get v 'visible)) #t)))
  (define (valid? v)
    (and (fields? v '(owner draft origin generation request status result))
      (let ([draft (get v 'draft)])
        (or (not draft) (and (list? draft) (= (length draft) 2) (eq? (car draft) 'buffer) (natural? (cadr draft)) (> (cadr draft) 0))))
      (descriptor:head? (get v 'owner)) (request? (get v 'origin)) (request? (get v 'request))
      (natural? (get v 'generation)) (memq (get v 'status) '(pending ready unavailable))))
  (define kind (model:register-kind! 'search-request 1 valid?))
  (define worker (work-queue:create))
  (define lock (make-mutex))
  (define active (make-hashtable equal-hash equal?))
  (define (record id)
    (let ([r (model:snapshot id)]) (and r (eq? (get r 'kind) 'search-request) r)))
  (define (owned r actor) (and r (equal? actor (get (get r 'value) 'owner))))
  (define (available? actor request)
    (let ([d (view:snapshot (get request 'target))])
      (and d (eq? (view:kind d) 'editor)
        (equal? (view:source d) (get request 'document))
        (store:visible? actor (get request 'document)))))
  (define (references origin request)
    (fold-left (lambda (out id) (if (member id out) out (cons id out))) '()
      (list (get origin 'target) (get origin 'document)
        (get request 'target) (get request 'document))))
  (define (change r value)
    (list (get r 'id) (get r 'revision) (filter values (cons (get value 'draft) (references (get value 'origin) (get value 'request)))) value))
  (define (replace v key value) (map (lambda (p) (if (eq? (car p) key) (cons key value) p)) v))

  (edoc "Create a transient search request with an explicit editor/document basis, starting anchor, needle, case and overlap policies, direction and visible logical span. Publish one match and bounded annotations first; an optional summary counts matches cooperatively afterward without retaining their positions. The initial request captures the cancellation origin."
        (actor actor "requesting head") (request list "ordered target/document/basis/sequence/start/needle/fold?/visible/direction/summary?/overlap? alist")
        (draft? boolean "create an owned authored entry draft; false for externally supplied needles") (returns model))
  (define (create! actor request draft?)
    (unless (and (descriptor:head? actor) (request? request) (boolean? draft?) (available? actor request))
      (error 'create! "invalid or unavailable search target"))
    (let ([draft
           (and draft?
             (store:create!
               actor
               "<search>"
               (list (get request 'needle))
               (list
                 '(internal . #t)
                 '(disposable . #t)
                 (cons 'audience (list actor)))))])
      (guard (ex [else (when draft (store:delete! actor draft)) (raise ex)])
        (model:create! actor 'search-request 1 actor 'transient (filter values (cons draft (references request request)))
          (map cons '(owner draft origin generation request status result) (list actor draft request 0 request 'pending #f))))))

  (edoc "Replace a search request against its request generation; result publications do not invalidate this fence. Retargeting keeps the original cancellation receiver. Return the new generation, or false for a superseded, closed or unavailable request."
        (actor actor "request owner") (id model "search request") (generation integer "expected request generation")
        (request list "same fields as create!") (returns (or integer #f)))
  (define (configure! actor id generation request)
    (unless (and (natural? generation) (request? request)) (error 'configure! "invalid search request"))
    (let retry ()
      (let ([r (record id)])
        (and (owned r actor) (= generation (get (get r 'value) 'generation)) (available? actor request)
          (let* ([v (get r 'value)] [next (+ generation 1)]
                 [v (replace (replace (replace (replace v 'request request) 'generation next) 'status 'pending) 'result #f)])
            (let-values ([(status rows) (model:commit! actor (list (change r v)))])
              (case status [(applied) next] [(stale) (retry)] [else #f])))))))

  (edoc "Close an owned search request. Borrowed editors and documents survive; late work cannot recreate the request."
        (actor actor "request owner") (id model "search request"))
  (define (close! actor id)
    (let retry ()
      (let ([r (record id)])
        (when (owned r actor)
          (let-values ([(status current) (model:retire! actor id (get r 'revision))])
            (case status [(stale) (retry)]
              [(applied) (view:retire-scope! actor id)
               (let ([draft (get (get r 'value) 'draft)])
                 (when (and draft (store:exists? draft)) (store:delete! actor draft)))]))))))

  (edoc "Close all transient search requests belonging to a departing head."
        (actor actor "departing request owner"))
  (define (close-owner! actor)
    (for-each (lambda (id) (close! actor id)) (model:ids 'search-request)))

  (define (signature r)
    (let* ([v (get r 'value)] [request (get v 'request)])
      (list (get v 'generation)
        (guard (ex [else #f])
          (and (available? (get v 'owner) request) (store:revision (get request 'document)))))))
  (define (live? id stamp)
    (let ([r (record id)]) (and r (model:demanded? id) (equal? stamp (signature r)))))
  (define (publish! id stamp status result)
    (let retry ()
      (let ([r (record id)])
        (when (and r (model:demanded? id) (equal? stamp (signature r)))
          (let* ([v (get r 'value)] [next (replace (replace v 'status status) 'result result)])
            (let-values ([(status rows) (model:commit! (get v 'owner) (list (change r next)))])
              (when (eq? status 'stale) (retry))))))))
  (define (scan request check!)
    (let-values ([(lines revision changes) (store:snapshot-since (get request 'document) (get request 'basis))])
      (unless changes (error 'scan "Search anchor history is unavailable"))
      (let* ([deltas (map caddr changes)] [needle (get request 'needle)] [n (string-length needle)]
             [find (string:searcher needle (get request 'fold?) check!)] [last (- (vector-length lines) 1)])
        (define (rebase p)
          (let* ([p (fold-left text:rebase-position p deltas)] [row (min last (car p))])
            (cons row (min (cdr p) (string-length (vector-ref lines row))))))
        (define (find-next row first limit)
          (check!) (let ([hit (find (vector-ref lines row) first limit)]) (and hit (cons row hit))))
        (define (find-in row first limit)
          (check!)
          (let loop ([at (if (get request 'overlap?) first 0)])
            (let ([hit (find (vector-ref lines row) at limit)])
              (and hit (if (< hit first) (loop (+ hit (max 1 n))) (cons row hit))))))
        (define (find-last row first limit)
          (let loop ([p (find-in row first (string-length (vector-ref lines row)))] [last #f])
            (if (and p (< (cdr p) limit))
              (loop (find-next row (+ (if (get request 'overlap?) 1 n) (cdr p)) (string-length (vector-ref lines row))) p) last)))
        (let* ([start (rebase (get request 'start))]
               [hit (and (> n 0)
                      (if (eq? (get request 'direction) 'previous)
                        (or (let seek ([row (car start)] [end (cdr start)])
                              (and (>= row 0) (or (find-last row 0 end)
                                                (seek (- row 1) (if (> row 0) (+ 1 (string-length (vector-ref lines (- row 1)))) 0)))))
                          (let wrap ([row last])
                            (and (>= row (car start))
                              (or (find-last row (if (= row (car start)) (cdr start) 0) (+ 1 (string-length (vector-ref lines row))))
                                (wrap (- row 1))))))
                        (or (let seek ([row (car start)] [col (cdr start)])
                              (and (<= row last)
                                (or (find-in row col (string-length (vector-ref lines row))) (seek (+ row 1) 0))))
                          (let wrap ([row 0])
                            (and (<= row (car start))
                              (or (find-in row 0 (if (= row (car start))
                                                   (min (string-length (vector-ref lines row)) (+ (cdr start) n -1))
                                                   (string-length (vector-ref lines row))))
                                (wrap (+ row 1))))))))]
               [span (text:datum->span (get request 'visible))]
               [from (rebase (text:span-start span))] [to (rebase (text:span-end span))]
               [truncated? #f] [matches '()] [count 0])
          (when (> n 0)
            (let rows ([row (car from)])
              (when (<= row (car to))
                (if (or (= count 512) (>= (- row (car from)) 256)) (set! truncated? #t)
                  (let cols ([at (if (= row (car from)) (cdr from) 0)] [first? #t])
                    (let* ([line (vector-ref lines row)] [limit (if (= row (car to)) (min (string-length line) (+ (cdr to) n -1)) (string-length line))]
                           [p (and (< at limit) ((if first? find-in find-next) row at limit))])
                      (cond [(not p) (rows (+ row 1))]
                        [(= count 512) (set! truncated? #t)]
                        [else (set! count (+ count 1))
                          (set! matches (cons (list (list row (cdr p) row (+ (cdr p) n)) 'match) matches))
                          (cols (+ (cdr p) (if (get request 'overlap?) 1 n)) #f)])))))))
          (when hit (set! matches (cons (list (list (car hit) (cdr hit) (car hit) (+ (cdr hit) n)) 'match-point) matches)))
          (values (map cons '(basis hit annotations truncated? ordinal count)
                    (list revision hit (list (get request 'document) revision (reverse matches)) truncated? #f #f)) lines)))))
  (define (summarize request result lines check!)
    (let* ([needle (get request 'needle)] [n (string-length needle)] [hit (get result 'hit)]
           [find (string:searcher needle (get request 'fold?) check!)] [count 0] [ordinal #f])
      (when (> n 0)
        (do ([row 0 (+ row 1)]) ((= row (vector-length lines)))
          (check!)
          (let cols ([at 0])
            (let ([col (find (vector-ref lines row) at (string-length (vector-ref lines row)))])
              (when col
                (set! count (+ count 1))
                (when (equal? hit (cons row col)) (set! ordinal count))
                (cols (+ col (if (get request 'overlap?) 1 n))))))))
      (replace (replace result 'ordinal ordinal) 'count count)))
  (define (schedule! id)
    (let ([r (record id)])
      (if (not (and r (model:demanded? id))) (with-mutex lock (hashtable-delete! active id))
        (let* ([stamp (signature r)] [v (get r 'value)] [request (get v 'request)]
               [needed? (with-mutex lock
                          (let ([old (hashtable-ref active id #f)])
                            (and (not (equal? old (list stamp request)))
                              (begin (hashtable-set! active id (list stamp request)) #t))))])
          (when needed?
            (work-queue:submit! worker id (lambda () (live? id stamp))
              (lambda (check!)
                (if (cadr stamp)
                  (let-values ([(result lines) (scan request check!)])
                    (publish! id stamp 'ready result)
                    (when (get request 'summary?)
                      (publish! id stamp 'ready (summarize request result lines check!))))
                  (publish! id stamp 'unavailable "Search target is unavailable")))
              (lambda (ex) (publish! id stamp 'unavailable (kernel:condition-text ex)))))))))
  (define observers
    (list (model:observe-demand! (lambda (ids) (for-each schedule! ids)))
      (model:subscribe! #f
        (lambda (notice)
          (let-values ([(ids jobs) (with-mutex lock (hashtable-entries active))])
            (vector-for-each (lambda (id job)
                               (when (or (not (cadr notice)) (member id (cadr notice))
                                       (member (get (cadr job) 'target) (cadr notice))) (schedule! id))) ids jobs))))
      (store:subscribe! #f
        (lambda (event)
          (let-values ([(ids jobs) (with-mutex lock (hashtable-entries active))])
            (vector-for-each (lambda (id job) (when (equal? (cadr event) (get (cadr job) 'document)) (schedule! id))) ids jobs)))))))
