;; Explicit incremental-search requests; no head, window or terminal geometry.
(import (only (foundation edoc) elibrary))
(elibrary (service search-request)
  (export close! close-owner! configure! create!)
  (import (chezscheme) (prefix (core descriptor) descriptor:) (prefix (core kernel) kernel:)
          (prefix (core work-queue) work-queue:) (prefix (foundation string) string:)
          (prefix (foundation text) text:) (prefix (state model) model:)
          (prefix (state store) store:) (prefix (state view) view:))
  (define (get r k) (cdr (assq k r)))
  (define (natural? n) (and (integer? n) (exact? n) (>= n 0)))
  (define (position? p) (and (pair? p) (natural? (car p)) (natural? (cdr p))))
  (define (fields? v keys) (and (list? v) (for-all pair? v) (equal? (map car v) keys)))
  (define (request? v)
    (and (fields? v '(target document basis sequence start needle fold? visible))
      (model:reference? (get v 'target)) (natural? (get v 'document)) (> (get v 'document) 0)
      (natural? (get v 'basis)) (natural? (get v 'sequence)) (position? (get v 'start))
      (string? (get v 'needle)) (not (string:search (get v 'needle) "\n" 0 (string-length (get v 'needle))))
      (boolean? (get v 'fold?))
      (guard (ex [else #f]) (text:datum->span (get v 'visible)) #t)))
  (define (valid? v)
    (and (fields? v '(owner draft origin generation request status result))
      (let ([draft (get v 'draft)])
        (and (list? draft) (= (length draft) 2) (eq? (car draft) 'buffer) (natural? (cadr draft)) (> (cadr draft) 0)))
      (descriptor:head? (get v 'owner)) (request? (get v 'origin)) (request? (get v 'request))
      (natural? (get v 'generation)) (memq (get v 'status) '(pending ready unavailable))))
  (define kind (model:register-kind! 'search-request 1 valid?))
  (define worker (work-queue:create))
  (define lock (make-mutex))
  (define active (make-hashtable equal-hash equal?))
  (define (record id)
    (let ([r (model:snapshot id)]) (and r (eq? (get r 'kind) 'search-request) r)))
  (define (owned r actor) (and r (equal? actor (get (get r 'value) 'owner))))
  (define (available? actor request)
    (let ([d (view:snapshot (get request 'target))])
      (and d (eq? (view:kind d) 'editor)
        (equal? (view:source d) (list 'buffer (get request 'document)))
        (store:visible? actor (get request 'document)))))
  (define (references origin request)
    (fold-left (lambda (out id) (if (member id out) out (cons id out))) '()
      (list (get origin 'target) (list 'buffer (get origin 'document))
        (get request 'target) (list 'buffer (get request 'document)))))
  (define (change r value)
    (list (get r 'id) (get r 'revision) (cons (get value 'draft) (references (get value 'origin) (get value 'request))) value))
  (define (replace v key value) (map (lambda (p) (if (eq? (car p) key) (cons key value) p)) v))

  (edoc "Create a transient search request naming an editor, document, basis, interaction sequence, start position, needle, fold? policy and visible logical span. The initial request also captures the cancellation origin. Results contain one next match and a bounded annotation batch; no complete match list is built."
        (actor actor "requesting head") (request list "ordered target/document/basis/sequence/start/needle/fold?/visible alist") (returns model))
  (define (create! actor request)
    (unless (and (descriptor:head? actor) (request? request) (available? actor request))
      (error 'create! "invalid or unavailable search target"))
    (let ([draft (list 'buffer (store:create! actor "<search>" (list (get request 'needle))
                                 (list '(internal . #t) '(disposable . #t) (cons 'audience (list actor)))))])
      (guard (ex [else (store:delete! actor (cadr draft)) (raise ex)])
        (model:create! actor 'search-request 1 actor 'transient (cons draft (references request request))
          (map cons '(owner draft origin generation request status result) (list actor draft request 0 request 'pending #f))))))

  (edoc "Replace a search request against its request generation; result publications do not invalidate this fence. Retargeting keeps the original cancellation receiver. Return the new generation, or false for a superseded, closed or unavailable request."
        (actor actor "request owner") (id model "search request") (generation integer "expected request generation")
        (request list "same fields as create!") (returns (or integer #f)))
  (define (configure! actor id generation request)
    (unless (and (natural? generation) (request? request)) (error 'configure! "invalid search request"))
    (let retry ()
      (let ([r (record id)])
        (and (owned r actor) (= generation (get (get r 'value) 'generation)) (available? actor request)
          (let* ([v (get r 'value)] [next (+ generation 1)]
                 [v (replace (replace (replace (replace v 'request request) 'generation next) 'status 'pending) 'result #f)])
            (let-values ([(status rows) (model:commit! actor (list (change r v)))])
              (case status [(applied) next] [(stale) (retry)] [else #f])))))))

  (edoc "Close an owned search request. Borrowed editors and documents survive; late work cannot recreate the request."
        (actor actor "request owner") (id model "search request"))
  (define (close! actor id)
    (let retry ()
      (let ([r (record id)])
        (when (owned r actor)
          (let-values ([(status current) (model:retire! actor id (get r 'revision))])
            (case status [(stale) (retry)]
              [(applied) (view:retire-scope! actor id)
               (let ([draft (cadr (get (get r 'value) 'draft))])
                 (when (store:exists? draft) (store:delete! actor draft)))]))))))

  (edoc "Close all transient search requests belonging to a departing head."
        (actor actor "departing request owner"))
  (define (close-owner! actor)
    (for-each (lambda (id) (close! actor id)) (model:ids 'search-request)))

  (define (signature r)
    (let* ([v (get r 'value)] [request (get v 'request)])
      (list (get v 'generation)
        (guard (ex [else #f])
          (and (available? (get v 'owner) request) (store:revision (get request 'document)))))))
  (define (live? id stamp)
    (let ([r (record id)]) (and r (model:demanded? id) (equal? stamp (signature r)))))
  (define (publish! id stamp status result)
    (let retry ()
      (let ([r (record id)])
        (when (and r (model:demanded? id) (equal? stamp (signature r)))
          (let* ([v (get r 'value)] [next (replace (replace v 'status status) 'result result)])
            (let-values ([(status rows) (model:commit! (get v 'owner) (list (change r next)))])
              (when (eq? status 'stale) (retry))))))))
  (define (scan request check!)
    (let-values ([(lines revision changes) (store:snapshot-since (get request 'document) (get request 'basis))])
      (unless changes (error 'scan "Search anchor history is unavailable"))
      (let* ([deltas (map caddr changes)] [needle (get request 'needle)] [n (string-length needle)]
             [find (string:searcher needle (get request 'fold?) check!)] [last (- (vector-length lines) 1)])
        (define (rebase p)
          (let* ([p (fold-left text:rebase-position p deltas)] [row (min last (car p))])
            (cons row (min (cdr p) (string-length (vector-ref lines row))))))
        (define (find-in row first limit)
          (check!) (let ([hit (find (vector-ref lines row) first limit)]) (and hit (cons row hit))))
        (let* ([start (rebase (get request 'start))]
               [hit (and (> n 0)
                      (or (let seek ([row (car start)] [col (cdr start)])
                            (and (<= row last)
                              (or (find-in row col (string-length (vector-ref lines row))) (seek (+ row 1) 0))))
                        (let wrap ([row 0])
                          (and (<= row (car start))
                            (or (find-in row 0 (if (= row (car start))
                                                 (min (string-length (vector-ref lines row)) (+ (cdr start) n -1))
                                                 (string-length (vector-ref lines row))))
                              (wrap (+ row 1)))))))]
               [span (text:datum->span (get request 'visible))]
               [from (rebase (text:span-start span))] [to (rebase (text:span-end span))]
               [truncated? #f] [matches '()] [count 0])
          (when (> n 0)
            (let rows ([row (car from)])
              (when (<= row (car to))
                (if (or (= count 512) (>= (- row (car from)) 256)) (set! truncated? #t)
                  (let cols ([at (if (= row (car from)) (cdr from) 0)])
                    (let* ([line (vector-ref lines row)] [limit (if (= row (car to)) (min (string-length line) (+ (cdr to) n -1)) (string-length line))]
                           [p (and (< at limit) (find-in row at limit))])
                      (cond [(not p) (rows (+ row 1))]
                        [(= count 512) (set! truncated? #t)]
                        [else (set! count (+ count 1))
                          (set! matches (cons (list (list row (cdr p) row (+ (cdr p) n)) 'match) matches))
                          (cols (+ (cdr p) 1))])))))))
          (when hit (set! matches (cons (list (list (car hit) (cdr hit) (car hit) (+ (cdr hit) n)) 'match-point) matches)))
          (map cons '(basis hit annotations truncated?)
            (list revision hit (list (get request 'document) revision (reverse matches)) truncated?))))))
  (define (schedule! id)
    (let ([r (record id)])
      (if (not (and r (model:demanded? id))) (with-mutex lock (hashtable-delete! active id))
        (let* ([stamp (signature r)] [v (get r 'value)] [request (get v 'request)]
               [needed? (with-mutex lock
                          (let ([old (hashtable-ref active id #f)])
                            (and (not (equal? old (list stamp request)))
                              (begin (hashtable-set! active id (list stamp request)) #t))))])
          (when needed?
            (work-queue:submit! worker id (lambda () (live? id stamp))
              (lambda (check!)
                (if (cadr stamp) (publish! id stamp 'ready (scan request check!))
                  (publish! id stamp 'unavailable "Search target is unavailable")))
              (lambda (ex) (publish! id stamp 'unavailable (kernel:condition-text ex)))))))))
  (define observers
    (list (model:observe-demand! (lambda (ids) (for-each schedule! ids)))
      (model:subscribe! #f
        (lambda (notice)
          (let-values ([(ids jobs) (with-mutex lock (hashtable-entries active))])
            (vector-for-each (lambda (id job)
                               (when (or (not (cadr notice)) (member id (cadr notice))
                                       (member (get (cadr job) 'target) (cadr notice))) (schedule! id))) ids jobs))))
      (store:subscribe! #f
        (lambda (event)
          (let-values ([(ids jobs) (with-mutex lock (hashtable-entries active))])
            (vector-for-each (lambda (id job) (when (= (cadr event) (get (cadr job) 'document)) (schedule! id))) ids jobs)))))))
