;; Keyed cooperative work, outside store writers and UI event pumps.
(import (only (foundation edoc) elibrary))
(elibrary (core work-queue)
  (export create submit!)
  (import (chezscheme) (prefix (sys sys) sys:))
  (define-record-type queue
    (fields lock ready jobs (mutable order) (mutable started?) (mutable leave)))
  (define-record-type job (fields key alive? failed (mutable run)))

  (edoc "Create a lazy cooperative worker. Jobs with equal keys supersede older work; domain checkpoints yield between jobs, never under a store writer."
        (returns any))
  (define (create) (make-queue (make-mutex) (make-condition) (make-hashtable equal-hash equal?) '() #f #f))
  (define (current? q job)
    (with-mutex (queue-lock q) (eq? job (hashtable-ref (queue-jobs q) (job-key job) #f))))
  (define (finish! q job)
    (with-mutex (queue-lock q)
      (when (eq? job (hashtable-ref (queue-jobs q) (job-key job) #f))
        (hashtable-delete! (queue-jobs q) (job-key job)))))
  (define (work! q)
    (let loop ()
      (let ([job (with-mutex (queue-lock q)
                   (let wait () (when (null? (queue-order q)) (condition-wait (queue-ready q) (queue-lock q)) (wait)))
                   (let ([key (car (queue-order q))])
                     (queue-order-set! q (cdr (queue-order q))) (hashtable-ref (queue-jobs q) key #f)))])
        (when job
          (call/cc
            (lambda (leave)
              (queue-leave-set! q leave)
              (guard (ex [else (when (and (current? q job) ((job-alive? job))) ((job-failed job) ex))])
                ((job-run job)))
              (finish! q job)))))
      (loop)))

  (edoc "Queue bounded-checkpoint work on one background worker. Replacing a key cancels its old continuation. The task receives a checkpoint procedure; alive? fences external generations and demand. Failures are delivered only while the task is current."
        (queue any "worker") (key datum "coalescing identity") (alive? procedure "nonblocking validity check")
        (run procedure "(checkpoint) -> result") (failed procedure "condition handler"))
  (define (submit! queue key alive? run failed)
    (let ([job (make-job key alive? failed #f)] [deadline (sys:after 0.005)] [ticks 0])
      (define (check!)
        (set! ticks (+ ticks 1))
        (when (or (= ticks 1) (zero? (mod ticks 32)))
          (unless (and (current? queue job) (alive?))
            (finish! queue job) ((queue-leave queue) #f))
          (when (time>=? (current-time 'time-monotonic) deadline)
            (when (with-mutex (queue-lock queue) (pair? (queue-order queue)))
              (call/cc
                (lambda (resume)
                  (with-mutex (queue-lock queue)
                    (when (eq? job (hashtable-ref (queue-jobs queue) key #f))
                      (job-run-set! job (lambda () (resume #f)))
                      (queue-order-set! queue (append (queue-order queue) (list key)))))
                  ((queue-leave queue) #f)))
              (unless (and (current? queue job) (alive?))
                (finish! queue job) ((queue-leave queue) #f)))
            (set! deadline (sys:after 0.005)))))
      (job-run-set! job (lambda () (check!) (run check!)))
      (with-mutex (queue-lock queue)
        (unless (member key (queue-order queue))
          (queue-order-set! queue (append (queue-order queue) (list key))))
        (hashtable-set! (queue-jobs queue) key job)
        (unless (queue-started? queue) (queue-started?-set! queue #t) (fork-thread (lambda () (work! queue))))
        (condition-signal (queue-ready queue))))))
